### ISSUE TITLE
AvailableCourse, Course yerine CurriculumCourse ile ilişkilendirilmeli

### ISSUE THREAD

**Issue by dilara** [omu/nokul#1028]
#### İş kaydı

Açılan dersler ve müfredat paralel olarak geliştirilirken duruma uygun olarak AvailableCourse modeli Course ile ilişkilendirilmişti. Açılan derslerin öğrenciye sunulması ile ilgili çalışılırken alınan karar: 
Açılan derse ait yıl ve dönem, ects, zorunluluk bilgisinin kolayca erişilebilir olması adına, AvailableCourse modelinin CurriculumCourse ile ilişkilendirilmeli.

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [x] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] İş kaydı hata bildirimi veya ürün özelliği dışında bir niteliğe sahip
- [x] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

Related: #1009

**Comment by isubas** [comment]
#1098
