### ISSUE TITLE
Personel görevlendirilmeleri ve geçici görevlendirilmeleri görüntülenebilmeli

### ISSUE THREAD

**Issue by baran** [omu/nokul#1029]
#### Teknik borcun açıklaması
Personel modülünde, personel görevlendirilmelerinin görüntülenmesi işlevi gerçekleştirilecek.
- Bu issue'ya ait analiz @ekural tarafından eklenecek

[//]: # (Kısa ve net bir şekilde hatanın ne olduğunu açıkla.)

#### Geri ödeme planı

[//]: # (Borcun ödenmesi için neler yapılmalı?)
[//]: # (En geç ne zamana kadar ödeme yapılmalı?)
[//]: # (Örnek: En geç 2019 Kasım ayı sonuna kadar çözülmeli)
[//]: # (Örnek: "Falanca" milestone'dan önce çözülmeli)

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by baran** [comment]
Bu issue ile ilgili son durum nedir?

**Comment by ecmelkytz** [comment]
Burada geliştirme açısından beklenen tam olarak nedir?

**Comment by ecmelkytz** [comment]
**Not:** Kurum dışı görevlendirmeleri için diğer üniversite bilgilerine ihtiyaç var.

**Comment by baran** [comment]
> **Not:** Kurum dışı görevlendirmeleri için diğer üniversite bilgilerine ihtiyaç var.

Bu tip ihtiyaçlar yalnızca üniversiteler için geçerli değil. Diğer kurumların bilgilerine de ihtiyaç duyulacak. Örneğin KYK, KOSGEB, MSB gibi. O yüzden MEKSİS, YOKSİS gibi **DETSİS** bilgilerinin tamamının barındırılması gerekiyor.

**NOT** Mevcut hali ile **Birimler** yalnızca Ondokuz Mayıs Üniversitesi'ne ait birimler mevcut. Bu problemi çözmek için seçenekler:

- Birimler altına tüm kurumların DETSİS bilgileri girilerek (YOKSİS gibi güncellenmek koşulu ile)
- DETSİS tanımı bağımsız olarak **Tanımlar** altına alınarak bir düzenleme yapılması
