### ISSUE TITLE
Akademik personel Ar/Ge çalışmaları görüntülenebilmeli

### ISSUE THREAD

**Issue by baran** [omu/nokul#1030]
#### Teknik borcun açıklaması
Akademik personelin Ar/Ge faaliyetleri görüntülenebilmeli. @msdundar tarafından daha önce geliştirilmiş olan YÖK sistemlerinden alınan veriler kullanılarak görüntülenecek.

[//]: # (Kısa ve net bir şekilde hatanın ne olduğunu açıkla.)

#### Geri ödeme planı

[//]: # (Borcun ödenmesi için neler yapılmalı?)
[//]: # (En geç ne zamana kadar ödeme yapılmalı?)
En geç **Ekim ayı sonuna kadar** tamamlanmalı.

[//]: # (Örnek: En geç 2019 Kasım ayı sonuna kadar çözülmeli)
[//]: # (Örnek: "Falanca" milestone'dan önce çözülmeli)

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by ecmelkytz** [comment]
@omu/product, bu iş kaydının kapanması için sistemin şu an ki haline ek olarak eklenmesi gerekenleri söyler misiniz?

**Comment by baran** [comment]
Açılan iş kaydının gereksinimlerini karşıladığı için kapatıyorum. Ek özellik gerektiğinde, yeni bir iş kaydı **improvement** etiketiyle açılacaktır.
