### ISSUE TITLE
Akademik personelin eğitim performansı görüntülenebilmeli

### ISSUE THREAD

**Issue by baran** [omu/nokul#1031]
#### Teknik borcun açıklaması
Akademik personelin eğitim performansı **kalite modülünden** sorgulanarak görüntülenebilmeli.

[//]: # (Kısa ve net bir şekilde hatanın ne olduğunu açıkla.)

#### Geri ödeme planı

[//]: # (Borcun ödenmesi için neler yapılmalı?)
[//]: # (En geç ne zamana kadar ödeme yapılmalı?)
[//]: # (Örnek: En geç 2019 Kasım ayı sonuna kadar çözülmeli)
En geç **Ekim ayı sonuna kadar** tamamlanmalıdır.

[//]: # (Örnek: "Falanca" milestone'dan önce çözülmeli)

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by demir** [comment]
@baran hocam kalitede hocanın performansı ile ilgili bir bilgi yok şu anda.

**Comment by baran** [comment]
Personel performansının hesaplanmasında gerekli olan verilerin nasıl ve ne şekilde oluşturulacağı/alınacağı konusunu Vedat Hoca ile 7 Ekim Pazartesi günü bir araya gelip netleştireceğiz.

**Comment by baran** [comment]
Bu issue kalite tarafında kişisel performanslar tutulmaya başlandığında yeniden açılmak üzere kapatılmıştır.
