### ISSUE TITLE
MYO'da açılan bir program 8 dönemden oluşamaz

### ISSUE THREAD

**Issue by baran** [omu/nokul#1034]
#### Hatanın açıklaması
MYO'da tanımlanan bir program 8 dönem olarak belirtilmiş. Oysa ki 4 dönemden oluşmalı.

[//]: # (Kısa ve net bir şekilde hatanın ne olduğunu açıkla.  Varsa mutlaka ekran görüntüsü ekle.)

- [x] Ekran görüntüsü ekte

#### Hatayı tekrarlamak için takip edilmesi gereken adımlar
Herhangi bir programda müfredat tanımlanmak istendiğinde ilgili programın dönem sayısı parametrik olarak gelmeli. Program tanımlanırken dönem verisi girilmeli.

[//]: # (1. X adresinde bulunan Y sayfasına git.)
[//]: # (2. Z butonuna tıkla.)
[//]: # (3. Sayfayı en alta kaydır.)
[//]: # (4. Görünmesi gereken metin K iken L görünüyor.)

#### Olması gereken davranış

[//]: # (Kısa ve net bir şekilde uygulama davranışının ne olması gerektiğini açıkla.)
[//]: # (Örnek: X kaydı silindiğinde Z sayfasına yönlendirme yapılmalı.)

#### Hatanın alındığı ortam

- [x] Masaüstü

[//]: # (Belirtmediğiniz taktirde Ubuntu 18.04/Debian 9 üzerinde güncel Google Chrome kullandığınız varsayılacaktır.)
[//]: # (- OS: [ör. iOS, Windows 10])
[//]: # (- Browser [ör. Chrome, Safari])
[//]: # (- Version [ör. 22])

- [ ] Mobil

[//]: # (- Device: [ör iPhone6])
[//]: # (- OS: [ör. iOS8.1])
[//]: # (- Browser [ör. stock browser, Safari])
[//]: # (- Version [ör. 22])

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
![Screen Shot 2019-10-03 at 17 10 21](https://user-images.githubusercontent.com/283010/66134501-17ca4b00-e601-11e9-89e0-d9974e46e498.png)

[//]: # (Örnek çözümler)

**Comment by begum** [comment]
@baran hocam, yeni müfredat tanımlanırken dönem türü (yıllık/dönemlik) ve sayısı 1-12 arasında oluşturulabiliyor. 
![myo-müfredat](https://user-images.githubusercontent.com/338489/66190557-f6b33a00-e694-11e9-8c6a-ad9c6b563e6c.png)

**Comment by baran** [comment]
> @baran hocam, yeni müfredat tanımlanırken dönem türü (yıllık/dönemlik) ve sayısı 1-12 arasında oluşturulabiliyor.
> ![myo-müfredat](https://user-images.githubusercontent.com/338489/66190557-f6b33a00-e694-11e9-8c6a-ad9c6b563e6c.png)

Mesele **oluşturulabilmesi değil**, **_YÖK tarafından belirlenen kriterler üzerinden işlem yapmak zorundayız_**. Program açma konusunda da uyulması gereken kurallar var. Örneğin; açılacak program MYO ise yarıyıl değeri 4 olmak zorundadır. Dolayısıyla kullanıcının keyfiyetine bırakılacak bir veriden bahsetmiyoruz. Bu ve bunun gibi veriler otomatik olarak atanmalı. Aksi taktirde hatalara yol açabilir.

Öğrenci işleri ile uğraşanların bu bilgiye vakıf olmaları önemli değil. Sistemin kontrolünde olması gereken veri tipi bu ve bunun gibi durumlar.

**Comment by begum** [comment]
Aslında Yoksis verilerinde programın yıl bilgisi geliyor; bunu `duration` olarak birimlerde tutuyoruz. 
```
- name: Bilgisayar Mühendisliği Programı
  abbreviation: BİLGİSAYAR-PR
  yoksis_id: '168861'
  parent_yoksis_id: '122184'
  unit_type_id: Önlisans/lisans Programı
  unit_status_id: Aktif
  district_id: Atakum
  osym: '108210665'
  foet_code: '523'
  unit_instruction_language_id: Türkçe
  unit_instruction_type_id: Normal Öğretim
  duration: 4
  founded_at: 10.09.2009

- name: Bilgisayar Programcılığı Programı
  abbreviation: SAMSUN-MYO-BT-BP-PR
  yoksis_id: '169874'
  parent_yoksis_id: '169871'
  unit_type_id: Önlisans/lisans Programı
  unit_status_id: Aktif
  district_id: İlkadım
  osym: '108250346'
  foet_code: '481'
  unit_instruction_language_id: Türkçe
  unit_instruction_type_id: Normal Öğretim
  duration: 2

```
Ancak bazı programlar dönemlik bazıları yıllık (tıp, hukuk vb.) olduğu için bu şekilde seçime bırakmıştık. Mevcut yıl (duration) bilgisi kullanılarak yapılacak iyileştirmede muhtemel hatalar engellenebilir diye düşünüyorum.
