### ISSUE TITLE
Ders: Ders eklerken birim seçimini iyileştir

### ISSUE THREAD

**Issue by isubas** [omu/nokul#107]
Derslerin açılma şeklini belirle ve birim seçimini buna göre iyileştir.
Sorular:

- Dersler, birim altına girilerek hazırlanmış bir sayfa üzerinden mi eklenmeli?
- Halihazırdaki gibi dersler sayfası altında yeni ders ekleme formu kullanılarak, form üzerinden birim seçim işlemi yaparak mı oluşturulmalı?

**Comment by abdagli** [comment]
Selamlar @isubas Bu konu biraz da UX konusu. Süreçleri tasarlarken bunlarla ilgili biraz düşünme fırsatım oldu. Genelde gördüğümüz benzer yazılımlarda sol sidenav üzerinde çok fazla item var. Bu da UX açısından çok doğru gelmiyor bana. Çok fazla buton var. Bu tarz aksiyon butonları, ilgili kaydın altında olsa sanki daha temiz bir arayüze sahip oluruz. Zaten kullanıcı gözüyle de düşündüğümüzde, kullanıcı bir birime ders açacağını biliyor; dolayısıyla ilgili birime gidip Ders Ekle butonuna tıklamak daha pratik gelebilir diye düşünüyorum.
