### ISSUE TITLE
Ders görevlendirme işlemleri geliştirilmeli

### ISSUE THREAD

**Issue by baran** [omu/nokul#1071]
#### Kullanım senaryosu

[//]: # (Kullanım senaryosunu yaz veya dış bir dokümana bağlantı oluştur)
@ekural kullanım senaryosu ve UC'leri ekleyecek.

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Özellik ürün takımı tarafından incelendi ve onaylandı
- [ ] İş kaydını "Product" projesiyle ilişkilendirdim
- [x] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kullanım senaryosuna ilave açıklamalar)
[//]: # (Mockuplar)
[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by baran** [comment]
@ekural kullanım senaryolarıyla ilgili olarak durumumuz nedir? Malum @isubas kodlayabilmesi için elinde iş akış ve süreçlerinin olması gerekiyor.

**Comment by ekural** [comment]
Po tarafında 55 ve 56 nolu issuelar biraz daha vaktimi aldığı için buna hafta başında başladım. En kısa zamanda sonlandıracağım.

**Comment by baran** [comment]
Bu issue ile ilgili son durum nedir?

**Comment by isubas** [comment]
Bu işle ilgili süreçleri nasıl yönetebileceğimi tam kestiremediğimden ve sistem üzerinde düzeltme işlemleri yaptığımdan iş uzadı bu hafta bu işe üzerine çalışacağım.
