### ISSUE TITLE
Müfredat tanımlama geliştirmeleri yapılmalı

### ISSUE THREAD

**Issue by isubas** [omu/nokul#108]
### Sorulacak Sorular:
- Müfredat tanımlanırken, yıllık-dönemlik bilgisi müfredatta mı tanımlanmalı ?
- Dönemlik programlarda yıllık okutulan dersler var mı?
  - Yıllık okutulan dersler varsa halihazırda nasıl bir tanımlama yapılmış.

@abdagli @ekural

**Comment by abdagli** [comment]
#289
