### ISSUE TITLE
Ders kaydı için isimlendirme ve modelleme yapılmalı

### ISSUE THREAD

**Issue by dilara** [omu/nokul#1105]
#### İş kaydı
Ders kaydı için isimlendirme ve modelleme yapılmalı.

Öğrencinin aldığı dersler için model ismi olarak İrfan'dan gelen `CourseEnrolment` önerisi geldi. 

- Model nitelikleri: `:student_id,` `:available_course_id`.

- Ayrıca seçilen ders için taslak/kaydedilmiş/onaylanmış gibi bir durum da söz konusu. Ama ders kaydının tümü için mi bu durum, yoksa her ders ayrı onaydan mı geçecek?

- Öğrencinin geçmişe dayalı öğrenciliğinin kaçıncı yıl kaçıncı döneminde bu dersleri aldığını tutan bir nitelik de gerekli (`:year,` `:semester`).

Öğrenci modeline öğrencinin sınıf bilgisini eklemek konuşulmuştu, bir de eğitim yarıyılı bilgisi eklenmeli. Oğuz'dan gelen bilgiye göre mevcut sistemde aşağıdaki bilgiler tutuluyor. 
- Sınıf bilgisi : Yılda birkez artan veri. Eğitim öğretim başında manuel olarak artırılıyor.
- Kayıt yenileme yarıyılı : Öğrencinin ders kaydı yaptığı yarıyıl sayısı
- Eğitim yarıyılı : Müfredatında kaçıncı yarıyıla kadar takip ediyor.

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [x] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] İş kaydı hata bildirimi veya ürün özelliği dışında bir niteliğe sahip
- [x] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

Related: #1009 

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by begum** [comment]
#1236 merge ile bu issue tamamlanmış.
