### ISSUE TITLE
Ders kaydı için controller adı ve yollar yeniden düzenlenmeli

### ISSUE THREAD

**Issue by dilara** [omu/nokul#1106]
#### Teknik borcun açıklaması
Ders kaydı için controller adı ve yollar yeniden düzenlenmeli.

> Bu controller ismini `CourseEnrolmentsController` yapalım. (Eğer isimde herkes hem fikir olursa)
> Bu kontrolürü `CourseManagement` modülünün altından, `Studentship` modülü altına alalım `(Studentship` modülü yok oluşturalım), çünkü bu yapılan işler artık öğrencilikle ilgili olan işler. (Not: Modüle ismini `Student` yerine `Studentship` yazdım çünkü isim çakışması yaşanır. Eğer isimde herkes hem fikir olursa bu şekilde devam edelim.)
> `CourseEnrolmentsController'nın` `index` sayfasına ders kayıtlanma tarihleri, ders kayıtlanmasına engel olan durumlar hakkında bilgilendirmeler ve yapılan ders kaydının son durumunu koyalım. Bu sayfa üzerinden ders kayıtlanma sayfasına ulaşsın. `CourseEnrolmentsController'nın` `new' işlevinde ise ders kayıtlanma formunu görüntüleyelim.
> 

#### Geri ödeme planı
#1105 kapandığında çözülmeli.

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [x] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

Related: #1009, #1105 

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by begum** [comment]
#1236  merge ile bu issue tamamlanmış.
