### ISSUE TITLE
Parola sıfırlama linki hatalı servise gidiyor

### ISSUE THREAD

**Issue by roktas** [omu/nokul#1141]
#### Hatanın açıklaması

https://dev.nokul.omu.sh servisinde yapılan parola sıfırlama isteğine gelen link https://nokul.omu.sh'a çıkıyor.

- [ ] Ekran görüntüsü ekte

#### Hatayı tekrarlamak için takip edilmesi gereken adımlar

1. https://dev.nokul.omu.sh'a gir
2. Parola sıfırlama yap
3. Gelen linke tıkla

#### Olması gereken davranış

https://dev.nokul.omu.sh parola sıfırlama isteği yine aynı servise çıkmalı

#### Hatanın alındığı ortam

- [X] Masaüstü

- [ ] Mobil

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [X] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [X] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

**Comment by msdundar** [comment]
Bunun sebebi `dev.nokul.omu.sh` makinesinde `RAILS_ENV`'in `production` olarak set edilmesi. Dolayisiyla Tenant'in production ayarlarini okuyor: https://github.com/omu/nokul/blob/develop/plugins/tenant/omu/config/tenant.yml

**Comment by roktas** [comment]
Evet, dediğin gibi.  Daha ayrıntıya girecek olursak, mailer için tam olarak şurası: https://github.com/omu/nokul/blob/develop/config/environments/production.rb#L72

Hangi domain'de çalıştığımızı bu şekilde bir yapılandırma ayarına koymak doğru gelmiyor bana.  **Uygulama zaten bunu bilebiliyor olmalı**.  Kabaca baktığımda `request.base_url`, `request.domain` gibi yöntemler görüyorum.  Bu sorun (şimdilik) sadece ActionMailer'da; kodda `Tenant.configuration.host` araması yaptığımda ulaştığım sonuç. ActionMailer çalışmadan önce konulan bir filtreyle ismi çözebiliyoruz gibime geliyor.  Şöyle [şeyler](https://stackoverflow.com/questions/37732014/can-i-set-default-url-options-for-actionmailer-to-request-base-url-or-request-do)  Kalanını @ecylmz'ye bırakıyorum.

**Comment by ecylmz** [comment]
Parola sıfırlama maili devise üzerinden geldiği için, devise'ın önerdiği yöntem şuydu: https://github.com/plataformatec/devise/wiki/How-To:-Set-:host-and-:port-for-all-devise-mailer-urls

Ancak bu yöntem ile gidersek DeviseMailer'ı da şuradaki gibi özelleştirmiş olacaktık: https://github.com/plataformatec/devise/wiki/How-To:-Use-custom-mailer

Açıkcası bu yönteme pek sıcak bakmadığımdan ve 12 faktöre uygun bir yöntem bulmaya çalışınca; ilk olarak `HOST` ortam değişkenini okumaya çalıştım yoksa tenant'daki değeri default değer olarak kabul ettim. Ayrıca bu ayar 3 ortamda da aynı olduğundan, `config/application.rb` altına taşıdım.

https://github.com/omu/nokul/commit/b148be2f0cd0fe04ee95ac80528609f3043a2995

Değişikliği @isubas'ın açtığı bug-fixes dalına gönderdim. (@isubas'ın izniyle)

**Comment by roktas** [comment]
@ecylmz Bu durumda dev.nokul.omu.sh için hostname mi set edeceksin (veya zaten öyle mi bilmiyorum), o kısmı anlamadım.

**Comment by ecylmz** [comment]
evet dev.nokul.omu.sh için `HOST` ortam değişkenini set ettim sunucuda.

**Comment by roktas** [comment]
`HOST` kabuk veya bir başka kaynak tarafından atanan standart bir ortam değişkenidir, `USER`, `PWD`, `EUID` gibi (tam liste için örneğin şuna bak: https://fsl.fmrib.ox.ac.uk/fslcourse/unix_intro/environment.html).  Örneğin benim makinamda zsh altında ne değer veriyor?

```sh
$ echo $HOST
spinoza
```

Bu tür standart ortam değişkenleriyle "semantiğini bozacak" yönde oynamamalıyız, karışıklıktan başka bir sonuç vermez.  O bir yana çalışma ortamına bağlı olarak (örneğin ben de öyle çıktı) `HOST` değişkeni daima tanımlı olduğundan `Tenant.configuration`'a düşmezsin bile.

`HOST` yerine başka bir ortam değişkeni bulalım (düşünüyorum)...

**Comment by ecylmz** [comment]
Hmm evet haklısınız hocam, zsh'ta `HOST` değişkeni kullanılıyor. Aklıma gelmemişti yazarken. 
`APP_URL`, `HOSTNAME`, `MAILER_HOSTNAME` aklıma gelen değişken isimleri.

**Comment by roktas** [comment]
Mevcut durumda `NOKUL_TENANT` ortam değişkenimiz var, **şimdilik** o konvansiyonla ilerleyelim: `NOKUL_HOST` olabilir.  Gelecekte gerekirse daha farklı bir isim (veya yöntem) kullanabiliriz.
