### ISSUE TITLE
Hesap aktivasyon ekranı daha anlaşılır olmalı

### ISSUE THREAD

**Issue by roktas** [omu/nokul#1142]
#### Kullanım senaryosu

Mevcut durumda gelen ekranda Seri, Seri No ve Doküman No alanlarının ne olduğu yeni bir kullanıcı için belirsiz

![resim](https://user-images.githubusercontent.com/47842/67548922-c8f96800-f70b-11e9-8188-b0c6b0bf29f0.png)

- Bu alanların anlamı uygun UX düzenlemeleriyle açık hale getirilmeli.  Örneğin (1) tool tip ve (2) `?` butonları kullanılarak açıklama eklenebilir (sadece birini değil ikisini birlikte yapmak daha uygun, tool tip kaçırılabilir).  Ayrıca bu düzenleme yapılacaksa (diğer alanlar açık olmakla birlikte) tüm alanlarda olmalı.

- "Doküman No" yerine daha uygun bir karşılık bulabilir miyiz?  "Kimlik Doküman No" gibi?

- (Anladığım kadarıyla) Eski kimlik kartları için Seri, Seri No, yeniler için Doküman No kullanılıyor.  Bu ikisinin aynı ekranda olması kullanıcıya hepsini birlikte girmesi gerektiği izlenimi veriyor.  Bunu nasıl düzeltebiliriz düşünelim.  Örneğin sadece Doküman No görüntüleyip yanına "Eski kimlik kartı kullanıyorum" gibi bir tik koyup ona tıklandığında bu alanların açılması gibi.  Zor bir UX...

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [X] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [X] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [X] Özellik ürün takımı tarafından incelendi ve onaylandı
- [X] İş kaydını "Product" projesiyle ilişkilendirdim
- [X] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

**Comment by ekural** [comment]
Bu konuyla ilgili çalışma yaparken başlangıçta "Kimlik kartı" ve "Nüfus cüzdanı" gibi seçenekler vardı. Sonraki aşamada hepsinin tek sayfada olması, hangisiyle ilgili bilgileri doldurursa diğer alanların pasif hale geçmesi fikri onaylanmıştı ([Mockup'taki 1 nolu alternatif](http://po.omu.sh/nokul/mockups/user/?to=883171AC-848B-4C5A-80F3-8AA1E6D8707C)). Daha ileri aşama için çözüm önerisi olarakta Kimliklerin görselleri gösterilip direkt görsel üzerinden doldurulması fikri ortaya çıkmıştı ([Mockuptaki 2 nolu alternatif](http://po.omu.sh/nokul/mockups/user/?to=A527FB2D-D17D-4529-BCDA-DD1E7656E337)). 

Şuandaki durumda karışıklığı ortadan kaldırmak için @roktas'ın söylediği gibi kimlik kartı ile ilgili bir seçim koyup bu seçimin yanına bir ? vs. ile eski ve yeni kimlik kartlarının görsel örneklerini girilmesi istenen alanlar işaretli bir sekilde koyabiliriz.

**Comment by isubas** [comment]
Bu issue için ufak düzenleme yaptım, eğer onaylanırsa aşağıdaki gibi devam edelim.

![image](https://user-images.githubusercontent.com/5476376/67945594-59461a00-fbf0-11e9-84a7-8906d7300a3c.png)
![image](https://user-images.githubusercontent.com/5476376/67945607-62cf8200-fbf0-11e9-87da-66a8ba700554.png)

**Comment by baran** [comment]
> Bu issue için ufak düzenleme yaptım, eğer onaylanırsa aşağıdaki gibi devam edelim.

Yabancı uyruklu öğrencilerin kullanımı için **pasaport** ile de aktivasyon yapılabilir. Pasaport seçeneğini ekleyebiliriz.
