### ISSUE TITLE
Meksis yeni mekan türü eklenirken hata veriyor

### ISSUE THREAD

**Issue by begum** [omu/nokul#1157]
#### Hatanın açıklaması

Meksis altındaki ana mekan türleri sayfasında "Yeni Mekan Türü" butonu hata veriyor.

- [ ] Ekran görüntüsü ekte

#### Hatayı tekrarlamak için takip edilmesi gereken adımlar

1. Yönetim / Meksis / Ana Mekan Türleri sayfasına git.
2. Yeni Mekan Türü butonuna tıkla.
(https://dev.nokul.omu.sh/meksis/place_types/new)
 
#### Olması gereken davranış

Mekan türlerini Meksis'ten çekiyorsak, manuel mekan türü ekleme yapılmamalı.

[//]: # (Kısa ve net bir şekilde uygulama davranışının ne olması gerektiğini açıkla.)
[//]: # (Örnek: X kaydı silindiğinde Z sayfasına yönlendirme yapılmalı.)

#### Hatanın alındığı ortam

- [x] Masaüstü

[//]: # (Belirtmediğiniz taktirde Ubuntu 18.04/Debian 9 üzerinde güncel Google Chrome kullandığınız varsayılacaktır.)
[//]: # (- OS: [ör. iOS, Windows 10])
[//]: # (- Browser [ör. Chrome, Safari])
[//]: # (- Version [ör. 22])

- [ ] Mobil

[//]: # (- Device: [ör iPhone6])
[//]: # (- OS: [ör. iOS8.1])
[//]: # (- Browser [ör. stock browser, Safari])
[//]: # (- Version [ör. 22])

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by huseyin** [comment]
thanks @begum. [Buradaki](https://github.com/omu/nokul/blob/develop/app/views/meksis/place_types/index.html.erb#L1) layout'tan otomatik geliyor o link. Düzeltiyorum...
