### ISSUE TITLE
Ders değerlendirme türleri yüzdelik toplamı %100'ü geçmemeli

### ISSUE THREAD

**Issue by begum** [omu/nokul#1159]
#### Hatanın açıklaması

Açılan derse eklenen ders değerlendirme türleri toplamı için %100 kontrolü yapılmıyor.

[//]: # (Kısa ve net bir şekilde hatanın ne olduğunu açıkla.  Varsa mutlaka ekran görüntüsü ekle.)

- [x] Ekran görüntüsü ekte

#### Hatayı tekrarlamak için takip edilmesi gereken adımlar

1. Ders işlemleri / Açılan dersler sayfasına git.
2. Açılan derslerden biri için farklı değerlendirme türlerini yüzdelik toplamı 100'ü geçecek şekilde kaydet.
ör: https://dev.nokul.omu.sh/available_courses/7

[//]: # (1. X adresinde bulunan Y sayfasına git.)
[//]: # (2. Z butonuna tıkla.)
[//]: # (3. Sayfayı en alta kaydır.)
[//]: # (4. Görünmesi gereken metin K iken L görünüyor.)

#### Olması gereken davranış

Değerlendirme türlerinin toplamı %100'ü aşmamalı.
(bk. [ONDOKUZ MAYIS ÜNİVERSİTESİ EĞİTİM-ÖĞRETİM VE SINAV YÖNETMELİĞİ, Altıncı Bölüm, Madde 27 - 1](http://www.omu.edu.tr/sites/default/files/files/3-2015-29512%20OM%C3%9C%20E%C4%9E%C4%B0T%C4%B0M-%C3%96%C4%9ERET%C4%B0M%20VE%20SINAV%20Y%C3%96NETMEL%C4%B0%C4%9E%C4%B0.pdf))

[//]: # (Kısa ve net bir şekilde uygulama davranışının ne olması gerektiğini açıkla.)
[//]: # (Örnek: X kaydı silindiğinde Z sayfasına yönlendirme yapılmalı.)

#### Hatanın alındığı ortam

- [x] Masaüstü

[//]: # (Belirtmediğiniz taktirde Ubuntu 18.04/Debian 9 üzerinde güncel Google Chrome kullandığınız varsayılacaktır.)
[//]: # (- OS: [ör. iOS, Windows 10])
[//]: # (- Browser [ör. Chrome, Safari])
[//]: # (- Version [ör. 22])

- [ ] Mobil

[//]: # (- Device: [ör iPhone6])
[//]: # (- OS: [ör. iOS8.1])
[//]: # (- Browser [ör. stock browser, Safari])
[//]: # (- Version [ör. 22])

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

![değerlendirme-türü](https://user-images.githubusercontent.com/338489/67947738-5e599800-fbf5-11e9-870d-da16ea9266f4.png)

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by ecmelkytz** [comment]
Bakıyorum

**Comment by ecmelkytz** [comment]
Buradaki asıl sıkıntı değerlendirme kriterlerinin yüzdelik dilimlerini kullanıcıdan aldığımız için yaşanıyor. Aslında bu yüzdelik dilimler yönetmelikte tanımlandığı gibi dönem içi %40, dönem sonu %60(diş hariç) olmak üzere ders açılırken otomatik oluşturulması gerekiyor. Bu değerler otomatik geleceği ve biri tarafından değiştirilemeyeceği için böyle bir problemle karşılaşmamış olacağız.

Yapacağım validasyon düzenlemesi "Dönem içi değerlendirme" ve "Dönem sonu değerlendirme" türlerinin toplamını kontrol etmek ve aynı zamanda "Dönem sonu değerlendirme" ve "Bütünleme Değerlendirme" değerlerinin aynı olmasını sağlamak olacak. Değerlendirme türlerini `EvaluationType` modelinde tuttuğumuz için `name` alanlarına göre kontrol edeceğim. Kayıttaki bu string değer değiştiğinde validasyonunda değişmesi gerekecek. Açıkçası bu hali hem geçici çözüm olacağı için hem de içime sinmediği için yönetmelik devreye girdiğinde halledilmesi gereken bir sorun olarak görelim derim.
