### ISSUE TITLE
Sidebar geliştirilmeli

### ISSUE THREAD

**Issue by baran** [omu/nokul#1179]
#### Kullanım senaryosu

Kullanıcı rollerine göre menü organizasyonu yapılacak.

[//]: # (Kullanım senaryosunu yaz veya dış bir dokümana bağlantı oluştur)

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [ ] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Özellik ürün takımı tarafından incelendi ve onaylandı
- [x] İş kaydını "Product" projesiyle ilişkilendirdim
- [x] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kullanım senaryosuna ilave açıklamalar)
[Analiz dokümanı](https://github.com/omu/po/issues/56)

[//]: # (Mockuplar)
[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by abdagli** [comment]
ref: #969
