### ISSUE TITLE
Personel sicil numarası kişiye özel ve tekil olmalı

### ISSUE THREAD

**Issue by begum** [omu/nokul#1180]
#### İş kaydı

Sistemde tanımlanmış bir kişi için personel kayıtları farklı sicil numaraları ile oluşturulabiliyor. Sicil numarası personele özgü ve tekil olmalı.

[//]: # (Kısa ve net şekilde iş kaydının hedeflediği problemi tanımla)
[//]: # (Kısa ve net bir şekilde çözüm önerini yaz)

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [ ] İş kaydı hata bildirimi veya ürün özelliği dışında bir niteliğe sahip
- [ ] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [ ] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [ ] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

![sicilno](https://user-images.githubusercontent.com/338489/68301046-2ac4b500-00b0-11ea-9dbb-ef20bf12c65c.png)

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by ekural** [comment]
Kurum sicil numaraları personel daire başkanlığı tarafından verilen, kadro tipi ile ilişkili olarak kullanılan bir kod. Kadro tipi ile ilişkili numara ve sicil numarası karakter sayısı bizim pdb tarafından yapılan bir seçim. Bu nedenle mevcut durumda "Sicil numarası personele özgü ve tekil olmalı" ifadesi doğru ancak "bir kişi için personel kayıtları farklı sicil numaraları ile oluşturulabiliyor" ifadesi tam olarak doğru değil.

Birinci kısmı açıklarsak bir sicil no yalnızca bir kişiye verilebilir. Pasif durumda dahi olsa aynı sicil no yeni gelen farklı bir personele verilmez. Ancak bir sicil no aynı kişinin farklı personelliklerine verilebilir (gidip geri gelme, aynı türde farklı kadroya geçme vb.).
İkinci kısım için ise örnek olarak bir kişi üniversitede hizmete sürekli işçi olarak başlayabilir. Bu durumda sicil numarası D kod ile başlar. Hizmetinin sonraki yıllarında öğretim görevlisi gibi bir kadroya geçiş yaptığında bu sicil numarası A kod ile değiştirilerek faklı bir sicil no verilecektir.

Buradaki validasyon bir sicil numarası tekil olmalıdır ancak bir kişinin farklı personelliklerinde kullanılabilir biçiminde olmalı.

**Comment by ecmelkytz** [comment]
Personelin sicil numarasında bir değişiklik yapılacaksa yeni bir personel kaydı oluşturulacak. Sicil numarası değişmeyecekse yeni bir personel kaydı oluşturmadan pasif olan kayıt aktifleştirilecek. 

Sonuç olarak sicil numaraları personele özgü olmalı ve kişiye birden fazla sicil no tanımlaması yapılabilmeli.

**Comment by baran** [comment]
> Sonuç olarak sicil numaraları personele özgü olmalı ve kişiye birden fazla sicil no tanımlaması yapılabilmeli.

Akademik yada idari personel olarak **her ikisinden de bir tane** sicil numarası olabilir demek daha doğru bir ifade olur.
