### ISSUE TITLE
CoreUI paket ismi güncellenmeli

### ISSUE THREAD

**Issue by wemrekurt** [omu/nokul#1198]
#### Hatanın açıklaması

Projede `yarn install` denildiğinde en son adımda sonsuz bir bekleyişe geçiyor. 17 gün önce bir sürüm [yayımlanmış](https://www.npmjs.com/package/@coreui/coreui), bununla alakalı olabilir.

- [x] Ekran görüntüsü ekte

#### Hatayı tekrarlamak için takip edilmesi gereken adımlar

```bash
rm -rf node_modules
rm -rf ~/.yarn-cache/
mkdir -p ~/.yarn-cache
yarn cache clean
yarn install

```

#### Olması gereken davranış

Sorunsuz bir şekilde paketleri kurmalı.

#### Hatanın alındığı ortam

- [ ] Masaüstü

[//]: # (Belirtmediğiniz taktirde Ubuntu 18.04/Debian 9 üzerinde güncel Google Chrome kullandığınız varsayılacaktır.)
[//]: # (- OS: [ör. iOS, Windows 10])
[//]: # (- Browser [ör. Chrome, Safari])
[//]: # (- Version [ör. 22])

- [ ] Mobil

[//]: # (- Device: [ör iPhone6])
[//]: # (- OS: [ör. iOS8.1])
[//]: # (- Browser [ör. stock browser, Safari])
[//]: # (- Version [ör. 22])

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [x] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

Ekran Görüntüsü:

![Screenshot from 2019-11-11 13-31-01](https://user-images.githubusercontent.com/10333281/68580524-9a0f2000-0487-11ea-984e-0edea7d4cc52.png)

Örnek Çözüm:

`package.json:`

```json
"@coreui/coreui": "^2.1.16",
```

**Comment by msdundar** [comment]
Hatayi tekrar edemedim, belki de duzeltilmistir:

```
rm -rf node_modules
rm -rf ~/.yarn-cache/
mkdir -p ~/.yarn-cache
yarn cache clean
yarn install
yarn cache v1.19.0
success Cleared cache.
✨  Done in 16.11s.
yarn install v1.19.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > webpack-dev-server@3.9.0" has unmet peer dependency "webpack@^4.0.0".
warning "webpack-dev-server > webpack-dev-middleware@3.7.2" has unmet peer dependency "webpack@^4.0.0".
[4/4] 🔨  Building fresh packages...
✨  Done in 40.27s.
```

**Comment by roktas** [comment]
Kapatıyorum, gerekirse tekrar açarız.
