### ISSUE TITLE
İş atama ve takip modülü EBYS entegrasyonu için sorguları hazırla

### ISSUE THREAD

**Issue by sinansh** [omu/nokul#1232]
#### İş kaydı

[//]: # (Kısa ve net şekilde iş kaydının hedeflediği problemi tanımla)
[//]: # (Kısa ve net bir şekilde çözüm önerini yaz)

#1210 id kayıtlı iş kaydı ile oluşturulmuş bir alt iş kaydıdır. 

EBYS entegrasyonu kısmında veritabanından veri okuma yöntemi için sql sorgularının hazırlanması gerekmektedir. 

Sorgu Listesi: 
* EBYS Kullanıcı_ID arama
* EBYS Havale Takip(Asil Yaptığım ve Gereği olarak havale edilenler)

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [x] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [ ] İş kaydı hata bildirimi veya ürün özelliği dışında bir niteliğe sahip
- [x] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by sinansh** [comment]
Sistemi tam olarak anlayabilmek için yönetim panelinde bulunan iki menü için detaylı kullanım kılavuzu talep ettim. 

![Screen Shot 2019-11-21 at 10 09 29](https://user-images.githubusercontent.com/9765995/69315217-10a9db80-0c47-11ea-89c6-5c18e8b35326.png)

**Comment by baran** [comment]
Başka bir özellik için EBYS tabloları analiz etmiştim. Gerekli sorgularda hazırlandı. Bu issue'ya uygun olarak düzenlenerek paylaşılacak.
