### ISSUE TITLE
Zorunlu dersler öğrencinin seçilen derslerine otomatik olarak eklenmeli

### ISSUE THREAD

**Issue by dilara** [omu/nokul#1235]
#### Teknik borcun açıklaması
Öğrencinin ders seçiminde zorunlu derslerin seçim listesine otomatik olarak eklenmesi gerekli.

#### Geri ödeme planı
Özelliğin nasıl gerçekleneceği üzerine düşünülmeli. Planlanmak üzere sonraya bırakıldı.

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by isubas** [comment]
İlerliyen bir zamanda gözden geçirilip, gerekirse tekrardan açılmak üzere kapatıyorum.
