### ISSUE TITLE
Öğrencinin kaldığı ders(ler)in özet tabloda tutulmasını sağla

### ISSUE THREAD

**Issue by baran** [omu/nokul#1237]
#### Kullanım senaryosu

[//]: # (Kullanım senaryosunu yaz veya dış bir dokümana bağlantı oluştur)
Öğrencilerin ders kaydı işlemleri sırasında, sistem yükü oluşturacak sorguların azaltılması ve işlemlerin hızlı bir şekilde tamamlanabilmesi amacıyla **dönem sonlarında (akademik takvime göre tüm süreçler tamamlandığı tarih itibari ile)** herbir öğrencinin **GANO** ve **kaldığı ders(ler)i** özet bir tabloda tutulacak.

Bu işlemi akademik takvime göre çalışacak bir arka plan görevi gerçekleştirecek. Bu görevin durumu **NOKUL** tarafından takip edilecek. Bu görevin **tamamlandığı** bilgisi ile ***bir sonraki dönem işlem yapılabilir*** duruma gelmiş olacak.

STUDENT_TERM_SUMMARY |  
-- | --
term_id | integer
student_id | integer
course_ids | array
gano | decimal
total_ects | decimal

```
unique_key -> [term_id, student_id]
```

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [ ] Özellik ürün takımı tarafından incelendi ve onaylandı
- [ ] İş kaydını "Product" projesiyle ilişkilendirdim
- [x] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kullanım senaryosuna ilave açıklamalar)
[//]: # (Mockuplar)
[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by msdundar** [comment]
https://pganalyze.com/blog/materialized-views-ruby-rails

**Comment by baran** [comment]
Makale ile ilgili olarak tekniğin uygulanması konusunda temelde iki amacın olabileceğini gördüm.

1. Bu işlemi vt üzerinde yaparak bir "sistem görevi" olmaktan çıkarmak.
2. VT'nin sahip olduğu yetenekleri kullanarak sağlam ve hızlı bir çözüme ulaşmak.
 
Her iki seçenek için GYZY analizi yaptığımda (aklıma gelenleri hızlıca listeliyorum belki sayısı artabilir);

- Veritabanı bağımlı olmak (tercihen kullanmamızın bağımlılık haline gelmesi görece sorun olabilir)
- Veritabanı bağımlı olmak problem olmasa dahi yapılacak işlemlerin bir takım vt fonksiyonlarına/prosedürlerine ihtiyacı nedeniyle "test" süreçlerinin nasıl yönetileceği sorunu ile karşı karşıya kalıyoruz. 

Oracle günlerimden kalan tecrübeleriminden yola çıkarak bu tip bir çözüm oldukça hızlı sonuç döneceği gerçeğini de yadsımıyorum. Üzerinde düşünülmesi gereken en önemli konu **TEST** işlemlerinin nasıl yönetileceği. Şayet bununla ilgili uygulanabilir yöntem(ler) var ise bu yöntemi kullanmak son derece faydalı olur kanaatindeyim.

**Comment by roktas** [comment]
> Veritabanı bağımlı olmak

"Tüm servislerde VT olarak Postgres kullanalım" kararı verirken bunu epey düşünmüştük.  Postgres'in zengin ekosistemini (heroku'da default seçenek), açık kaynak free software olmasını vs dikkate alarak vardığımız sonuç, "varsın postgres" bağımlı olsun idi.  Bence bağımlılık konusunu dikkate almayalım, postgres bir sabitemiz olsun.  (Böyle baka sabitler de var, yeri geldiğinde listelerim.)

**Comment by msdundar** [comment]
Muhtemelen ufak bir eforla mevcut veritabani MySQL'de de calisabilir hale gelir, daha once AIS'i mySQL'den PostgreSQL'e tasimistik, cok sorun cikarmamisti, tam tersi de cok sorun cikarmaz diye tahmin ediyorum. Bir ara hem Postgre hem de MySQL'de uyumlu olsun diye bi dusuncem olmustu ama bunu maintain etmek cok yorucu oldugu icin vazgecmistik. Suanki haliyle full text search (`pg_search`) ve constraint'ler acisindan PostgreSQL bagimliligimiz var.
