### ISSUE TITLE
Akademik faaliyetlere sayfalama eklenmeli

### ISSUE THREAD

**Issue by ekural** [omu/nokul#1256]
#### Teknik borcun açıklaması
Akademik faaliyetlerde makale, bildiri gibi içeriklerin çok fazla olması durumunda sayfa görünümü çok uzuyor. Bu alanlar paginate edilmeli.

#### Geri ödeme planı
İlgili alanlar paginate edilmeli.

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

**Comment by ekural** [comment]
İrfan son commitinde sayfalamaları ekledir. Bu issue'ya gerek kalmadı.

![pagy](https://user-images.githubusercontent.com/19164518/69804594-fb592200-11ef-11ea-8787-964758d32b8b.png)

**Comment by roktas** [comment]
Ekran görüntüsünde sondaki etiket dikkatimi çekti `-tübitak 1001`.  Sanıyorum kaynağında öyle yazılmış ama bir ara bu etiketleri de son işlemeden geçirmemiz de yarar var (aciliyeti olmayan bir iş).

**Comment by begum** [comment]
#1257 merge ile bu issue tamamlanmış.
