### ISSUE TITLE
Mekan raporu logolari tenant'tan okumali

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#1262]
#### Hatanın açıklaması

[//]: # (Kısa ve net bir şekilde hatanın ne olduğunu açıkla.  Varsa mutlaka ekran görüntüsü ekle.)

- Mekan yonetimi raporunda (PDF) `omu` ve `baum` logolari hard-coded durumda, bunlarin tenant'tan okunmasi gerekiyor.
- `university_name` locale'ler icine 'Ondokuz Mayis Universitesi' olarak yazilmis, bu da tenant'tan okunmali.
- Logolar tenant altinda bulunmali, `assets` altinda degil.
- `/meksis/omu.jpg` dosyasi 801KB ve 3508 × 3508 boyutunda 💥
- Raporda sayilar human-readable'a donusturulmeli. `1,51 Bin` gibi degerler kafa karistirici, bunun yerine 1513 gibi bir rakam gormek daha mantikli.

#### Hatanın alındığı ortam

- [X] Masaüstü

[//]: # (Belirtmediğiniz taktirde Ubuntu 18.04/Debian 9 üzerinde güncel Google Chrome kullandığınız varsayılacaktır.)
[//]: # (- OS: [ör. iOS, Windows 10])
[//]: # (- Browser [ör. Chrome, Safari])
[//]: # (- Version [ör. 22])

- [X] Mobil

[//]: # (- Device: [ör iPhone6])
[//]: # (- OS: [ör. iOS8.1])
[//]: # (- Browser [ör. stock browser, Safari])
[//]: # (- Version [ör. 22])

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [X] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [X] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

**Comment by roktas** [comment]
@huseyin /CC
