### ISSUE TITLE
Course Enrollment PR'ı sonrası db:migrate hata veriyor

### ISSUE THREAD

**Issue by ecylmz** [omu/nokul#1275]
#### Hatanın açıklaması

Course Enrollment PR'ı sonrası, sunucuda çalıştırılan db:migrate komutu hata veriyor.

Log: https://gist.github.com/ecylmz/459045d53685831e3cb0e1dbeba2b3aa

#### Hatayı tekrarlamak için takip edilmesi gereken adımlar

Terminalden production'a deploy isteği yapılmalı ya da Travis'teki deploy görevi yeniden çalıştırılmalı.

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

**Comment by roktas** [comment]
@dilara Bunu acilen bakalım, deploylar gecikmesin, @ecylmz de yardımcı olacaktır

**Comment by dilara** [comment]
@ecmelkytz belirtmişti bunu review'inde, PR'ın veritabanına etkilerini güncellemem gerekiyordu, afedersiniz. Student modeline eklenilen `null: false` niteliklerden kaynaklı olmalı sorun. Develop'taki `Student` verileri önemli durumda mı? Eğer değilse bu veriler silindikten sonra migrate edilebilirse sorun oluşmayacaktır. Aksi durumda başka bir çözüm üretelim.

**Comment by roktas** [comment]
@dilara Sıkıntı yok :-) Review'leri okudum ve bilerek merge ettim.  Önemli olan bu PR sürecinde yaşadığın deneyim ve code base'i tanıman.  Sorunlar her zaman olur ve düzeltilir.  Eline sağlık tekrar.

**Comment by dilara** [comment]
@roktas tamam hocam, sağ olun.

**Comment by ecylmz** [comment]
Eklenen migrate dosyasında, mevcut students tablosuna yeni bir alan eklenmiş ve bu alana "null constraint"  uygulanmış ancak bu alanın default değeri yok. Tablo ilk kez oluşturuluyorsa "null constraint" uygulanan alanın default değerinin olmasına gerek olmayabilir ancak bizim örnekte olduğu gibi mevcut bir tabloya yeni bir alan ekliyorsak ve "null constraint" uyguluyorsak, bu alana default değer koymak zorundayız.

Önümüzde 2 seçenek var:

- acme'de test amaçlı kullanılan 6 öğrenciyi silmek.(omü'de öğrenci yok)
- migrate dosyasına default değer eklemek. https://github.com/omu/nokul/blob/develop/db/migrate/20191021073002_add_semester_and_year_to_students.rb

Veri silme işlemi normal şartlar altında ihtimal dahilinde olamaz. "omü" tenant'ında kesin kayıtlı bir öğrenci olmamasından dolayı, acme'de test amaçlı oluşturulan 6 öğrenciyi silebiliriz.

**Comment by msdundar** [comment]
Bu duzeltildikten sonra bir de release ciksak mi? `develop..master` cok farklilasmis.

**Comment by ecylmz** [comment]
Acme'de kesin kayıtlanmış 6 öğrenciyi sildim.
https://acme.omu.sh güncel.
