### ISSUE TITLE
manifest.json 401 dönüyor

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#1280]
#### Hatanın açıklaması

[//]: # (Kısa ve net bir şekilde hatanın ne olduğunu açıkla.  Varsa mutlaka ekran görüntüsü ekle.)

`manifest.json` dosyasi okunamiyor ve 401 dönüyor.

<img width="612" alt="Screenshot 2019-12-05 at 04 07 56" src="https://user-images.githubusercontent.com/468744/70200768-d6dfd700-1714-11ea-8814-dc90382ba209.png">

#### Hatayı tekrarlamak için takip edilmesi gereken adımlar

[//]: # (1. X adresinde bulunan Y sayfasına git.)
[//]: # (2. Z butonuna tıkla.)
[//]: # (3. Sayfayı en alta kaydır.)
[//]: # (4. Görünmesi gereken metin K iken L görünüyor.)

1. https://dev.nokul.omu.sh adresine git.
2. Sag click, inspect.

#### Olması gereken davranış

[//]: # (Kısa ve net bir şekilde uygulama davranışının ne olması gerektiğini açıkla.)
[//]: # (Örnek: X kaydı silindiğinde Z sayfasına yönlendirme yapılmalı.)

Before:

```html
<link rel="manifest" href="manifest.json">
```

After:

```html
<link rel="manifest" href="manifest.json" crossorigin="use-credentials">
```

#### Hatanın alındığı ortam

- [x] Masaüstü

[//]: # (Belirtmediğiniz taktirde Ubuntu 18.04/Debian 9 üzerinde güncel Google Chrome kullandığınız varsayılacaktır.)
[//]: # (- OS: [ör. iOS, Windows 10])
[//]: # (- Browser [ör. Chrome, Safari])
[//]: # (- Version [ör. 22])

- [ ] Mobil

[//]: # (- Device: [ör iPhone6])
[//]: # (- OS: [ör. iOS8.1])
[//]: # (- Browser [ör. stock browser, Safari])
[//]: # (- Version [ör. 22])

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

**Comment by huseyin** [comment]
Bu hata basic auth olmasından kaynaklanıyor. @baran hocayla bakmıştık daha önce.

**Comment by roktas** [comment]
Bu yine de çözülebilir.  @ecylmz `/manifest.json` path için exclude koymak yeterli olmalı.  Örnek:

```
location /manifest.json/ {
        auth_basic off;
}
```

**Comment by roktas** [comment]
İlave olarak: https://thatemil.com/blog/2018/02/21/pwa-basic-auth/

**Comment by ecylmz** [comment]
> ```
> location /manifest.json/ {
>         auth_basic off;
> }
> ```

Bu örnek çalışmadı hocam. Tüm öneriler @msdundar'ın da yazdığı gibi:

```html
<link rel="manifest" href="manifest.json" crossorigin="use-credentials">
```

İtiraz yoksa develop dalına değişikliği göndereceğim.

**Comment by roktas** [comment]
@huseyin release yapmamışsan henüz bu değişikliği de master'a alıp tag'le
