### ISSUE TITLE
SSO Türkçe yerelleştirmesi yapılmalı

### ISSUE THREAD

**Issue by roktas** [omu/nokul#1291]
#### İş kaydı

LemonLDAP'ın Türkçe çevirileri eksik.  Production'da kullanıma geçmeden önce çevirileri tamamlamalıyız.  Çeviriler transifex üzerinden yapılıyor ama önce LemonLDAP geliştiricilerine Türkçe dilinin eklenmesi için istekte bulunmamız gerekiyor.  İzlenmesi gereken adımlar:

- [X] ~~LemonLDAP'a iş kaydı açarak Türkçe dil ekle, tercihen bir PR ile (@ecylmz)~~
- [x] Çevirmenler Transifex'te hesap aç (@begum ve @ekural) https://www.transifex.com/
- [x] Transifex lemonldap takımına Türkçe için kayıt ol (@begum ve @ekural) https://www.transifex.com/lemonldapng/lemonldapng/

İş paylaşımını yukarda belirttim.  @begum, @ekural stringleri aranızda paylaşın, çeviri tamamlandığında yer değiştirerek çeviri review'ı yapın.

#### Katkı sağlama

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [X] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [X] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [X] İş kaydı hata bildirimi veya ürün özelliği dışında bir niteliğe sahip
- [X] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

**Comment by roktas** [comment]
Dil ekleme işlemi tamam, @msdundar sağolsun.  Epey string var çevrilmesi gereken, @msdundar önden başlamış.  @begum ve @ekural takıma katılıp siz de başlayın bir yandan: https://www.transifex.com/lemonldapng/lemonldapng/

**Comment by msdundar** [comment]
Bir taraftan da tercume edilen string'lerin onaylanmasini saglamak icin reviewer yetkisi istedim. @ekural Xavier'e (proje sahibi) DM gondererek Turkce icin sizi proje koordinatoru, eger olmuyorsa en azindan reviewer yapmasini isteyebilirsiniz.

**Comment by msdundar** [comment]
Update: proje yoneticiligini aldik, dolayisiyla reviewer vs. atayabiliyoruz. Ek olarak yazisma sonucu gelen mesaj:

> There is 3 files, the most important is portal.json, then mail.json, then manager.json (the longer and needed only for administrator interface). Usually we (LLNG team) add those files until translation is around 90%. We just need a flag logo for each language. Additional detail: LLNG team add each file separately, so for example if only portal.json is translated (and if we have a flag logo), this file is added to next release.

Mevcut durum:

- `portal.json`: 57.86%
- `mail.json`: 93.75%
- `manager.json`: 20.2%

**Comment by begum** [comment]
@roktas, @ekural ile kayıt yapıp çevirilere başladık.

**Comment by roktas** [comment]
@ecylmz çeviriler bitip LLNG yeni sürümü kurulduğunda iş kaydını kapatalım.

**Comment by begum** [comment]
Çevirilerde son durum:
- portal.json: 100%
- mail.json: 100%
- manager.json: 100%

![Screenshot from 2019-12-13 15-22-59](https://user-images.githubusercontent.com/338489/70800163-963f2800-1dbc-11ea-882c-b8bf23b40004.png)

**Comment by roktas** [comment]
LLNG release'i beklemeyelim; kapatıyorum.  Katkı sağlayan herkesin ellerine sağlık.
