### ISSUE TITLE
Ders kaydı için eklenecek yeni modelin ismi belirlenmeli

### ISSUE THREAD

**Issue by dilara** [omu/nokul#1311]
#### İş kaydı
Ders kaydı için eklenecek yeni modelin ismi belirlenmeli.

- Nitelikler:
  - Durum: taslak, kaydedildi, tamamlandı vs.
  - Akademik dönem: ders kaydının gerçekleştiği akademik dönem
  - Yarıyıl: öğrencinin ders kaydını gerçekleştirdiği yarıyılı
- Ayrıca, öğrenci (Student) ve öğrencinin aldığı dersler (CourseEnrollment) ile ilişkilendirilecek.

Kayıttan alınacak örnek bilgi: "Öğrenci, eğitiminin 3. yarıyılında, 2019-2020 Güz döneminde, x, y, z, ... derslerini alarak ders kaydını tamamladı."

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] İş kaydı hata bildirimi veya ürün özelliği dışında bir niteliğe sahip
- [x] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by ekural** [comment]
Dün @huseyin ve @dilara ile konu ile ilgili biraz konuştuk. @huseyin ile "semester_registration" olarak fikir belirttik

**Comment by baran** [comment]
@dilara "semester_registration" olarak işlemi tamamlayalım. Tamamlandı ise issue'yu kapatalım.

**Comment by begum** [comment]
#1393 no'lu PR ile tamamlanmış.
