### ISSUE TITLE
Giriş ekranında BAUM sahipliğini ifade et

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#139]
Tartışmaya açayım, bunu eklemişsiniz ama login ekranındaki badge benim gözüme acayip alakasız görünüyor. Bu sayfada badge olmak zorunda mı? Değilse bunu kaldıralım düşüncesindeyim.

![screenshot from 2018-08-01 03-49-55](https://user-images.githubusercontent.com/468744/43494962-1fbb8730-953e-11e8-8a8d-b314dc40f09e.png)

**Comment by sinansahin** [comment]
footer'a copyright bilgisi(ref: [roktas's comment](https://github.com/omu/nokul/pull/124#issuecomment-405227353)), belki versiyon numarası bilgisi gelecek. Bunlarla birlikte düşünmek lazım. 

Burası üniversite dışından birinin OMÜ hangi firma ile çalışıyor diye bakmak istediğinde görebileceği alan olarak duruyor. Veya bunu biz yaptık diye gövde gösterisi yapabileceğimiz bir alan. Buraya birçok şey sayılabilir ama bence üst satırda bahsi geçen diğer objelerle birlikte tasarlanıp öyle tartışılmalı.

**Comment by roktas** [comment]
Tartışılması gereken issue'nun değişen title'ı.  Şimdilik bir kaç nedenle badge önerdim.  Rozet yani "badge" dediğimiz şey temelde **konstrantre** formda kimlik/sahiplik/aidiyet/vs ifade eden bir görsel öge (alternatifler: logo, ikon vs).  İlk bakışta (1) "baum"u ve uygulamanın mevcut "durumunu" görüyorsunuz ve tıklandığında daha geniş bir bilgiye ulaşılıyor.  Rozetin kullanım alanı Github README'leriyle sınırlı değil; böyle bir duruma alışmış olsak bile.

Rozet olur bir başka öge olur, BAUM'un geliştirdiği/bakımını yaptığı **her üründe** böyle standart bir ögeye ihtiyacımız var.  Bu karar üzerinde anlaşmışsak tartışmayı "peki bu öge ne olsun ve hangi işlevlere sahip olsun" yönünde yürütmemizde yarar var.  Ögenin işlevleri (ilk bakışta neler görünmeli, tıklandığında neler görünmeli) konusunda ayrıca yazacağım.  Mesela benim olmazsa olmazlarımdan biri tıklandığında o ürün üzerinde kimlerin katkı sağladığı bilgisinin mutlaka görünmesi.  BAUM kalite standartları (a la [The Tao of Hashicorp](https://www.hashicorp.com/blog/the-tao-of-hashicorp) gibi şeyler de) var aklımda.  Bunları bir karara bağlamak lazım.  Karar gecikecekse mevcut durumun şimdilik koruyalım derim.

**Comment by roktas** [comment]
Tartışmayı iki yönde sürdürelim: (1) form (şekil/şemal), (2) işlev.  İşlevi konusunda sanıyorum herkes az çok mutabık, sadece detayları belirlememiz lazım.  "Ögenin" formundan bahsedeyim biraz. Kanaatimce...

- Bu "öge" logo olamaz/olmamalı.  Yazıya da ihtiyacımız var.  Sadece grafiksel gidemeyiz, ifade tarzı fazlasıyla soyut olduğundan.
- Sadece yazı dikkate alınabilecek bir seçenek ("bir BAUM yapımı" gibi bir şey kullanıyorduk).  Ama ben biraz daha ikonik bir şey tercih ederim (o nedenle rozet).  Ama bu tercih bir yana güzel bir font family/size + içerikle yazı da olabilir.  Veya sadece bu amaçla geliştirilecek yeni bir rozet. 
- Sayfada çok fazla kamufle olmamalı, tıklanmaya veya hover yapılmaya teşvik etmeli.  İşte bu biraz "sayfada alakasız görünmeyi" gerektiriyor.  Tuvalet yazısı gibi bir şey :-P
- Footer'da ısrarlıyım.

**Comment by msdundar** [comment]
> İşlevi konusunda sanıyorum herkes az çok mutabık, sadece detayları belirlememiz lazım.

+1. İşlevi konusunda hem fikiriz hocam. Zaten bu badge'leri nokul'a ekleyen de benim. Yalnızca misafirlerin gördüğü sayfalarda çok havada kalmış, tasarımla bir bütünlüğü yok. Dolayısıyla önerim ya footer'a farklı bir konumlandırma yapalım, yada `guest` template'ini tekrar tasarlayalım.

**Comment by msdundar** [comment]
Yapılan değişiklikler dışında #152'ye başka istek gelmediği için bu issue'yu da kapatıyorum, yeni bir şey eklemek isteyen olursa tekrar açabilirsiniz.
