### ISSUE TITLE
Ruby 2.7.0'a yükseltilmeli

### ISSUE THREAD

**Issue by isubas** [omu/nokul#1392]
#### İş kaydı

- Uygulama genelinde ruby sürümü 2.7.0'a yükseltilmeli
- irb test edilerek pry yerine irb geçisi sağlanmalı

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [X] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [X] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [X] İş kaydı hata bildirimi veya ürün özelliği dışında bir niteliğe sahip
- [X] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[2.7.0 Release Detayları](https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/)

**Comment by huseyin** [comment]
Yerelde Ruby sürümünü yükselttim fakat çok fazla deprecation türü uyarı var. Çeşitli regresyonlara sebep olabilir. Log'ları aşağıya bırakıyorum.

https://gist.github.com/huseyin/36a7158400bd3882aca503302a2ea77d

**Comment by huseyin** [comment]
Biz kendi yazdığımız kodları Ruby 2.7.0 ile uyumlu hale getirelim bence önce. Gem'lerden gelen uyarıları sahipleri çözecektir. Yumuşak bir sürüm geçişi yapalım

**Comment by roktas** [comment]
Uyarıların çoğu keyword parametreleri için, bu beklediğim bir şeydi.  Dediğin gibi bu sorunları sahipleri çözecektir.  Bizim kodlara bakmak lazım.
