### ISSUE TITLE
Tekrarlı toggler ikonu

### ISSUE THREAD

**Issue by begum** [omu/nokul#140]
BAUM logosunun sağındaki toggler ikonu ve sidebarın sağ altında bulunan minimizer benzer işleve sahip. Tıklayınca paneli tamamen kapattığı için logonun yanındaki togglerın kaldırılması daha iyi olur diye düşünüyorum. 
![ekran goruntusu - 2018-08-01 15-12-46](https://user-images.githubusercontent.com/338489/43521036-8c10b9be-959d-11e8-8711-eccfd4392daa.png)

**Comment by msdundar** [comment]
Bence de toggler'ı kaldırabiliriz, sadece minimizer kalsın.

**Comment by isubas** [comment]
Toggle mobilde çok kullanışlı oluyor. Bu bakımdan ikisinin de durmasında bence bir sakınca yok.

**Comment by msdundar** [comment]
İrfan haklı, ben mobili hiç düşünmemiştim. Fikrimi mevcut şekliyle durması yönünde güncelliyorum.

**Comment by huseyin** [comment]
@isubas haklı 👍

**Comment by huseyin** [comment]
Red

**Comment by ecylmz** [comment]
Toggler yalnızca küçük ekranlarda görünmeli diyerek açtım pull request'i 😁 #148

**Comment by roktas** [comment]
"UX etiketinin vakti geldi" diye mırıldanırken baktım ki `msdundar added the UX  label 5 hours ago` :+1: 

UX konulu issue'ları açmaya devam edebilirsiniz, bu iyi de oluyor.  Söyleyeceğimi sakın yanlış anlamayın.  Ama şu dakika itibarıyla bir **patron** kuralı koyuyorum:  Aksi bir yorum yapılmadığı sürece ve tabii bu kural kaldırılıncaya kadar **UX konuları üzerinde fazla enerji harcamayın**.  Bu şu anlama da geliyor.  UX issue'larına çok uzun bir süre cevap dönülmeyebilir.  Issue raporlayanların hevesi kırılmasın.  Bu kural ne zaman kalkar?  Çok uzun bir yolumuz var maalesef.

**Comment by roktas** [comment]
UX'in öncelikli olmadığını söyledim, en yüksek önceliği de hemen not edelim: `bug` etiketi.  Yani bu demek oluyor ki bir etiket hem UX hem de bug ise bunun mutlaka çözülmesi gerekiyor.

**Comment by msdundar** [comment]
#148 derman oldu.
