### ISSUE TITLE
Türkçe - English yazısı ve bayrak ikonları

### ISSUE THREAD

**Issue by begum** [omu/nokul#141]
Dil butonlarında bayrak ikonları ve yazı yerine; http://www.omu.edu.tr/tr 'de sağ üstte bulunan TR/EN geçişi gibi olsa daha sade ve şık olur diye düşünüyorum.

![omu-en](https://user-images.githubusercontent.com/338489/43524775-c23c1d52-95a8-11e8-9948-2330a97429f5.png)

Bankalarda da benzer şekilde. Örneğin Akbank:
![akbank-en](https://user-images.githubusercontent.com/338489/43524846-f34c79c8-95a8-11e8-9086-96421cc387a6.png)

**Comment by msdundar** [comment]
Bu issue ile alakalı olarak, `guest` template'inde dil ikonları ile bildirimler üst üste biniyor, bunun da düzeltilmesi lazım.

![screenshot from 2018-08-01 17-30-45](https://user-images.githubusercontent.com/468744/43528037-b635fe26-95b0-11e8-8a3e-779cb5422d0a.png)
