### ISSUE TITLE
Kullanıcı profilleri sayfasında mernis'ten adres ve kimlik güncelle/oluştur butonları yok

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#144]
![screenshot from 2018-08-01 17-44-33](https://user-images.githubusercontent.com/468744/43528842-9168dd96-95b2-11e8-8701-820a6384a87e.png)

**Comment by msdundar** [comment]
@sinansh buna bakabilir misin?

**Comment by sinansh** [comment]
@msdundar hocam https://github.com/omu/nokul/pull/133 ile eklediğimiz fonksiyonlar üzerinden mi gitmeliyim? 

Gidersek controllerda bulunan aşağıdaki kodu nasıl düzenleyeceğiz?
https://github.com/omu/nokul/blob/develop/app/controllers/account/addresses_controller.rb#L50
```
def redirect_with(message)
  redirect_to(addresses_path, notice: t(".#{message}"))
end
```

**Comment by msdundar** [comment]
`AddressSaveJob` ve `IdentitySaveJob`'ları kullanmalısın. Yalnız `addresses_controller` kullanıcının kendi account'uyla ilişki olan controller. Sen bunu ayrı bir controller'da yapmalısın, mesela `users_controller`. Controller'a ekleyeceğin action sadece `AddressSaveJob` ve `IdentitySaveJob`'ı çalıştıracak.

**Comment by msdundar** [comment]
@sinansh ne durumdayız?

**Comment by sinansh** [comment]
Diş tedavisi sürecinden kaynaklı gecikme oldu hocam, toparlamaya çalışıyorum iki taraftaki işleri de. Bilgi işlem tarafında da işler var öncelikli olanları bitirmeye çalışıyorum.
