### ISSUE TITLE
Harç işlemleri UBYS üzerinden yönetilmeli

### ISSUE THREAD

**Issue by baran** [omu/nokul#1453]
#### Kullanım senaryosu

[//]: # (Kullanım senaryosunu yaz veya dış bir dokümana bağlantı oluştur)
Üniversitenin harç süreçleri sistem üzerinden takip edilmeli. Bu iş süreci [#11](https://github.com/omu/po/issues/11) analizine uygun olarak geliştirilecek.

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Özellik ürün takımı tarafından incelendi ve onaylandı
- [x] İş kaydını "Product" projesiyle ilişkilendirdim
- [x] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kullanım senaryosuna ilave açıklamalar)
[//]: # (Mockuplar)
[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by ecmelkytz** [comment]
Borçlandırma sürecinde düşündüğüm yöntemi hem tartışma anlamında hem de farklı fikirler olursa öğrenmek adına yazıyorum.

Yapılan analizleri([#11](https://github.com/omu/po/issues/11)) incelediğimde, her süreç için sırasıyla kontrol edilmesi gereken bazı durumların olduğunu görüyorum.
Örneğin ikinci öğretimde okuyan bir öğrencinin borçlandırma sürecinde şu durumlara sırasıyla bakılıp ona göre bir borçlandırma yapılmalı.

1. Burslu mu?
2. Engelli mi?

Bu koşulları operation olarak ele almayı düşünüyorum. Yani bunların kontrolleri single responsibility sağlanması adına  kendilerine ait bir sınıfta yapılacak. Bunları sırasıyla işletebilmek için de chain of responsibility tasarım deseninden faydalanarak bir zincir oluşturmayı düşünüyorum. 

İkinci öğretim öğrenci borçlandırma sürecinde oluşturulacak zincir örneği:
```ruby
#  pseudo code
chain = DebitService::ScholarshipOperation.new(DebitService::DisabledOperation.new)
```
Süreçte belirtilen zinciri takip ederek; kişi burslu ise borç oluşturulmayacak, burslu değilse engelli olup olmadığına bakılacak. Engelli ise engel yüzdesine göre indirim uygulanacak, engelli değilse borçlandırılacak. 

Bu şekilde her süreci kendi içerisinde düzenleyebiliriz diye düşünüyorum. Farklı borçlandırma durumlarında ya da problem büyüdükçe bu tasarım deseninin uymaması gibi öngöremediğim durumlar olabilir. Şimdilik aklımdakiler bunlar.
