### ISSUE TITLE
Engellilik bilgisi kişinin üzerinde tutulmalı

### ISSUE THREAD

**Issue by ecmelkytz** [omu/nokul#1456]
#### Kullanım senaryosu
Kişinin engel türü ve engellilik oranı `User`'da tutulmalı.

Şu an için sadece engel türü `prospective_student` modelinde tutuluyor. Buraya da engellilik oranı eklenmeli. Kişinin kesin kaydı yapılırken bu bilgiler user modeline aktarılmalı.

[//]: # (Kullanım senaryosunu yaz veya dış bir dokümana bağlantı oluştur)

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [x] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [ ] Özellik ürün takımı tarafından incelendi ve onaylandı
- [ ] İş kaydını "Product" projesiyle ilişkilendirdim
- [x] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kullanım senaryosuna ilave açıklamalar)
[//]: # (Mockuplar)
[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by roktas** [comment]
@ecmelkytz User modelini @isubas elden geçiriyor (bk ilgili dal), koordineli gitmenizde yarar var.
