### ISSUE TITLE
BAUM VPN için YOKSIS ve KPS'yi açtır

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#157]
YOKSIS ve KPS'ye erişememe sorunları sürekli olarak vaktimi çalmaya başladı. Bazen OMÜ VPN'in yavaşlığından, sıklıkla yanlışlıkla silinen ayarlardan bir türlü servislere erişemiyorum.

@ecylmz İsmail hocayla görüşerek senin kurduğun VPN'e YOKSIS ve KPS'yi açmasını söyleyebilir misin? Ayrıca açtıktan sonra mutlaka kontrol edelim, yapıldı deniyor sonra yine erişemiyoruz :)

**Comment by roktas** [comment]
Hüseyin sen konuşur musun?

**Comment by huseyin** [comment]
@roktas tamamdir hocam ben konuşurum

**Comment by sinansahin** [comment]
`Bazen OMÜ VPN'in yavaşlığından` bu sorunu yaşadığınız zamanları hatırladığınız kadarıyla bana mail atabilir misiniz ? Ulaknet kaynaklı problemlerden mi kaynaklanıyor yoksa firewall'da mı problem var incelemek istiyorum.

**Comment by huseyin** [comment]
@sinansahin Biz OpenVPN kullaniyoruz. ULAKNET'te sorun olsa biz de sorun yasamaliyiz. Sorun cok yuksek ihtimalle OMU VPN'de veya firewall'da.

**Comment by roktas** [comment]
@sinansahin aşağıdaki cloud üzerinde @ecylmz OpenVPN kurdu, uzun süredir kullanıyoruz.  En ufak bir sorun yok, gayet hızlı.  Ben artık üniversitenin firewall ve VPN sorunlarından bıktım.

**Comment by msdundar** [comment]
@sinansahin Ben bu OMÜ-VPN'e bulaştığımdan beri sorun yaşıyorum. Tek sorun yavaşlık değil, ama onu inceleyecek olursan dün akşam 8'den neredeyse sabah 3'e kadar cinnet geçirtecek kadar yavaştı. Kendi VPN'imle Filipinler'e, Jamaika'ya bağlanıyorum daha hızlı, öyle diyeyim sana.

Ama asıl sorunlar bu değil - asıl sorun daha önce belki en az 10 kez VPN'e açtırdığım YÖKSİS ve KPS erişimlerinin sürekli olarak kayboluyor olması. Artık nasıl bir ayar yapısı var, bunlar neden kayboluyor bilemiyorum ama ben artık bunları açtırmaktan bıktım. Dolayısıyla kendi VPN'imize bunları tanımlayalım, rahat edelim.

@huseyin Pazartesi öncelikli olarak bunu halledersen iyi olur.

**Comment by sinansahin** [comment]
FortiClient ile mi bağlanıyorsunuz hocam? Şuan son 24 saat içinde VPN trafiği oluşturduğunuzu göremiyorum. Evet şuan ciddi bir problem gözüküyor. 

![screen shot 2018-08-04 at 07 53 22](https://user-images.githubusercontent.com/9765995/43672671-afa2af34-97bb-11e8-9118-2a54034d34fe.png)

![screen shot 2018-08-04 at 08 01 16](https://user-images.githubusercontent.com/9765995/43672713-9e8c2a9e-97bc-11e8-9f49-d3e1f56b42b3.png)

**Comment by roktas** [comment]
ben omu-vpn'i uzun süredir kullanmıyorum

**Comment by msdundar** [comment]
@sinansahin evet forticlient ile bağlanıyorum
