### ISSUE TITLE
Kayıtlanma iş akışı iyileştirilmeli

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#162]
- Kayıtlanma adımına KPSPublic servisini ekle.
- Servisin erişilemez olması senaryosunu planla.
- User'da kimlik numarası mernis'ten doğrulanıyor mu bilgisini tut.
- Kimlik numarası doğrulanmamışsa bu kimlik numaraları için kimlik/adres bilgisi güncelleme/oluşturma işlemini çalıştırma.
- #143 ve #161'i test et.

**Comment by msdundar** [comment]
@huseyin KPS Public'te T.C. vatandaşı ve yabancı uyruklu için iki farklı sorgu endpoint'i var. Senin API'de bunu tekilleştirebilir miyiz? Yani bir kimlik numarasının T.C. mi (1-8'le başlar), yabancı mı (9'la başlar) veya geçersiz mi olduğunu nokul'da kontrol ettirmek yerine xokul'da kontrol etsek?

Kısacası ben kimlik numarası, ad, soyad, baba adı ve doğum tarihini herhangi bir kontrolden geçirmeden göndereyim - sen bana true veya false döndür. Ne dersin?

**Comment by huseyin** [comment]
@msdundar Bence fena fikir değil abi. Yapabiliriz teknik bir zorluğu yok. Sadece condition yükünü Api servise taşıyacağız. Yukarıdaki koşullar dışında bir istisna var mı peki?
