### ISSUE TITLE
Duty, Employee ve Position validasyonları hatalı çalışıyor

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#166]
**Hatayı ve/veya bug'ı açıklayın:**

[//]: # (Kısa ve net bir şekilde hatanın ne olduğu açıklanmalıdır.)

EmployeeValidator ve DutyValidator ilk yazıldığı ilkel haliyle duruyor ve değişen ihtiyaçları karşılamıyor. Position için ise henüz validator hiç yazılmadı, ancak yazılmalı.

**Olması gereken davranış:**

[//]: # (Kısa ve net bir şekilde hata yerine olması gereken uygulama davranışının ne olması gerektiğini açıklayınız. Örn: X kaydı silindiğinde Z sayfasına yönlendirme yapılmalı.)

Constraint'ler şu şekilde:

- Bir User'ın aktif olan 1 tane Employee kaydı olabilir.
  - Örn. Bir kullanıcı herhangi bir zaman diliminde tek bir Employee kaydı için maaş alabilir. Bir kişi aynı anda aktif olarak hem Doçent, hem Profesör olamaz.
- Bir kullanıcının sonsuz tane pasif Employee kaydı olabilir.
  - Örn: Kullanıcıların geçmişten gelen personellik kayıtlarını da tuttuğumuz için kullanıcıların sonsuz tane pasif Employee kaydı olabilir. Kişi geçmişte Araştırma Görevlisi olarak çalışmış, sonra istifa etmiş, sonra tekrar aynı/farklı bir unvan ile üniversiteye dönmüş olabilir.
- Bir kullanıcının bir birimde 1 tane aktif (bitiş tarihi > bugün) Duty kaydı olabilir.
  - Bir kişi herhangi bir birime aynı zaman diliminde iki kez görevlendirilemez. 
- Bir kullanıcının bir birimde sonsuz tane pasif (bitiş tarihi < bugün) Duty kaydı olabilir.
  - Kişi geçmişte herhangi bir birimlerde defalarca kez görevlendirilmiş olabilir.
- Bir kullanıcının sadece 1 tane temporary olmayan ve aktif olan Duty kaydı olabilir.
  - Temporary olmayan aktif Duty kaydı kişinin kadrolu çalıştığı birimi tarif ettiğinden, kişilerin böyle bir kaydı sadece 1 tane olabilir.
- Bir kullanıcının sonsuz tane temporary olan aktif Duty kaydı olabilir.
  - Bir kullanıcı aynı anda birden çok birime görevlendirilmiş olabilir.
- Bir kullanıcının bir birimde sonsuz tane pasif Duty kaydı olabilir.
  - Bir kişi geçmişte aynı birime defalarca görevlendirilmiş olabilir.
- Bir kullanıcının Duty kaydı oluşturulurken başlangıç tarihi daima bitiş tarihinden önce olmalıdır.
- Bir kişi aktif olan (bitiş tarihi > bugün) iki tane aynı Position'a sahip olamaz.
  - Bir kişi aynı birimde aktif olarak iki kez Dekan olamaz, iki kez Daire Başkanı olamaz vb. Ama aynı anda aktif olarak hem Dekan, hem Dekan Yardımcısı olabilir.
- Bir kullanıcının Position kaydı oluşturulurken başlangıç tarihi daima bitiş tarihinden önce olmalıdır.

Bu constraint'ler ele alınırken update işlemlerine ayrıca dikkat edilmelidir. Örneğin bir kullanıcının pasif olan employee'likleri update yoluyla aktife çekilerek ilk maddenin bypass edilmesi engellenmelidir. Ancak kayıtların diğer attribute'leri hala güncellenebilir. Refactor edilmiş olan `AddressAndIdentityValidator` örnek alınabilir.

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi:**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) emin misiniz?

**Comment by msdundar** [comment]
@dilara Buna bakabilir misin? Anlamadığın veya benim net ifade edemediğim bir yer olursa istediğin kanaldan sorabilirsin, iletişimi koparmayalım.

**Comment by msdundar** [comment]
@dilara WDYT?

**Comment by dilara** [comment]
@msdundar Yeni inceleyebildim, tamamdır.

**Comment by dilara** [comment]
Yukarıdaki kısıtlamalardan cevabını çıkaramadığım durumlar var:

- Kadrolu aktif kaydı olan bir kullanıcı o sırada bir ya da birden çok birime de aktif olarak geçici görevlendirilmiş olabilir mi?

- "Bir kişi aynı birimde aktif olarak iki kez Dekan olamaz, iki kez Daire Başkanı olamaz vb. Kullanıcı aynı anda aktif olarak hem Dekan hem Dekan Yardımcısı olabilir."
Farklı birimlerde aktif olarak Dekan olabilir veya aynı birimde hem Dekan hem Dekan Yardımcısı olabilir mi?

**Comment by roktas** [comment]
@omu/product ping

**Comment by ekural** [comment]
**- Kadrolu aktif kaydı olan bir kullanıcı o sırada bir ya da birden çok birime de aktif olarak geçici görevlendirilmiş olabilir mi?**
-> Evet olabilir. Örnek: Dr. Öğr. Üyesi Recai OKTAŞ    Bilgisayar Müh. Öğretim Üyesi, UZEM Müdür Yardımcısı, BAUM Müdür Yardımcısı.

**- "Bir kişi aynı birimde aktif olarak iki kez Dekan olamaz, iki kez Daire Başkanı olamaz vb. Kullanıcı aynı anda aktif olarak hem Dekan hem Dekan Yardımcısı olabilir."
Farklı birimlerde aktif olarak Dekan olabilir veya aynı birimde hem Dekan hem Dekan Yardımcısı olabilir mi?**
-> Bir kişi aynı birimde aktif olarak iki kez Dekan olamaz. Çünkü bir birimde birden fazla aktif Dekan farklı kişiler içinde olamaz. Her birimin aktif Dekanı tektir. Ancak bir kişi birden fazla birimin Dekanı veya Dekan Yardımcısı olabilir.  Örnek:  [Gümüşhane Üniversitesi](https://bianet.org/bianet/egitim/179550-gumushane-universitesi-nde-rektor-bes-fakultenin-dekan-vekili)

**Comment by roktas** [comment]
@ekural bu vekaleten pozisyon olayını da kayıtlı tutmamızda yarar var, not edelim.

**Comment by abdagli** [comment]
Selamlar herkese

Bu modeller, bizim calismalarimizdan once gerceklenmisti. Yol haritamizda da henuz yok aslinda. Ama bircok yeri etkiledigi icin Pazartesi product ekibi olarak istisare edip yol haritamizda onceliklendirebiliriz. Suanki yapi, gelistirici arkadaslarin insiyatifinde gelistirildi. Dolayisiyla bizim suanda yapacagimiz yorumlar sadece fikir verebilir. Henuz kesinlik teskil etmiyor.

**Comment by roktas** [comment]
@dilara bekleme yok, devam et, sonra gerekirse düzeltirsin
