### ISSUE TITLE
VPN açıkken dokku'ya erişim sorununu çöz

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#179]
Kaybolmaması için iş kaydı açıyorum.

**Comment by roktas** [comment]
![image](https://user-images.githubusercontent.com/47842/43691195-8758f68e-9921-11e8-981c-79ce41189b84.png)

Debian GNOME3, VPN yapılandırma ekranında görülen "tik" sorunu çözdü bende.

**Comment by sinansahin** [comment]
Sorun vpn server ile alakası bulunmamaktadır. Mikrotik FW arkasında bulunan public ip'ye sahip herhangi bir makineden de erişim sağlanamamaktadır. BIDB tarafında yer alan public ip'ye sahip makinelerden ulaşıbiliyor mu kontrolü yapıldı ve ulaşılabilir olduğu görüldü. Mikrotik'e yoğunlaşılması gerekiyor.
