### ISSUE TITLE
Rubocop yapılandırması sonrası oluşan hatalar düzeltilmeli

### ISSUE THREAD

**Issue by isubas** [omu/nokul#1856]
#### Hatanın açıklaması

Rubocop genel yapılandırması değişti ve bundan dolayı bazı offence'ler ortaya çıktı. Bu hataların çözüş

#### Hatayı tekrarlamak için takip edilmesi gereken adımlar

N/A

#### Olması gereken davranış

N/A

#### Hatanın alındığı ortam

N/A

#### Kontrol listesi

- [X] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [X] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

N/A

**Comment by ecylmz** [comment]
Ben de buna bakıyordum. Karşılaştığım hataların listesi şurada:

https://gist.github.com/ecylmz/102e7b4bda4028ab373a089612ba9ba5

Çok fazla aşağıdaki hataya benzeyen hata var.

```
Lint/ConstantResolution: Fully qualify this constant to avoid possibly ambiguous resolution. (not autocorrected)
In file: app/views/manager/stats/articles/index.html.erb:100
```

Bunları düzeltecek miyiz yoksa bu Cop'u `disable` mı edeceğiz? Çok fazla hata üretiyor diye Rubocop'ta `default disabled` ayarlanmış.

@isubas PR'ı açarken erb linter'daki autocorrect'i de kapatabilir miyiz? CI'da hatalar gözden kaçıyor.

https://github.com/omu/nokul/blob/develop/lib/tasks/static_analysis/erb_linter.rake#L6

**Comment by isubas** [comment]
`erb linter` ayarını düzeltirim haklısın orada, `Lint/ConstantResolution` disable edelim. Bu tür kaygıların olabileceği bir uygulama olursa uygulama genelinde açalım.

**Comment by roktas** [comment]
> Lint/ConstantResolution disable edelim. Bu tür kaygıların olabileceği bir uygulama olursa uygulama genelinde açalım.

:+1: default disable olsun, fakat gözetimde tutalım, gelecekte bu Cop'un yakalayabileceği bir bug ile kaşılaşırsak enable ederiz.

**Comment by isubas** [comment]
https://github.com/omu/omu/pull/3 sonuçlandığında çalışmaya devam edilecek.
