### ISSUE TITLE
Rails deprecation uyarısı çözülmeli

### ISSUE THREAD

**Issue by roktas** [omu/nokul#1860]
#### Hatanın açıklaması

Halen aşağıdaki uyarıyı alıyoruz.  Bunu uygun bir vakitte düzeltelim, gelecekte bu uyarı hataya dönüşecek.

![image](https://user-images.githubusercontent.com/47842/86450284-f3cb9f80-bd21-11ea-89a6-0764013d986d.png)

- [X] Ekran görüntüsü ekte

#### Hatayı tekrarlamak için takip edilmesi gereken adımlar

Uygulama loglarına bakılabilir.

#### Olması gereken davranış

Hiç bir uyarı kalmamalı.

#### Hatanın alındığı ortam

- [ ] Masaüstü

[//]: # (Belirtmediğiniz taktirde Ubuntu 18.04/Debian 9 üzerinde güncel Google Chrome kullandığınız varsayılacaktır.)
[//]: # (- OS: [ör. iOS, Windows 10])
[//]: # (- Browser [ör. Chrome, Safari])
[//]: # (- Version [ör. 22])

- [ ] Mobil

[//]: # (- Device: [ör iPhone6])
[//]: # (- OS: [ör. iOS8.1])
[//]: # (- Browser [ör. stock browser, Safari])
[//]: # (- Version [ör. 22])

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [X] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [X] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by huseyin** [comment]
ben bakıyorum

**Comment by huseyin** [comment]
@omu/backend Bunun çözümü çok basit görünmüyor. Ataması üzerimde kalabilir fakat dönem dönem @roktas hocadan görüş alarak ilerlemem gerekecek, fyi
