### ISSUE TITLE
Image processing kütüphanesi seç

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#187]
ActiveStorage + minio ile dosya upload işlemleri tamamdır. Ancak image processing kütüphanesi için bir seçim yapmak gerekiyor.

Rails dökümantasyonu çeşitli image-processing kütüphaneleri için ortak bir helper seti sunan https://github.com/janko-m/image_processing ile ilerleyin diyor, Rails 5.2 için gecikmiş ama Rails 6'da bunu da çıkacaklarını söylüyorlar (https://github.com/rails/rails/pull/32471). Her halükarda nokul'un deploy edildiği ve geliştirildiği makinalarda seçilen image processing kütüphanesi kurulu olması gerek. Adaylar:

- https://github.com/jcupitt/libvips
- https://github.com/ImageMagick/ImageMagick
- https://github.com/aheckmann/gm

**Comment by ecylmz** [comment]
|Name|Contributors|Star|Last Commit|Open Issues| Closed Issues|
|---|---|---|---|---|---|
|libvips|28|2335|19h ago|59|842|
|ImageMagicK|45|1928|8h ago|51|1048|
|gm|69|5154|7m ago|252|319|

**Comment by roktas** [comment]
https://github.com/aheckmann/gm farklı bir şey değil mi?  "GraphicsMagick for node.js", npm paketi ile kuruluyor vs.

Bence burada iki seçenek var:  imagemagick ve libvips.  İlki ben bu dünyaya adım attığım günden beri var neredeyse.  Şişkin, güvensiz, hantal bir şey.  O olmasın da ne olursa olsun diyeceğim ama libvips (alıntılanan issue'da) zaten öne çıkıyor her haliyle.

**Comment by roktas** [comment]
@ecylmz https://github.com/janko-m/image_processing/issues/32

Dokku'da deploy için buildpack gerekecek, ama sanıyorum iyi kötü var zaten.

**Comment by ecylmz** [comment]
libvips için en güncel buildpack: https://github.com/kespry/heroku-buildpack-vips

Alternatif pek yok. Issue altında katkı sağlayıcı "ben yenisini yazıyorum, yakında yayınlıcam" tarzında bir şey demiş. https://github.com/mokolabs/heroku-buildpack-libvips

**Comment by msdundar** [comment]
Burada kararımız Vips değil mi @roktas hocam?

**Comment by roktas** [comment]
Evet kesinlikle Vips.
