### ISSUE TITLE
Aday öğrenci arama formundaki çeviri hataları düzeltilmeli

### ISSUE THREAD

**Issue by begum** [omu/nokul#1904]
#### Hatanın açıklaması

İlk Kayıt / Aday Öğrenciler arama formundaki aşağıdaki çeviri hataları (tr/en) düzeltilmeli.
- Askerlik Durumu Sorunsuz --> Askerlik Durumu
- t('year') --> Yıl

[//]: # (Kısa ve net bir şekilde hatanın ne olduğunu açıkla.  Varsa mutlaka ekran görüntüsü ekle.)

- [x] Ekran görüntüsü ekte

#### Hatayı tekrarlamak için takip edilmesi gereken adımlar

1. https://acme.omu.sh/prospective_students sayfasındaki arama alanı

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

![screenshot-acme omu sh-2020 07 14-13_52_50](https://user-images.githubusercontent.com/338489/87418442-5ce0cc00-c5da-11ea-85bf-ff5375df7648.png)

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by berkeka** [comment]
Bir sorun oluşturmayacaksa bu issue ile ben ilgilenebilirim.

**Comment by roktas** [comment]
@berkeka memnuniyetle
