### ISSUE TITLE
load_missing_constant': uninitialized constant Tenant (NameError)

### ISSUE THREAD

**Issue by ecylmz** [omu/nokul#1907]
#### Hatanın açıklaması

Rails 6.1 ile birlikte `production`'da `load_missing_constant': uninitialized constant Tenant (NameError)` hatası almaya başladık. 
Detaylı hata çıktısı: https://gist.github.com/ecylmz/1759f95509755fcb159e3de12c5c09d2

Bu issue çözülünce https://github.com/omu/nokul/issues/1860 numaralı issue da çözülmüş olacak.

#### Hatayı tekrarlamak için takip edilmesi gereken adımlar

develop dalındayken `$ RAILS_ENV=production rails c`

#### Olması gereken davranış

Production ortamda hata olmamalı ve CI'da olası hatalar tespit edilebilmeli.

#### Hatanın alındığı ortam

Geliştirme ortamı

#### Katkı sağlama

- [x] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [ ] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [ ] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [ ] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [ ] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by msdundar** [comment]
6.0 surumunde olsa gerek `bin/rails zeitwerk:check` diye bir task eklemislerdi, uygulamayi boot etmeden zeitwerk sorun cikartacak mi anlamak icin. Belki CI'a veya static analiz task'lerine eklenebilir.

**Comment by ecylmz** [comment]
@msdundar güzel öneri, bunu teste ekleyeceğim,  `zeitwerk:check` bu problemi yakalamasa da şunu yakalıyor:

```ruby
# app/lib/foo.rb

Bar = Nokul::Tenant
```

```sh
op@4d96db849f03:/app$ rails zeitwerk:check
Hold on, I am eager loading the application.
expected file app/lib/foo.rb to define constant Foo
```

Yani dosya isminin dosya içerisinde constant olarak tanımlı olmasını bekliyor.

**Comment by ecylmz** [comment]
Buraya yazmayı unuttum. Problemi çözdük ama henüz PR çıkmadım.

Özet: `autload_path` içerisindeki constant'ları Rails `config` aşamasında kullanamazsın. Yani biz `app/lib/tenant.rb` içerisindeki `Tenant`'ı `config/environments/production.rb`'de kullanmışız. zeitwerk bunu istemiyor. Bunun yerine gem içerisinden gelen `Nokul::Tenant` kullanarak bu durumu çözdük.

Bir diğer problem olan #1860'daki uyarıların nedeni ise `initialize` aşamasında `app/lib/nokul` altındaki constant'lara erişmeye çalışıyoruz. zeitwerk bunu da istemiyor. İlle de kullanmak istiyorsan `config/application.rb`'e aşağıdaki gibi açıkca ekle diyor.

```ruby
config.before_initialize do
  require 'nokul/sso'
  require 'nokul/name'
  require 'nokul/database_url'
  require 'nokul/version'
end
```

**Comment by roktas** [comment]
Ben de bir ekleme yapayım (dokümantasyona da eklenecek).  Bu hataya yol açan `Tenant = Nokul::Tenant` ve `Support = Nokul::Support` aliasları "conveniency" amacıyla eklenmişti.  Bunların erken aşamada uygulama ilklendirilirken kullanılmaması veya kullanılacaksa bir kaç taklayla düzenlenmesi gerekiyordu.  Bu taklaları atmak yerine uygulamada daima explicit formla yani `Nokul::` ön ekiyle kullanmayı tercih ettik.

Diğer modüller ise uygulamayla ilgili bazı meta bilgileri tutuyor.  Bu bilgileri programatik olarak elde etmek için korunmasında yarar var.

**Comment by roktas** [comment]
@ecylmz `zeitwerk:check`'i mutlaka CI'a ekleyelim
