### ISSUE TITLE
Vagrantfile'ı daima çalışır halde tut

### ISSUE THREAD

**Issue by roktas** [omu/nokul#193]
Şu an rollbar ve yöksis'ten dolayı ilk denemede çalışmıyor.

**Comment by ecylmz** [comment]
Bunun nedeni, config/credentials.yml.enc dosyasının decrypt edilememesi.

decrypt etmek için master key'e ihtiyaç duyulmakta. master key'in ya `config/master.key` dosyasına yazılması ya da  RAILS_MASTER_KEY çevre değişkenine tanımlanması gerekiyor.

**Comment by roktas** [comment]
rollbar ayrı bir sorun gibi ama.

**Comment by msdundar** [comment]
Rollbar access token'ı ekip keepass'ine ekledim

**Comment by roktas** [comment]
Bu iş kaydında aslında farklı bir şeyi hedefledim.  Anlatmaya çalışayım...

Kökteki `Vagrantfile` (Dokku PaaS için yapacağımız opsiyonel ekleme dışında) Rails development ortamını hedefliyor (production veya beta değil).  Şöyle ideal bir hedef: halihazırda public olan bu depoyu klonlayan bir X geliştiricinin uygulamayı ayağa kaldırarak geliştirme yapması için:

1. Bizden temin etmesi gerekecek credentials'lara
2. Bizim üniversiteye özgü production verilerine

ihtiyacı olmaması lazım.  Bu yapılabilir mi veya **her tarafa conditional switch'ler koymadan temiz şekilde** yapılabilir mi bilmiyorum.  İş kaydıyla en azından bu yönde bir girişimde bulunulmasını hedefledim.

Oyunun kurallarını toplu halde tekrar yazayım:

1. Herhangi bir geliştirici depoyu klonladıktan hemen sonra `vagrant up` diyerek büyük ölçüde katkı sağlayacağı bir uygulamaya erişebilmeli
2. Bu yapılırken bizden alması gereken credentials'lara ihtiyacı olmamalı.  Çözüm? Uygulama hazırlanırken bu credentials'lar ephemeral olarak üretilebilir mi?
3. Bize özgü, public depoda ekspoze etmek istemediğimiz ve dolayısıyla bizden talep edilmesi gereken verilere ihtiyacı olmamalı. Çözüm? Hayali bir üniversite için oluşturulmuş zengin bir seed verisi
4. Tüm bu koşulların sağlanabilmesi için kodda yapılması gereken değişiklikler **fazla ve çirkin** olmamalı (ör. her tarafta conditional'lar)

Bunların ne kadarı ne ölçüde yapılabilir, yapılsa bile gelecekte kolayca maintain edilebilir mi onu da bilmiyorum.  Ama böyle bir çalışmanın pek çok yararı olur.

- Projeye yeni bir geliştiricinin katkı sağlaması çok kolaylaşır.
- Nokul bir başka tenant için kolayca paketlenebilir hale gelir.
- Esasında bu bir taşınabilirlik ("portability") sorunu.  Uygulamanın falan filan koşullarda değil neredeyse her yerde (belli kısıtlamalara OK) çalışmasını hedeflemiş oluyoruz.  Deneyimle sabit, taşınabilirlik çabaları codebase kalitesini arttırır.

Bunu teknik tartışmaya açıyorum.  Ama teknik tartışmadan önce somut bazı düzenlemeler de önerilmeli, @isubas o nedenle sana assign ettim.  Her ne düzenleme yapılırsa yapılsın önemli olan yukarıda özetlemeye çalıştığım koşulların gelecekte de sağlanabilmesi.  "Vagrantability" dediğim bu koşulları sınamak için CI'ı kullanamayız maalesef (Docker tabanlı olsa belki).  Ama gerekirse köke eklenecek bir Jenkinsfile ile jenkins.omu.sh'ta bazı testleri aktive edebiliriz.

Düşünceleriniz?

**Comment by msdundar** [comment]
> Bu yapılırken bizden alması gereken credentials'lara ihtiyacı olmamalı. Çözüm? Uygulama hazırlanırken bu credentials'lar ephemeral olarak üretilebilir mi?

Bu iki sebepten dolayı epey zor görünüyor. Birincisi credentials.enc.yml ne olacak sorunsalı, ikincisi ise YOKSIS-KPS gibi şifreler olmadan uygulamanın teorik ve pratik olarak al-çalıştır olamaması. Normalde bu API'lar test ortamları için bir kullanıcı adı ve şifre verse bizde bunu development ve test ortamlarında kullanabilirdik ama böyle bir şey tabii ki yok :)

> Bize özgü, public depoda ekspoze etmek istemediğimiz ve dolayısıyla bizden talep edilmesi gereken verilere ihtiyacı olmamalı. Çözüm? Hayali bir üniversite için oluşturulmuş zengin bir seed verisi.

Bu daha da zor, çünkü seed verisi hazırlamak oldukça zaman alan bir iş. Hazırlanan seed verisinin sürekli maintain edilmesi de gerekiyor. Örneğin bir modelden bir attribute kaldırıldığında, bir şey eklendiğinde veya ilişkiler değişince seed'in de değişmesi gerekiyor.

Burada bir `seed` ve `demo` karmaşası var gibi. Rails'ta `seed` uygulamanın gerçek ortamda ayağa kalkabilmesi için gereken temel verileri üretmeyi temsil ediyor. Örneğin gidip YOKSIS'ten önce referansları çekmesi, ülkeleri-şehirleri oluşturması gibi. Bizim daha çok YOKSIS'siz ve MERNIS'siz durum için bir `demo` veri üretmeye ihtiyacımız var gibi anladım ben. Bunu [faker](https://github.com/stympy/faker) vb. araçlarla yapmak çok daha kolay. Gerçek data gibi davranan, ama gerçek olmayan veriler.

**Comment by roktas** [comment]
Bu haliyle çok epik ve eskimiş bir iş kaydı bu.  Kapatıyorum.

(omu/xokul olgunlaştığında stub servisler açmak gibi bir fikrim var, o zaman tekrar bakacağım)
