### ISSUE TITLE
Improve CircleCI workflows

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#205]
Mevcut CI/CD flow'umuzda bir takım sorunlar var.

## Latest Sürümleri

İmaj olarak `image: circleci/ruby:latest-node-browsers` kullanıyoruz. `latest`, `-l` gibi tag'lere sahip docker imajlarını kullanmak tavsiye edilen bir pratik değil:

> Note: If you do not specify a tag, Docker applies the latest tag. The latest tag refers to the most recent stable release of an image. **However, since this tag may change unexpectedly, it is best practice to add an explicit image tag.**

> Avoid using mutable tags like latest or 1 as the image version in your config.yml file. It is best practice to use precise image versions or digests, like redis:3.2.7 or redis@sha256:95f0c9434f37db0a4f... as shown in the examples. **Mutable tags often lead to unexpected changes in your job environment. CircleCI cannot guarantee that mutable tags will return an up-to-date version of an image. You could specify alpine:latest and actually get a stale cache from a month ago.**

https://circleci.com/docs/2.0/executor-types/#docker-image-best-practices

@huseyin ping, https://github.com/omu/nokul/commit/7034610462e5baf4ad24151cb2c37267e47b714c#diff-1d37e48f9ceff6d8030570cd36286a61

## Parallelism

Mevcut CI configürasyonumuz'da parallelism ayarlanmadığı için sadece paralel tek bir görev çalışıyor. Bu konfigürasyon çok fazla commit akışının olduğu bir repo'da belki avantajlı olabilir (aynı anda dört farklı geliştirici de commit atsa, dördünün de commitleri CI'da aynı anda x1 paralellism ayarında çalışıyor olacak), ancak bizim proje de commit akışı çok yoğun olmadığı için x4 paralellism'i de bir build'e ayırmak daha doğru. Dolayısıyla konfigürasyonda değişiklik lazım:

```
BUNDLE_JOBS: 4 # bundler için
parallelism: 4 # tüm flow için, minitest ve rspec buna otomatik uyum sağlıyor
```

## Source Code Caching

`vendor/bundle`'ı ve `node_modules`'ü cacheliyoruz ancak `checkout` sonrası uygulamayı cachlemiyoruz. Bir build'i tekrar başlatan şey zaten kodun değişmesi gibi düşünürsek bu gerekli gelmeyebilir ancak build'i `restart` yaptığımızda checkout süresinden bizi kurtaracak.

## Orchestrating Workflows

https://circleci.com/docs/2.0/workflows/

Şuan kullandığımız yapı sequential basic flow. Yani kabaca iki tane job çalışıyor, biri build yapıyor, diğeri ise deploy. Build yapan job aslında kendi içerisinde pek çok farklı job'u barındırmasına rağmen (checkout, bundle, yarn install, kalite kontrolü, testler gibi gibi) bir bunları tek job altında çalıştırıyoruz. Dolayısıyla build'in herhangi bir yerinde hata alırsak (örneğin rubocop bir şeye kızarsa) tüm build'i baştan başlatmak gerekiyor, bu da epey zaman kaybı. Sonuç olarak build geçerse ve build `master` dalı üzerinde yapıldıysa deploy başlıyor.

* Mevcut flow (master harici branch)

![screenshot from 2018-08-13 15-29-18](https://user-images.githubusercontent.com/468744/44031767-b49df7a6-9f0d-11e8-8c85-a3e1dac89c73.png)

* Mevcut flow (master branch)

![screenshot from 2018-08-13 15-29-47](https://user-images.githubusercontent.com/468744/44031777-c6146c68-9f0d-11e8-9dcf-7e5d4cf5b380.png)

* Mevcut flow

![](https://circleci.com/docs/assets/img/docs/sequential_workflow.png)

Bu flow yerine hem parallel hem de fan-in-fan-out workflow'ları bizim açımızdan daha uygun görünüyor. Paralellik farklı ruby ve postgres sürümlerine karşı uygulamayı test ederken bizim için çok faydalı. fan-in-fan-out ise günlük geliştirmelerde sequential-flow'un dezavantajlarını ortadan kaldıracak.

* Yeni fan-in-fan-out flow (master harici branch)

![screenshot from 2018-08-13 15-35-05](https://user-images.githubusercontent.com/468744/44032016-837be0c4-9f0e-11e8-96dd-381f41942161.png)

* Yeni fan-in-fan-out-flow

![](https://circleci.com/docs/assets/img/docs/fan_in_out.png)

Yeni flow'un sağladığı avantajlardan biri de paralel olarak task'leri çalıştıracak ve test suite'i bölecek olmamız. Örneğin bizim durum için kod kalitesi ile testler aynı anda çalışıyor, bu task'lerden herhangi biri diğerinin tamamlanmasını beklemiyor. Şuan entegrasyon testlerimiz vs. olmadığı için kazancımız bu flow'un bize sağlayabileceklerinin yanında oldukça ufak bir kazanç. Ancak ilerde test sayımız arttığında ve entegrasyon testleri yazmaya başladığımızda paralel olarak bir build unit testleri çalıştırsın, bir build entegrasyon testlerini, bir build selenium testlerini çalıştırsın gibi senaryoları şak diye bu flow'a ekleyebiliriz.

Paralel flow'u ise farklı sürümlere karşı test etmek için düşündüm. Uygulama farklı ruby ve postgres sürümlerinde nasıl çalışacak önceden görebilmemiz için, ve geriye uyumluluğumuzu test edebilmek için farklı pre-build imajlarda paralel şekilde çalışacak. Flow'un sonuda ise seçtiğimiz mevcut sürüm başarılı ise deploy yap - cutting edge sürümü git başka yere deploy yap vb. bir senaryoya da gidebiliriz.

* Parallel version flow

![screenshot from 2018-08-13 15-53-07](https://user-images.githubusercontent.com/468744/44032829-0555a6d2-9f11-11e8-9706-6eac58c6d72d.png)

## Caching vs Persistent Storage

Bu tarafta epey kıyaslama ve okuma yaptım, burada özetlemek epey uzun olacağından meraklısına isterse anlatırım. Ama bizim durum için şuan en hızlısı hala caching. Workspace'i persist edip job'lar arasında paylaştığımda ilk çalışmada 9, ikinci çalışmada 4 dakika gibi sürelere ulaştım. Cache ile denediğimde süreler ilk çalışmada 4, ikinci çalışmada 1,5 dakika gibiydi. Kimileri ise workspace persist etmenin daha hızlı olduğunu tecrübe etmiş, bunun sebebi ise repolarında devasa bağımlılıklar (mesela 1GB `node_modules` klasörü gibi) olması diye tahmin ediyorum. Bu çapta bir bağımlılığı cache'yip daha sonra cache'i restore etmek demekki klasörü .tar'lamak, diğer workspace'e indirmek, ve daha sonra extract etmekten uzun sürüyormuş. Bizde böyle bir durum olmadığı için şuan cache ile devam edeceğiz. Bu flow'larda best practice ne derseniz - 'hangisi sizin için hızlı çalışıyorsa o' diyorlar.

**Comment by roktas** [comment]
Emeğine sağlık, güzel bir CircleCI briflemesi yapmışsın.
