### ISSUE TITLE
Dokku'da büyük boyutlu dosyalar yüklenirken 413 dönüyor

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#213]
Nokul'da belirli bir boyutun üzerinde resim yüklemeye çalıştığımda (örneğin 6MB'lık bir resim), istek daha nokul'a düşmeden Dokku'dan 413 dönüyor.

Şuan için sorun değil, ancak production'da da dokku kullanacaksak daha user-friendly bir hata sayfası dönmesi doğru olur.

![2018-08-14 14-17-16 ekran goruntusu](https://user-images.githubusercontent.com/468744/44088700-d38977d4-9fcc-11e8-843e-b4627ec652b9.png)

**Comment by roktas** [comment]
Buna baktım.  Nginx özelleştirmesi yapılabilir iki yerde:

- `client_max_body_size 10M;` yapalım.  Bu şekilde en azından maksimum 3 MB sınırını aşan 3 MB- 10 MB arası upload'lar (bk. "gerçek çözünürlüklü büyük bir fotoyu upload etmeye çalışan dummy user" sendromu) Rails tarafından bağlamı daha açık verilen bir hata mesajıyla karşılaşır.

- 10 MB'tan büyük uploadlar için custom 413 sayfası ekleyelim (şu an hepsi 400 şablonu üzerinden yönetiliyor: https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.sigil#L39) Bu sayfada (1) Türkçe ve İngilizce olarak büyük bir dosya upload edilmeye çalışıldığı mesajı görüntülensin (2) uygulamaya geri yönlendirme linki bulunsun.

@ecylmz: Fotolarda 3 MB Rails, 10 MB Nginx sınırı makul.  Ama Nokul'da gelecekte öyle rotalar olabilir ki daha büyük dosyaların yüklenmesi gerekebilir.  Bu rotalara özel olarak `client_max_body_size` "per route" olarak arttırılmalı.  [Nasılı şurada](https://serverfault.com/a/772584)

**Comment by roktas** [comment]
@msdundar Böyle bir çözüm kurguladım, uygun mudur?

**Comment by roktas** [comment]
Bu arada, Nginx default'ı 1 MB olarak görüyorum.  Yani mevcut durumda 1-3 MB arası legal uploadların bile kesilmesi gerekiyor?

**Comment by roktas** [comment]
@ecylmz: Daha önce konuştuğumuz gibi ufaktan Nginx özelleştirmeleri yapmamızın vakti geliyor gibi.  Soru şu: bu özelleştirmeleri nerede tutalım?  Örneğin bu sorun için tüm nginx şablonuyla oynamak yerine /home/dokku/nokul/nginx.conf.d altına bir ayar atmak [yeterli](http://dokku.viewdocs.io/dokku/configuration/nginx/#customizing-via-configuration-files-included-by-the-default-tem)  Bu yolla gideceksek ayarlar depoda olmayacak.  Yok depoda olsun dersek, nginx.conf.sigil gibi bir dosyayı depo köküne eklememiz gerekecek.  Bunu bir düşünelim...
