### ISSUE TITLE
Profil fotosunda yüz tespiti yapılmalı

### ISSUE THREAD

**Issue by sinansh** [omu/nokul#234]
**Bu özellik bir problemle mi ilgili? Lütfen detaylıca açıklayınız:**

[//]: # (Özelliği detaylıca açıklayınız. Eklenmesi/değiştirilmesi iyi olacak olan özelliğin netleştirilmesi, varsa yaşanan sorunların tanımı açıkça yapılmalıdır.)

Kullanıcıların sisteme yükleyecekleri profil fotoğrafını bir çok yerde kullanabiliriz/kullanacağız. Bunun için bu alanın validasyonlarını yeterli düzeye çıkartmamız gerekmektedir. Profil fotoğrafı alanında yüz tespiti yapmalıyız ve fotoğrafı buna göre biçimlendirmeliyiz.

Kullanıcılar çok enteresan fotoğraflar yükleyebiliyor. Tanıtım sayfası, kurum kimliği basımı, matbu çıktılar vb. işlemlerde bu fotoğrafı kullanabileceğimiz için yüz tespitinin gerekli olduğunu düşünüyorum.     

**Sizin çözümünüz:**

[//]: # (Kısa ve net bir şekilde konuyla ilişkili olarak sizin önerileriniz neler, sizin öneriniz kabul edilirse neler olacak, uygulama da neler iyileşecek açıklayınız.)

Aslında bu durum için direk bir çözüm önerim yok. Diğer projelerde [Cloudinary'nin desteği](https://cloudinary.com/documentation/rails_image_manipulation) kullanılmış.

**Diğer alternatifler:**

[//]: # (Konuyla veya sunduğunuz çözümle ilgili düşündüğünüz diğer alternatifler neler? Konuya dahil olarak kişiler neleri göz önünde bulundurmalı?)

https://stackoverflow.com/questions/1399748/how-can-i-detect-faces-using-ruby

https://cloud.google.com/vision/docs/face-tutorial

https://medium.com/statuscode/how-to-detect-image-contents-from-ruby-with-amazon-rekognition-46a962cb040f

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [x] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [x] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [x] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Ek içerik:**

[//]: # (Kaynaklar, dış bağlantılar, ekran görüntüleri, örnek çözümler ve benzeri diğer kaynakları ekleyiniz.)

**Comment by msdundar** [comment]
> Profil fotoğrafı alanında yüz tespiti yapmalıyız ve fotoğrafı buna göre biçimlendirmeliyiz.

İhtiyacı bu kadar net tanımlamadan önce bazı bilgilere ihtiyacımız var. Şöyle ki, kullanıcılar profil fotoğraflarını kendileri mi yükleyecek, kendileri yükleyecekse bu fotoğraflar bir onay mekanizmasından geçecek mi, geçecek ise bunu kim, ne zaman ve nasıl yapacak, yok onaydan geçmeyecekse ne olacak, kayıt ve işe giriş (sistemi kullanan personeller) esnasında bir fotoğraf yüklemesi mi yapılacak - gibi gibi pek çok yanıtsız soru var.

Bu soruların ve olası tüm cevaplarının artısını/eksisini @omu/product ekibinin çalışması lazım. Bu çalışma gerçekleştiğinde ancak o zaman ihtiyacın gerçekten yüz tanıma mı olduğu netleşecek.

Ancak, fotoğrafı ister kullanıcı kendi yüklesin, isterse kullanıcı adına bir personel yüklesin, her halükarda bir fotoğraf kırpma çözümüne ihtiyacımız olduğu kesin.
