### ISSUE TITLE
Kurul ve komisyonlar modellenmeli

### ISSUE THREAD

**Issue by ecmelkytz** [omu/nokul#236]
**1. Senaryo:** Kurul ve komisyonlar birim olarak tutulacak.
Kaysis’de kurullar şu mekanizma ile tutuluyor:

- Üniversite
  - Kurullar/Komisyonlar/Konseyler
    - Akademik Değerlendirme ve Kalite Geliştirme Kurulu
    - Akademik Teşvik Düzenleme, Denetleme ve İtiraz Komisyonu
    - Hayvan Deneyleri Yerel Etik Kurulu
    - İş Etik Kurulu
    - Senato
    - Sosyal ve Beşeri Bilimler Araştırmaları Etik Kurulu
    - Üniversite Disiplin Kurulu
    - Üniversite Yönetim Kurulu
    - Yayın Komisyonu
  - Mühendislik Fakültesi Dekanlığı
    - Kurullar/Komisyonlar/Konseyler
      - Fakülte Disiplin Kurulu
      - Fakülte Kurulu
      - Fakülte Yönetim Kurulu
  - Fen Bilimleri Enstitüsü Müdürlüğü
    - Kurullar/Komisyonlar/Konseyler
      - Enstitü Disiplin Kurulu
      - Enstitü Kurulu
      - Enstitü Yönetim Kurulu

**Not:** Birim olarak oluşturduğumuz zaman kurullar için **yoksis_id** olmayacak.

**2. Senaryo:** Kurullar bir modelde tutulur ve ilgili birimler ile bağlantı sağlanır.

Senaryo ile ilgili ilkel bir görsel:
![committee](https://user-images.githubusercontent.com/937358/44707551-72fc4680-aaad-11e8-9394-3d7b89955639.jpg)

**Comment by msdundar** [comment]
@ecmelkytz Peki sence hangi senaryo ile gitmeliyiz?

Bence bu soruya yanıt vermeden önce bir personelin kurul/komisyon ile ilişkisini aydınlatmalısın, en kritik yer bura gibi geldi bana.

Biz birim-personel ilişkisini nasıl tanımlamıştık? Örneğin Ecmel için önce bir personel kaydı oluşturulur, bu kayıt Ecmel'in maaş alışıyla yani çalışanlığı ile alakalı olan kayıttır. Daha sonra bu çalışan kadrolu olduğu birim haricinde BAUM gibi birimlere bir görevlendirme (Duty) oluşturularak görevlendirilebilir. Bir kişinin birden fazla görevlendirmesi olabilir. Kişiler görevlendirmeli oldukları birimde çeşitli görevlerde yer alabilir (Position).

Kurul/komisyon bir birimdir dersek, kişileri X birimi altında tanımlanmış kurul/komisyonlarda görevlendirmek için, önce o kişiyi X birimine görevlendirmemiz gerekiyor mevcut yapıda. Oradaki varsayım, bir kişi herhangi resmi bir bağı olmayan bir birimde görev alamaz idi. Görev alabilmesi için adı üstünde 'görevlendirme' yapılması gerekir. Ancak buna uymayan örnekler var. Örneğin ben BAUM personeli değilim, ancak BAUM'a bağlı bir komisyona üyeyim.

Özetle kurul/komisyon bir birimdir dersek - kişilere kurullarda yer vermek için önce o kurulun ait olduğu birime görevlendirme yapmalıyız. Veya kişi-görev-yetki varsayımımızı; "bir kişi herhangi bir resmi bağı olmayan bir birimde çeşitli görevler alabilir" şeklinde güncellemeliyiz. İlk seçenek iş görür gibi geliyor bana, ama gözden kaçırdığımız durumlar olmamalı.

İkinci senaryoda merak ettiğim şey ise 1) Kişilerin kurul/komisyon üyeliklerini nerede ve nasıl tanımlayacaksın? 2) Karar (sanırım `meeting`'de alınacak) dediğimiz şey bu ilişki ağının neresinde olacak? 3) Bir `karar` bir `kurul/komisyon` dışında başka herhangi bir kişi/birim tarafından alınabilen bir şey mi - eğer öyleyse kararlar modeli bu diğer olası karar alıcı mekanizmalara ait olacak modeller ile paylaşılabilir durumda olacak mı?

Hem düşünüp hem yazdım, kafa karıştırdıysa bunu sakince bi tekrar görüşürüz.

**Comment by abdagli** [comment]
> Özetle kurul/komisyon bir birimdir dersek - kişilere kurullarda yer vermek için önce o kurulun ait olduğu birime görevlendirme yapmalıyız. Veya kişi-görev-yetki varsayımımızı; "bir kişi herhangi bir resmi bağı olmayan bir birimde çeşitli görevler alabilir" şeklinde güncellemeliyiz. İlk seçenek iş görür gibi geliyor bana, ama gözden kaçırdığımız durumlar olmamalı.

Ben duty modelini ilk gördüğümde hatırlarsanız positions mantığını tam anlayamamıştım. Çünkü bizim incelediğimiz örneklerde bir kişi farklı farklı birimlerde farklı farklı görevlendirmelerde bulunabiliyor. Ancak sonra @msdundar ile görüştüğümde bunun daha resmi bir kayıt olduğunu, direk rektörün kaleminden çıkan görevlendirme olduğunu belirtmişti. Ancak öyle durumlar varki bir kişi farklı farklı birimlerde farklı pozisyonlarda olabiliyor ama aslında duty'leri tek bir yerde. Çünkü kadroları orada. Bu yüzden belki de positions ile duty'i ayırmak da gerekebilir. Duty çok resmi bir kayıt ama positions biraz daha esnek gibi geldi bana.

**Comment by msdundar** [comment]
Normalde görevlendirme dediğim gibi resmi bir şey. UZEM/BAUM'da ki tüm personel resmi bir görevlendirme ile orada bulunuyor. Ancak şimdi düşündüm de, kurul/komisyon görevlendirmeleri de böyle. Bir kişinin kurul/komisyon görevi de yine resmi yazıyla geliyor. Yani her halükarda ortada resmi bir durum var. Sadece kurul/komisyon üyeliği bir birime görevlendirme değil.

> Ancak öyle durumlar varki bir kişi farklı farklı birimlerde farklı pozisyonlarda olabiliyor ama aslında duty'leri tek bir yerde. Çünkü kadroları orada.

Burada yine işler karışmış, kendimden örnekle şöyle toparlayayım. Benim kadrom Eğitim Bilimleri Enstitüsü'nde ve ünvanım Araştırma Görevlisi (Employee). Herkesin kadrosunun bulunduğu ve maaş alışıyla ilişkili olan böyle bir kadrosu var. Ancak rektör beni Uzaktan Eğitim Merkezi'ne 1 yıllık geçici görevlendirme ile görevlendirdi (Duty). Aynı anda birden çok yere de görevlendirebilirdi, yani hem UZEM, hem BAUM'a gibi. Kadrolu veya görevlendirmeli bulunduğum yerlerde müdür yardımcısı, teknik danışman, komisyon üyesi vb. çeşitli görevler (Position) alabiliyorum. Ama almak zorunda değilim. Her görevlendirmesi olanın bir Position'ı olmak zorunda değil. Benzer şekilde bir birimde görevlendirmesi olan bir kişinin birden çok Position'ı da olabilir. Örneğin Recai hoca, Duty kaydı UZEM'de, müdür yardımcısı ve yönetim kurulu üyesi olarak 2 ayrı Position'ı var.

**Comment by msdundar** [comment]
Rakamsal olarak ifade etmek gerekirse:

Bir kişi üniversitede personelse = 1 tane aktif employee kaydı olmak zorunda. Geçmişte istifa etmiş geri dönmüştür, birimi veya unvanı değişmiştir gibi durumlarda >= 1 tane de pasif Employee kaydı olabilir.

Aktif bir personelin >= 0 tane Duty kaydı olabilir. Yani ya hiç bir yere görevlendirilmemiştir, ya da onlarca yerde görevli olabilir.

Aktif bir personelin - her bir aktif Duty kaydı için - >= 0 tane Position kaydı olabilir. Örnek vereyim Cezmi'nin biri UZEM'de, diğeri BAUM'da iki Duty kaydı olsun. Cezmi'nin UZEM'de hem müdürlük, hem de yönetim kurulu üyeliği olsun - yani 2 tane Position'ı. Ancak Cezmi'nin BAUM'da 0 tane Position kaydı olabilir, yani orada idari bir görevi olmayabilir.

**Comment by msdundar** [comment]
Rakamsal olarak ifade etmek gerekirse:

- Bir kişi üniversitede personelse = 1 tane aktif employee kaydı olmak zorunda.

(Geçmişte istifa etmiş geri dönmüştür, birimi veya unvanı değişmiştir gibi durumlarda ise >= 1 tane de pasif Employee kaydı olabilir.)

- Aktif bir personelin >= 0 tane Duty kaydı olabilir.

(Yani ya hiç bir yere görevlendirilmemiştir, ya da sonsuz yerde görevli olabilir.)

- Aktif bir personelin - her bir aktif Duty kaydı için - >= 0 tane Position kaydı olabilir.

(Cezmi'nin biri UZEM'de, diğeri BAUM'da iki Duty kaydı olsun. Cezmi'nin UZEM'de hem müdürlük, hem de yönetim kurulu üyeliği olsun - yani 2 tane Position'ı. Ancak Cezmi'nin BAUM'da 0 tane Position kaydı olabilir, yani orada idari bir görevi olmayabilir.)

**Comment by abdagli** [comment]
Anladım. Bu durumda her türlü pozisyon görevlendirmesi resmi olacak. Bu çok güzel. Peki pozisyonlarda deadline olacak mı? Bir de bu atamaların yetkilendirmekte bir ilişkisi kurulabilir mi ileride?

**Comment by msdundar** [comment]
> Peki pozisyonlarda deadline olacak mı?

Bunu @sinansh ekledi, pozisyon oluştururken de başlangıç ve bitiş tarihi girebiliyoruz artık.

> Bir de bu atamaların yetkilendirmekte bir ilişkisi kurulabilir mi ileride?

İnş. inş. :)

**Comment by abdagli** [comment]
Yetki meselesini şu yüzden açtım; her yetki resmi pozisyonla kazanılmayabilir. Örneğin bizim birimimizde amirimiz sen şu işle ilgilen diyebilir ve bu işin sistemde yapması gereken birkaç işi olabilir.

**Comment by ecmelkytz** [comment]
> @ecmelkytz Peki sence hangi senaryo ile gitmeliyiz?

Bu konu hakkında ilk düşünmeye başladığım zamanlar kurulları tamamen ayrı bir yapı olarak düşünüp (2. Senaryo), şimdilerde konuştuğumuz **duty** mevzusunu da sadece kurul üyeleri diye bir modelde tutup işi halletmeyi planlıyordum. Ancak kurul/komisyon görevi atamalarında dediğin gibi resmi bir durum var ise  ve duty ile de bu işi hallediyorken, bu yaklaşım sistemi gereksiz karmaşıklaştırmaktan başka bir işe yaramayacak.

> Özetle kurul/komisyon bir birimdir dersek - kişilere kurullarda yer vermek için önce o kurulun ait olduğu birime görevlendirme yapmalıyız

Neden ait olduğu birime görevlendirme vereceğiz direk kurulda görevlendirme vermek daha doğru değil mi? Çünkü görevlendirildiğimiz birime ait pozisyonlarımız olacak.

> Karar (sanırım meeting'de alınacak) dediğimiz şey bu ilişki ağının neresinde olacak? 

**Meeting**  kurulda yapılacak toplantıları ele alıyor, kararlar toplantılara ait başka bir modelde tutulacak. İş kaydı gövdesinde ilkel olarak sadece kurulların konumlandırılmasını ele almıştım ondan kararlar vs. mevcut değil.

> Bir karar bir kurul/komisyon dışında başka herhangi bir kişi/birim tarafından alınabilen bir şey mi

İlk önce toplantıda görüşülecek gündemler belirleniyor. Toplantı sonrasında gündemler karara bağlanıyor  bazıları da sonraki toplantıda görüşülmek üzere askıya alınıyor. Kurul/komisyon üyeleri dışında başka herhangi bir kişi veya birim karar veremez. Yanlış biliyorsam @ekural düzeltecektir.

İlk senaryoda ise ister istemez yöksis’in birim yapısına müdahale etmiş olacağız  ve yoksis_id boş geçilebilen bir attribute olmak zorunda kalacak. Birimlerle ilgili *"mevcut yapıyı bozmayacağız"* tarzında radikal bir kararımız yok ise bir şekilde halledilebilir tabi ancak manuel olarak birim oluştururken yoksis_id girmesi gerektiği halde kişinin bu alanı boş geçmesini engelleyemeyeceğiz.

**Comment by roktas** [comment]
> Neden ait olduğu birime görevlendirme vereceğiz direk kurulda görevlendirme vermek daha doğru değil mi? Çünkü görevlendirildiğimiz birime ait pozisyonlarımız olacak.

"kurul/komisyon bir birimdir dersek"  önce birime görevlendirme gerekir diyor @msdundar, koşullu ifade.  kurul/komisyonu birim değilse sorun yok.

**Comment by abdagli** [comment]
Kurul Komisyon bir birimse üst birime görevlendirme yapmaya gerek yok @ecmelkytz nin dediği gibi. Sonuçta kurul komisyon bir başka birimin alt birimi. Böyle düşünürsek bizim hepimiz rektörlükte görevlendirilmemiz gerekir ama aslında var olduğumuz birimde görevlendirilmeliyiz.

Ancak kurul komisyonu birim olarak düşünmezsek o zaman farklı düşünülebilir tabini.

**Comment by roktas** [comment]
@msdundar:
> Örneğin ben BAUM personeli değilim, ancak BAUM'a bağlı bir komisyona üyeyim.

BAUM komisyonu neredeyse tamamen bu tür üyelerden oluşuyor.  Bilgisayar bölümünden Sedat ve Gökhan hoca mesela, BAUM personeli değil.  Benzer durum Pedagojik formasyon komisyonunda da var.  Misal Hüsnü hoca komisyon başkanı ama UZEM'de değil gibi.  Böyle başka pek çok örnek çıkacağına eminim.

**Comment by roktas** [comment]
>  Ama hissiyatım senin de dediğin gibi resmiyeti olmayan yetkilendirme durumları olabileceği yönünde.

Resmiyeti olmayan kurul/komisyonları yönetmek zorunda mıyız?  Resmiyet yoksa şayet, isimlendirme güçlüğü çektiğimizden kurul/komisyon dediğimiz ama bizim modellemeye çalıştığımız resmi kurum/komisyondan farklı bir şey vardır ortada.  Bununla ilgilenmek zorunda mıyız?

**Comment by roktas** [comment]
Kişisel görüşüm kurul/komisyonun **bizdeki programatik anlamıyla** unit olmadığı yönünde.  Ha şu olabilir ama `Unitable` (bir tür concern), position vs ortak tarafıyla.  Modeldeki ortaklıklara bu bakış açısıyla (unit değil unitable) baksanız?  Unitable'ı uydurdum, adı başla bir şey olabilir.  interface tabanlı OOP kavramlarından hareketle öyle dedim (-able ekledim).

**Comment by msdundar** [comment]
Dün yazdığımda hatalı bir durum var.

Eğer kurul/komisyon bir Unit olacaksa, kişileri direk bu kurul/komisyona atayabiliriz. Bu kurul/komisyon biriminde idari görevi varsa onu da ayrıca Position olarak atayabiliriz. Yani kurul/komisyonun üst birimleri ile işimiz yok.

Benim fikrim şimdilik işleri basit tutmak adına kurul/komisyonu birim gibi tutmak, siz ne dersiniz?

**Comment by roktas** [comment]
`yoksis_id` yerine `unit_code` veya basitçe `code` kullanılabilir.  Başka önerilere de açığım.  Yeter ki (bir parça yanıltıcı olan) `yoksis_id` için bir çözüm bulalım (alias yapılabilir).

**Comment by msdundar** [comment]
@ecmelkytz Bu tartışma sonucunda neye karar kıldık?

**Comment by roktas** [comment]
![image](https://user-images.githubusercontent.com/47842/45020533-ecf57800-b037-11e8-924a-53fb046aae22.png)

**Comment by roktas** [comment]
@sinansh bu bilgileri verdi.  KAYSİS numarası diye bir şey yok, herşey DETSİS nolar üzerinden yürüyor.  Yukarıdaki ekran görüntüsünde `81181891` gibi 8 haneli sayılar sanırım.

**Comment by roktas** [comment]
Üniversitenin birim ağacından bir kesit (sondaki kurul/komisyonlara dikkat).  Kurul/komisyon ağaç yapısında her bir birimde olabilir.

![image](https://user-images.githubusercontent.com/47842/45020674-48c00100-b038-11e8-845e-decd5ce36b6f.png)

**Comment by msdundar** [comment]
@ecmelkytz Sonuç olarak neye karar verildi? :)

**Comment by ecmelkytz** [comment]
@msdundar kurulları detsis_id'leriyle birlikte birim olarak oluşturacağım.
Diğer sıkıntılardan biri resmi geçerliliği olan bazı komisyonların detsis_id'ye sahip olmaması. Bu birimlerin idari birim olduğunu belirtmek için ya detsis_id uyduracağım ya da bütün birimler için unit_code mekanizmasını devreye sokacağım. Doğru pratiği yakalamak için ihtiyaç olursa iki farklı branchda farklı senaryoları deneyebilirim.

**Comment by msdundar** [comment]
Sesli düşünüyorum, `detsis_id`'si olmayan birimlerin şimdilik hem `yoksis_id`'leri, hem de `detsis_id`'leri nil geçse ne olur? Bunları LDAP tarafında temsil etmedikçe sorun olmaz sanki @roktas hocam? Sonra bunlara ne yapacağımıza karar veririz. Gerçekten yasal kurullar ise detsis'e kayıt etmelerini isteyebiliriz veya başka bir yol düşünürüz.

**Comment by roktas** [comment]
Bu bahiste kritik karar kurul/komiteye birim olarak muamele etmekti. LDAP açısından mevcut durum şimdilik yeterli. Uygundur.

**Comment by msdundar** [comment]
@ecmelkytz Bu ve #260'da ne durumdayız? Ne zamana biter, adını koyalım mı bu işlerin? :)

**Comment by ecmelkytz** [comment]
@msdundar rake görevi yazıyorum bugün/yarın bitmiş olur. iki iş aynı anda bitmiş olacak.
