### ISSUE TITLE
Unit modeline birim kısaltma kodu eklenmeli

### ISSUE THREAD

**Issue by isubas** [omu/nokul#257]
**Bu özellik bir problemle mi ilgili? Lütfen detaylıca açıklayınız:**

Ders tanımlanırken, ders kodunun sistem tarafından otomatik olarak üretilmesi isteniyor. Ders kodları üretilirken, kodların dersin açıldığı birimi referans olarak göstermesi gerekiyor. Ders kodları  **[BirimKodu][Sayısal Kod]** şeklinde bir pattern ile oluşturulması gerekiyor ve UBS sisteminde halihazırda böyle bir yöntem kullanılıyor. Bu durumdan dolayı Unit modelinde kısaltma kodu ilgili bir çözümün geliştirilmesi gerekli.

Kısaltma kodlarına örnek:
  
- Mühendislik Fakültesi: **MUH** veya **MF**
- Eğitim Fakültesi: *EF*
- Bilgisayar Mühendisliği Bölümü: **BIL**
- Fen Bilgisi Öğretmenliği:  **FBO**

**Sizin çözümünüz:**

Unit modeline `code` veya `abbreviation` adında bir alan eklenir. Birimler oluşturulurken de geliştirilecek kısaltma kodu ürütme mantığına göre kod set edilir. Burada genellikle birim isimlerinin baş harflerinden oluşan bir kısaltma kullanabiliriz fakat aynı isimli birimler için bir çözüm geliştirilmelidir.

**Diğer alternatifler:**

- Ders kodlarında birim kodlarını kullanmamak.

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [x] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [x] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [x] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Ek içerik:**

[//]: # (Kaynaklar, dış bağlantılar, ekran görüntüleri, örnek çözümler ve benzeri diğer kaynakları ekleyiniz.)

**Comment by abdagli** [comment]
Selamlar @isubas 

Alternatif onerin, var olan duzeni tamamen bozacagindan dolayi gundemimizde olmayacak malesef. Birim kodlarinin otomatik uretilmesi yerine belki hint belirleyip, kullanicinin max 3 min 2 karakterli bir kod girmesini de isteyebiliriz.

**Comment by msdundar** [comment]
@omu/product Nihai karara göre belirlenen geliştirmeyi yapabilirim. Unit tarafını ben kodladığım için işi kendime assign ettim, ama gönüllüsü varsa alıp kendine assign edebilir tabii, memnun olurum :)

**Comment by roktas** [comment]
Kısaltmalar kendi başına bir "ürün özelliği".  Sadece dersler değil kısaltma oluşturulması gereken başka şeyler de var.  PO arkadaşlar: bu konuda ürün tarif eden dokümanlarla (yoksa şimdiden yazılmaya başlanabilir) iş kaydını zenginleştirirse memnun olurum.

**Comment by roktas** [comment]
Sorunu sadece ders kodları olarak ortaya koyarsak bu iş kaydının "Unit modeline birim kısaltma kodu eklenmeli" başlığının değiştirilmesi gerekir.  Yaklaşık 1000 küsur yöksis birimi var.  Bunlardan ders kodu oluşturmaya konu olan birimlerin sayısı ise (şimdi kabaca baktım) 200 civarı.  1000 civarı birime kısaltma oluşturmakla (ki bence olabilir) 200'e oluşturmak `XXX` kısaltma uzayının kullanılması açısından çok farkeder.  Önce buna karar verilmeli. @omu/product: sadece derslere değil tüm birimlere kısaltma verilmeli mi?  (ör. `MUH` kısaltması hiç bir ders kodunda kullanılmayacak, ama gayet anlamlı) Use case'ler: evraklarda kısaltma, pek çok birime özgü servisin tutarlı isimlendirilmesi için bir fırsat vs.

**Comment by ekural** [comment]
Ders kodlarının 3 karakter ve ya 4 karakter olması gibi bir sınır yok. Genel kullanım 3 karakter şeklinde ancak 4 karakter olduğu yerlerde var. 2012 öncesi ders kodları 8 karakter civarıymış ancak gerekli durumlarda gözle takibi zorlaştırdığı ve evraklarda kullanımı pek hoş olmadığı için bu yapıya geçmişler. Ders kodları ile varolan düzeni değiştirmek demek değişecek her bir ders için bölüm kurulu kararı - fakülte kurul kararı - eğitim komisyonu kararı - senato kararı alınması gerekliliğini doğurmaktadır. @roktas hocamın verdiği sayıyı göz önüne alırsak kodu değişmesi söz konusu birimler 200 olduğunda her bölümde 20 dersin kodunu değiştirsek dahi 4000 ders için bu sürecin yaşanması gerekir.

**Comment by roktas** [comment]
@omu/product Hazır depoda çalışmaya başladık, bu konuda hemen önden bir çalışma yapalım mı?

- Hali hazırda kullanılan tüm bölüm kodlarını (ders kodlarının bölüm kısmı) ilgili bölümlerle birlikte listelensin
- (Sonraki aşama) Mevcut kodları korumak koşuluyla kodlamayı tüm yöksis birimlerine genişletme girişiminde bulunalım
- İdari birimler (detsis) için ne yapmak gerekir, düşünelim?

@abdagli Belirlediğin düzende yeni bir UC issue açıp bu iş kaydını oraya bağlayabilirsin.  Yukarıda anlattığım çalışma da bir dokümanda yerini alır.

**Comment by abdagli** [comment]
@roktas hocam suanda oncelikli islerimiz var. Bu kod meselesi, bize gore bir UC degil, UC altindaki bir dev issue. UC'nin icerisinde biz standarti belirtiriz zaten. UC'leri bu tarafa aktaralim, o sirada onlar altinda tartisalim.

**Comment by roktas** [comment]
@abdagli Uygundur.

**Comment by msdundar** [comment]
#284'te ele alındı.
