### ISSUE TITLE
İdari birimler sisteme eklenmeli

### ISSUE THREAD

**Issue by ecmelkytz** [omu/nokul#260]
**Bu özellik bir problemle mi ilgili? Lütfen detaylıca açıklayınız:**

Personel görevlendirmelerinin doğru bir şekilde yapılabilmesi için idari birimlerin sistemde olması gerekmektedir.

[//]: # (Özelliği detaylıca açıklayınız. Eklenmesi/değiştirilmesi iyi olacak olan özelliğin netleştirilmesi, varsa yaşanan sorunların tanımı açıkça yapılmalıdır.)

**Sizin çözümünüz:**

#236 iş kaydında kurul/komisyonların kaysis'den çekilip sisteme entegre edilebilmesi için bir .yml dosyası hazırlanıyor. Sadece kurul/komisyonların değil tüm idari birimlerin tek seferde çekilmesinin daha iyi olacağını düşünüyorum.

[//]: # (Kısa ve net bir şekilde konuyla ilişkili olarak sizin önerileriniz neler, sizin öneriniz kabul edilirse neler olacak, uygulama da neler iyileşecek açıklayınız.)

**Diğer alternatifler:**

[//]: # (Konuyla veya sunduğunuz çözümle ilgili düşündüğünüz diğer alternatifler neler? Konuya dahil olarak kişiler neleri göz önünde bulundurmalı?)

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [x] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Ek içerik:**

[//]: # (Kaynaklar, dış bağlantılar, ekran görüntüleri, örnek çözümler ve benzeri diğer kaynakları ekleyiniz.)

**Comment by ecmelkytz** [comment]
İdari birimler sisteme entegre edildiği zaman birim hiyerarşisi şu şekilde olması öngörülüyor: 
(Görselde kırmızı ile gösterilenler kaysis'den eklenecek olan idari birimleri temsil etmektedir)

![idari_birimler](https://user-images.githubusercontent.com/937358/45153909-56af8680-b1de-11e8-8dea-f3b5318b5c5b.jpg)

**Comment by ecmelkytz** [comment]
OMU organizasyon şemasında daire başkanlıkları genel sekreterliğin altında konumlandırılmış. 
bkz: http://www.omu.edu.tr/tr/organizasyon-semasi-yeni
Detsis'de ise genel sekreterlik ve daire başkanlıkları direk rektörlüğe bağlı. @ekural, @abdagli hiyerarşi itibariyle hangi yapı doğru?

**Comment by ecmelkytz** [comment]
İdari birimler dosyasını nihayete erdirmek adına daire başkanlıklarını ve genel sekreterliği rektörlüğe bağladım, fyi.

**Comment by msdundar** [comment]
@ecmelkytz Bence uygundur :+1:  Bu gibi durumlardan bloke olmayalım, yanlış yere konulmuşsa doğru yere alınır zaten sonra.
