### ISSUE TITLE
Görevlendirme güncelleme sırasında bilinmeyen hata

### ISSUE THREAD

**Issue by wemrekurt** [omu/nokul#261]
**Hatayı ve/veya bug'ı açıklayın:**

Kullanıcı görevlendirme güncelleme sırasında eğer görev bitiş tarihi bugünden daha ileri bir tarih ise `Lütfen aşağıdaki sorunları gözden geçirin:` şeklinde bir hata meydana geliyor, güncelleme işlemi de gerçekleşmiyor. Bu metin dışında herhangi bir uyarı da görünmüyor. Console'dan baktığımda ise hata mesajını şu şekilde görüyorum: `Bu personelin zaten aktif ve kadrolu bir görevi var! Yeni kayıt girmek yerine aktif kaydı düzenleyin veya öncelikle aktif kaydı pasifleştirin.` #166 'da bu konu muhtemelen ele alınıyor. Mevcut validasyon yeni kayıt ekleme için çalışması gerekirken güncelleme için de çalışıyor gibi görünüyor.

**Hatayı tekrarlama için takip edilmesi gereken adımlar:**

1. Kullanıcılar Sayfasında herhangi bir kullanıcıyı görüntüle
2. Personel işlemleri sekmesinden görevlendirmesinin bitiş tarihini ileri bir tarih olarak güncelle
3. Yine Personel İşlemleri sekmesinden görevlendirmesinin birimini güncelle.

**Olması gereken davranış:**
Eğer bu bir hata değil, olmaması gereken bir durum ise en azından hata mesajının görünmesi gerekirken boş görünüyor. Diğer durumda zaten birimin güncellenebilmesi gerekiyor. 

**Ekran görüntüleri:**

![ss1](https://user-images.githubusercontent.com/10333281/45144885-09281f00-b1c8-11e8-92cb-50474720f734.png)
![ss2](https://user-images.githubusercontent.com/10333281/45144872-03cad480-b1c8-11e8-8fa8-ace0f96f3092.png)

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi:**

* [x] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [x] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [ ] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) emin misiniz?

**Ek içerik:**

[//]: # (Kaynaklar, dış bağlantılar, ekran görüntüleri, örnek çözümler ve benzeri diğer kaynakları ekleyiniz.)

**Comment by msdundar** [comment]
@dilara senin baktığın custom validasyonlarla ilişkili.
