### ISSUE TITLE
Duty, Position ve Employee controller testleri eksik

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#279]
**Hatayı ve/veya bug'ı açıklayın:**

[//]: # (Kısa ve net bir şekilde hatanın ne olduğu açıklanmalıdır.)

DutiesController, PositionsController ve EmployeesController isimli controller'ların testleri eksik.

**Olması gereken davranış:**

[//]: # (Kısa ve net bir şekilde hata yerine olması gereken uygulama davranışının ne olması gerektiğini açıklayınız. Örn: X kaydı silindiğinde Z sayfasına yönlendirme yapılmalı.)

`test/controller/accounts` altında bu üç controller için testler bulunmalı. [Test coverage](https://github.com/omu/nokul/blob/develop/docs/development/test-coverage.md) kontrol edilerek controller'ların test edildiği teyit edilmeli.

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi:**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) emin misiniz?

**Comment by msdundar** [comment]
@dilara buna bakabildin mi?

**Comment by dilara** [comment]
@msdundar bakıyorum.
