### ISSUE TITLE
Pagy için DRY düzenlemesi yapılmalı

### ISSUE THREAD

**Issue by isubas** [omu/nokul#297]
**Bu özellik bir problemle mi ilgili? Lütfen detaylıca açıklayınız:**

Controller'ın genelinde kullanılan sayfalandırma ve search işlemleri için geliştirilen kod parçaları kendileri tekrar eden bir yapıda olduğundan dolayı iyileştirme yapılması gereklidir.

**Sizin çözümünüz:**

@roktas'ın https://github.com/omu/nokul/pull/283#discussion_r217896614 'deki belirtiği yapı.

**Katkı sağlama:**

* [X] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Comment by msdundar** [comment]
OK is sende olsun, ama acelesi yok bunun, oncelik her zaman product ekibinden gelenler, ornegin senin icin Course tarafi.
