### ISSUE TITLE
Akademik takvim ile kurul kararları ilişkilendirilmeli

### ISSUE THREAD

**Issue by ecmelkytz** [omu/nokul#505]
**Bu özellik bir problemle mi ilgili? Lütfen detaylıca açıklayınız:**

Kurul kararları geliştirilmeden önce akademik takvimde, kurul karar tarihini `senate_decision_date` alanında, kurul karar numarasını `senate_decision_no` alanında tutuyorduk. Bunların yerine akademik takvimin kurul kararları(`CommitteeDecision`) modeli ile ilişkilendirilmesi sağlanmalı.

[//]: # (Özelliği detaylıca açıklayınız. Eklenmesi/değiştirilmesi iyi olacak olan özelliğin netleştirilmesi, varsa yaşanan sorunların tanımı açıkça yapılmalıdır.)

**Sizin çözümünüz:**
Bir akademik takvim için birden fazla kurul kararı geçerli olabiliyor. Bundan dolayı `has_many` ilişkisi kurulmalı.

[//]: # (Kısa ve net bir şekilde konuyla ilişkili olarak sizin önerileriniz neler, sizin öneriniz kabul edilirse neler olacak, uygulama da neler iyileşecek açıklayınız.)

**Diğer alternatifler:**

[//]: # (Konuyla veya sunduğunuz çözümle ilgili düşündüğünüz diğer alternatifler neler? Konuya dahil olarak kişiler neleri göz önünde bulundurmalı?)

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [x] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [x] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [x] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [x] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Comment by abdagli** [comment]
@dilara @ekural ve @begum ile birlikte konustuk konuyu. Tarih olarak ilgili kararin alindigi toplantinin tarihi kullanilacak. Akademik takvim uzerindeki tarih bilgisini kullanan diger ekranlar (ornegin akademik takvimin PDF export'u) toplanti tarihini kullanacak.

**Comment by dilara** [comment]
> Kurul/Komisyon kararlari listelenirken, sadece senato kararlarinin listelendiginden emin olmaliyiz. 
Senato kararlarinin diger kararlardan ayri olarak cekilebildiginden emin degiliz. Bunu kontrol edip duruma gore yeniden tartisalim.

Senato Kurul/Komisyon kaydının (bir `Unit` kaydı) tipi (`UnitType`) şu şekilde:
`=> #<UnitType:0x00005644ef38c040 id: 51, name: "Senato", code: 937, group: "committee">`
`UnitType`'ının grubu "committee" ve bütün Kurul/Komisyonların `UnitType` grubu aynı.
Bu mevcut durumda sadece Senato'nun kararlarını çekemiyoruz. Yeni bir grup tanımlayabiliriz ama etkilerini bilemiyorum @omu/backend @omu/product .

**Comment by roktas** [comment]
@dilara Senato'nun tipini özellikle ayırdık: https://github.com/omu/nokul/blob/develop/plugins/tenant/omu/db/units/src/all.yml#L29358  Örneklediğin gibi `UnitType` adı `Senato` olarak geliyor.  Bir şekilde çözülür bu.
