### ISSUE TITLE
Müfredatın birden çok programla ilişkilendirilmesini yeniden modelle

### ISSUE THREAD

**Issue by abdagli** [omu/nokul#653]
**Açıklama:**
Birinci öğretim ve ikinci öğretimin aynı ya da farklı müfredatlar kullanması ve bilgisayar mühendisliği yapıkredi müfredatı gibi özel müfredatlar göz önünde bulundurularak modellerin gözden geçirilmesi gerekiyor. Burada, aynı müfredatı kullanan iki programın açılan derslerinin de düşünülmesi gerekiyor.

**Kontrol listesi**

* [x] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [x] Use case, product ekibi tarafından incelenip onaylandı mı?
* [ ] Use case ve oluşturulan mockup'lar müşteri tarafından onaylandı mı?

**Comment by isubas** [comment]
Bu iş kaydını kapatıyorum. Gerekli görünürse tekrardan açarız.
