### ISSUE TITLE
Kurul/Komisyon ozelligini refactor et 

### ISSUE THREAD

**Issue by abdagli** [omu/nokul#663]
**Açıklama:**
- Kurul/komisyon toplantilarinda uyeler eklenebilmeli.
- Sayfa duzeni ve hikayeleri iyilestirilmeli.

**Kontrol listesi**

* [x] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [x] Use case, product ekibi tarafından incelenip onaylandı mı?
* [ ] Use case ve oluşturulan mockup'lar müşteri tarafından onaylandı mı?

**Comment by isubas** [comment]
Günü geldiğinde tekrardan açılmak üzere kapatıyorum.
