### ISSUE TITLE
OMÜ personel listesi temin edilmeli

### ISSUE THREAD

**Issue by begum** [omu/nokul#671]
**Açıklama:**

Personele ilişkin bilgilerin (kişiler, görevlendirme, izinler vs.) mevcut durumda nasıl tutulduğu öğrenilmeli.

**Kontrol listesi**

* [x] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [ ] Use case, product ekibi tarafından incelenip onaylandı mı?
* [ ] Use case ve oluşturulan mockup'lar müşteri tarafından onaylandı mı?

**Comment by ekural** [comment]
Personel listesi Nokul ekip drive'ında paylaşılanlar dizininde paylaşıldı. Eksik alanlar varsa tekrar üzerinde çalışırım.

**Comment by msdundar** [comment]
İncelediğim kadarıyla şu durumlar söz konusu:

- 6435 aktif personel var.
- 4935 pasif personel var.
- 3 personelin T.C. numarası yok - bunlar zaten pasif.
- Aktif durumda olan 582 personelin sicil numarası yok. Çoğu işçi veya 4B.
- Pasif durumdaki personelin birim bilgisi bilinmiyor. Dolayısıyla bizim bunları Nokul'da Employee olarak temsil etmemiz mümkün değil, Employee olabilmek için 'maaş alınan - resmi' birimin girilmesi gerekli.
- Aktif personelin çoğunlukla birim bilgisi mevcut, yalnızca 40 tanesinin birimi belli değil, bunların da bir çoğu yabancı uyruklu.

**Comment by ekural** [comment]
Konuyla ilgili ekstra bir istek gelmedi. Şimdilik kapatıyorum.
