### ISSUE TITLE
Ders koordinatoru kendi derslerine ait sinav notlarini girebilmeli

### ISSUE THREAD

**Issue by abdagli** [omu/nokul#700]
**Açıklama:**
Ders koordinatoru, kendi derslerini listeleyebilmeli. Listeledigi derslere tiklayarak ilgili ders kaydina gitmeli. #697 de belirtildigi gibi, derslerin de kendi verilerine kendi ekranlarindan erisilebilmeli. Ornegin dersi alan ogrencilere ders ekranindan yonlendirilebilmeliyim. Eger kullanici, dersi veren koordnatorse, ders notlarini girecegim ekrana buradan erisebilmeliyim.

**Kontrol listesi**

* [ ] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [ ] Use case, product ekibi tarafından incelenip onaylandı mı?
* [ ] Use case ve oluşturulan mockup'lar müşteri tarafından onaylandı mı?

**Ek içerik:**

[//]: # (Kaynaklar, dış bağlantılar, ekran görüntüleri, örnek çözümler ve benzeri diğer kaynakları ekleyiniz.)

**Comment by isubas** [comment]
Bu issue'nun bir çok parçası yapıldı. Eksik kısımlar için yeniden issue açılacak.
