### ISSUE TITLE
Açılan derslerde grup tanımlanırken öğretim elemanı eklemek zorunlu olmalı

### ISSUE THREAD

**Issue by begum** [omu/nokul#718]
**Bu özellik bir problemle mi ilgili? Lütfen detaylıca açıklayınız:**

Açılan derse grup eklerken öğretim elemanı seçimi yapmadan ders grubu açılabiliyor.

**Sizin çözümünüz:**

- [x] En az 1 öğretim elemanı, grup tanımlanırken zorunlu olmalı.

- [x] Ders grubundaki öğretim elemanlarından en az biri için "Grup Koordinatörü" zorunlu olmalı.

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [x] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [x] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [x] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Comment by isubas** [comment]
@ecmelkytz başlamadım. Yapabilirsin.
