### ISSUE TITLE
Kullanicilarin olusturulma senaryolari

### ISSUE THREAD

**Issue by abdagli** [omu/nokul#729]
**Açıklama:**

Ogrenci olusturulurken ya da personel olusturulurken kullanici hesaplari nasil olusturulacak, ilgili kullanicinin validasyonu gibi konular var. Bu konular hakkinda herkes fikrini buraya yazarsa bir sonraki toplantida karar alacagiz ve gelistirmeye baslayacagiz.

**Kontrol listesi**

* [ ] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [x] Use case, product ekibi tarafından incelenip onaylandı mı?
* [ ] Use case ve oluşturulan mockup'lar müşteri tarafından onaylandı mı?

**Ek içerik:**

[//]: # (Kaynaklar, dış bağlantılar, ekran görüntüleri, örnek çözümler ve benzeri diğer kaynakları ekleyiniz.)

**Comment by msdundar** [comment]
Öncelikle bu konudaki fikrim sisteme **tüm kullanıcıların** kendileri kayıt olması yönünde. Önümüzde birden çok senaryo var.

1- Kişi Türk vatandaşı olabilir, çipli kimliği olabilir.
1- Kişi Türk vatandaşı olabilir, çipli kimliği olmayabilir.
1- Kişi yabancı uyruklu olabilir, YU numarası olabilir.
1- Kişi yabancı uyruklu olabilir, YU numarası olmayabilir.

Yani sorulacak sorular:

- Türk vatandaşı mısınız?
  - Evet
    - Çipli kimliğiniz var mı?
      - Evet [Çipli kimliğin seri numarası ile valide edilir]
      - Hayır [Eski tip kimliğin seri no ve sıra no bilgisi ile valide edilir]
  - Hayır
    - YU Numaranız var mı?
      - Evet [YU numarası ile valide edilir]
      - Hayır [Valide edilemez, bilgilerini kendisi girer]

Bu durumda `User` modeline iki ayrı alan eklesek iyi olur gibi görüyorum. Birincisi MERNIS'ten valide edip etmediğimizin bilgisini tutan bir boolean alan, diğeri ise mernis'ten valide edilemeyen kayıtlar için `approve` edilip edilmediği bilgisini tutan boolean alan. İsimlendirmeyi düşünürüz, şimdilik bunlara `mernis_verified` ve `approved` diyelim.

Bir kişinin kimlik bilgileri mernis'ten doğrulandıysa `approve` edilmesine gerek yok, otomatik olarak `approve` edeceğiz. Yok, bilgilerini doğrulayamıyorsak (YU numarası olmayan yabancı kişi), manuel olarak girdiği bilgilerin onaylanması gerekecek.

Buraya kadar yazdığım senaryonun personellik ve öğrencilik ile alakası yok, yalnızca sisteme kayıt olmakla alakalı.

Öğrencilik veya personellik durumu, `approved` durumu `true` olan kullanıcılar için `ProspectiveStudent` veya `ProspectiveEmployee` ile kurgulanacak.

**Comment by ekural** [comment]
Kullanıcı oluşturma senaryoları ile ilgili doküman hazırlanmıştır. [Link](https://drive.google.com/open?id=1dtd8GtV7LAZu8cov25O2Ta5oTrXdaits) ten erişebilirsiniz. @omu/product olarak edindiğimiz bilgiler ve görüşlerimiz bu yöndedir. @abdagli ve @begum 'e teşekkür ederim.

**Comment by roktas** [comment]
[@omu/product elinize sağlık.]

Kullanıcıların (1) oluşturulması ve (2) etkinleştirilmesi bağlamında bir kaç ilke koyalım.

#### Tanımlar

**Pasif hesap**: Veritabanında kullanıcı kaydı açılmış fakat henüz etkinleştirilmemiş kullanıcı.

**Aktiflenebilir hesap**: Aktive edilebilme koşullarını sağlayan pasif hesap.

Not: Bu tanımlar `User` modelinde birer `state` olarak da düşünülebilir.  Belki daha ayrıntılı bir dokümanda bu `state`'leri ayrıntılı yazacağız, başka `state`'ler de var çünkü.

#### İlkeler

1. Kullanıcıların hesaplarını etkinleştirmesi için gerekli insan-insan etkileşimi minimize edilmeli.

2. Hesapların etkinleştirilmesi olası en erken fazda gerçekleşmeli.

3. Sistemin kullanıcıyla offline etkileşiminde birincil enstrüman cep telefonu (SMS) olmalı.

4. Kullanıcıyı tekil olarak tanımlayan hesap adları "insani" olmalı.

   Öğrenci numaralarından hesap adı üretilmemeli, kişinin isim ve soyadından türetilen isimler tercih edilmelidir.

#### Hesapların aktifleştirilmesi

- Hesaplar daima sorumlu birim tarafından önce pasif hesap oluşturularak yaratılır.

  Bu süreçte sorumlu birim işlemi (1) elle, (2) bir CSV veya Excel dosyasıyla bulk halde, (3) dış kaynaklardan bir API çağrısıyla alınan bilgilerle bulk halde yürütebilir.

  Bu ilkeye göre şunu söylüyoruz: olağan senaryolarda hesaplar kullanıcı tarafından self-service oluşturulmaz, önce ilgili birimin süreci başlatması gerekir.  Öte yandan misafir hesaplar için kısıtlama uygulanması koşuluyla self-service yapılabilir.

- Sadece aşağıdaki niteliklere sahip hesaplar **aktiflenebilir hesap** durumundadır.  Bunlara "aktiflenebilirlik bilgileri" diyelim.

   1. Doğrulanmış kimlik bilgileri.

   2. Doğrulanmış iletişim enstrümanı: Doğrulanmış cep telefonu veya (kaçınılmaz
      ise) eposta hesabı.

   3. Tekil kod; öğrenciler için öğrenci no, personel için personel no.

   4. Tekil kullanıcı adı; e-posta hesaplarında da kullanılacak.

   5. Geçici ilk parola

  Bunlardan tekil kod, kullanıcı adı ve geçici parola ilgili birim (veya sistem yöneticileri tarafından) uygulama yoluyla ilke 4 dikkate alınarak otomatik olarak üretilen bilgilerdir.  Bunlara "hesaplanan aktiflenebilirlik bilgileri" diyelim.  Diğerleri ise hesap sahibi tarafından bir girişimde bulunulmayı gerektirir.

- Bir pasif hesap **aktiflenebilir** duruma ulaşır ulaşmaz gecikmeden aktifleştirilir ve ilk erişim/kullanım bilgileri (ör. öğrenci no, kullanıcı adı, oryantasyon bilgiler) kullanıcıya görüntülenir.  Bk. ilke 2.

Bu hususlar dikkate alındığında aşağıda yazdığım sonuçlar çıkıyor ortaya.

Önce daima pasif hesaplar oluşturulur.  Bu süreçte "hesaplanabilir aktiflenebilirlik bilgileri" de (kod, hesap adı ve geçici parola) önceden üretilir.

Müstakbel (Prospective) kişi kendisine duyurulan linke girerek diğer aktiflenebilirlik bilgilerini tamamlar; kimliğini ve cep telefonunu doğrular.  Önce kullanım koşullarını görüntüleyen bir ekranla kullanıcıdan resmi onay alınır.  Onayı takiben hesap bilgileri (öğrenci no, eposta hesabı) ve ilk oryantasyon linkleri görüntülenir.  Erişim bilgileri SMS olarak da gönderilir (ilk parola dahil).

#### FAQ

- Bu süreçte arka planda ne oluyor?

  + Pasif hesaplar LDAP'ta da bulunduğundan G-Suite'te hesaplar çok önceden açılmış oluyor.

  + Hesap aktifleştiğinde prospective'lik kaldırılıyor.

  + Kullanıcı Nokul ve G-Suite'e ilk girişte parola değiştirmeye zorlanıyor.

- Girişimde bulunmamış (örneğin kayıt olmaktan vazggeçmiş öğrenci) ve dolayısıyla aktifleştirilmeiş hesaplar ne olacak?

  Pasif hesaplar daima bir "expire date" ile oluşturuluyor.  Tarih dolduğunda hala prospective durumunda olan hesaplar süpürülecek.  Örneğin kesin kayıt aralığından bir kaç gün sonraya expire olacak şekilde ayarlanmış "ProspectiveStudent"  hesapları kaldırılacak.  Bu yapıldığında LDAP'taki kayıt da kalkmış ve dolayısıyla G-Suite tarafında da kalkmış oluyor.

- Kullanılmayan pasif hesaplar için de kod üretiyoruz ve kodlar boşa gidiyor?

  Evet boşa gidiyor, bence bu sorun değil.

- `ProspectiveEmployee` senaryosundaki bekleme süreleri (güvenlik soruşturması vs) ne olacak, hesabın aktifleştirilmesi için süre bitimi mi bekleyecek?

  Beklemeyelim.  `ProspectiveEmployee` için başvuruda pasif hesap PDB tarafından oluşturuluyor.  Linki hemen kişiye verelim ve kişi hesabını benzer süreçte (doğrulanmış tel vs) aktifleştirsin.

- Cep telefonu olmayan kullanıcılar ne olacak?

  Sadece yabancı uyruklularda olabilir bu sorun.  Belki onlarda email alanı eklenebilir.  Ama diğer tüm durumlarda telefonu zorunlu yapacağız.

**Comment by roktas** [comment]
Bugünkü görüşmelerden sonra yukarıda yaptığım yorumda bazı değişiklikler oldu.  Not düşeyim:

- Müstakbel kişiyi kimlik ve tel no doğrulaması için karşılayacak ekran sadece kesin kaydı tamamlanmış kullanıcılara sunulacak.  Örneğin E-devlet'de kesin kaydını tamamlamış öğrenciler veya manuel olarak ÖİDB'de kaydını tamamlamış öğrenciler veya PDB'de manuel olarak kayıt sürecini tamamlamış personel.  Ben bunu biraz daha esnek ve basit düşünmüştüm, örneğin kesin kayıt tamamlanmasa bile bu ekranın geçilmesi ve hesabın aktive edilmesi gibi.  Bu son haliyle bu ekrana düzgün bir isim de vermek gerekiyor.  Kesin kaydı tamamlanmış kişilere sunulacak ekran olduğuna göre "prospective" diyemiyoruz buna.  Bu ekran aslında kullanıcının bizzat kendisinin Nokul'la ilk temasa geçtiği ekran oluyor.  Bu nedenle buna "hesap etkinleştirme ekranı" veya "hesap etkinleştirme adımı" demek daha uygun gibime geliyor.

- Prospective kullanıcılar için önceden veritabanında kayıt oluşturulması planında bir değişiklik yok.  ÖSYM'den de gelse ÖİDB veya PDB'de manuel de yapılsa daima ilk adım prospective kişinin kaydının açılması.  Bu süreçte kişiye tekil kod atanıyor, tekil user name belirleniyor ve ilk parola atanıyor.  Bu kayıtlar (lojiği belki basitleştirebilir düşüncesiyle) LDAP'a da aktarılabilir veya aktarılmayabilir.  Fakat kesin kayıt gerçekleşmediği sürece hiçbir şekilde LDAP üzerinden G-Suite eşzamanlaması yapılmıyor.  Ne zamanki kesin kayıt tamamlandı eşzamanlama o vakit gerçekleşiyor (ve gereken tüm bilgiler mevcut).

- ÖSYM kanalıyla gelen öğrencilerin kesin kayıtlarının tamamlanması durumu yine ÖSYM'den öğrenilebiliyor (@isubas'tan gelen tespit), mutlaka E-devlet ile konuşmak gerekmiyor.  Bu durumda Nokul'da kayıt dönemi içinde bu sorgulamayı periyodik olarak yapan bir görev olmalı.  Fakat ÖSYM'den gelen liste ile Prospective'lerin pasif hesaplarının açılması süreciyle bunu karıştırmayalım.  Önce prospectiveler pasif halde oluşturulsun sonra kayıt dönemi bitişine kadar periyodik olarak kesin kayıt durumları işlensin.

- Doğrulanmış telefon numaralarının ÖSYM veya E-devlet'ten toplanabilmesi imkanı var.  Her ne yapılırsa yapılsın "hesap aktifleştirme ekranı"nda bu numaralar yine de doğrulanmalı.  Tek fark belki pek çok kullanıcı "`05***123` numaralı telefon benim diyerek" bir şey girmeden sadece doğrulama yapacak.  Girilen telefon numarasının değiştirilmesi imkanı da sunulmalı şüphesiz.

- E-devlet'te kesin kaydını tamamlamış öğrencilere görüntülenecek bir ekran hazırlamamız gerekiyor, çünkü böyle bir imkan var.  Bu sayede E-devlet'te kaydını tamamlamış bir kişinin hemen "hesap aktifleştirme adımı"na geçiş yapması gecikme olmadan sağlanabilir.  Aksi halde öğrenci ancak birilerinden duyarak veya ders kayıtları öncesinde el mahkum bizim sayfaya uğrayacak.  Bir diğer çözüm E-Devlet veya ÖSYM'den alınan doğrulanmış telefonlara mesaj atarak davet etmek de olabilir.

**Comment by roktas** [comment]
>  * Prospective kullanıcılar için önceden veritabanında kayıt oluşturulması planında bir değişiklik yok.  ÖSYM'den de gelse ÖİDB veya PDB'de manuel de yapılsa daima ilk adım prospective kişinin kaydının açılması.  Bu süreçte kişiye tekil kod atanıyor, tekil user name belirleniyor ve ilk parola atanıyor.  Bu kayıtlar (lojiği belki basitleştirebilir düşüncesiyle) LDAP'a da aktarılabilir veya aktarılmayabilir.  Fakat kesin kayıt gerçekleşmediği sürece hiçbir şekilde LDAP üzerinden G-Suite eşzamanlaması yapılmıyor.  Ne zamanki kesin kayıt tamamlandı eşzamanlama o vakit gerçekleşiyor (ve gereken tüm bilgiler mevcut).

Bu yazılanlardan şu sonuç çıkmasın: Nokul'da kayıtlar daima ön tanımlı oluşturulacak.  ÖİDB'de veya PDB'de görevli kişinin yapacağı kayıt işlemine kullanıcının bizzat kendisinin online olarak katılması gelecekte sağlanabilir.  Bunun için @isubas'ın da ifade ettiği gibi E-devlet'in yaptığını (askerlik durumu sorgulaması vs) bir tür yapacak bir servise (veya modüle) ihtiyacımız olacak.  Esasen ÖİDB veya PDB'de görevli kişinin karşısına çıkacak ekran bazı farklılıklarla kullanıcının karşısına da konulabilir.  Fakat ilk turda buna girmeyelim.  (ilk turda belki şuna girilebilir: library-walk-in gibi misafir hesapların açılması)

Diğer bir konu AİS gibi aday servisleri bu süreçle gelecekte ilişkilendirilecek ve bu servislerin "prospective user" üretmesi sağlanacak.  Bu bağlantı standart bir formatta bir API çağrısıyla gerçekleşebilir.  Tüm bu işler "başvuru ve kabul (admission)" gibi daha büyük bir başlık altında değerlendirilmeli.

**Comment by roktas** [comment]
Bugün yaptığımız stand up'tan sonra son durum:

- ProspectiveStudent'a ilave olarak ProspectiveEmployee modelinin olması gerektiği kanısına vardık.

- Öğrenci ve Sicil no'ların prospektif kayıtlarında önceden oluşturulmasında mutabıkız.  Fakat kullanıcı adı (username) ve ilk parolanın prospektiflikten kesin kayda geçiş sırasında oluşturulması yargısına ulaştık.  Neden?  Tekil username üretilmesi için mevcut kullanıcı kayıtlarında arama yapmak gerekecek.  Eğer username üretimini önceden prospektiflik sırasında yaparsak tekillik araması için sadece kullanıcı kayıtlarının değil bir de prospektif kayıtların taranması gerekecek.  Bu büyük bir sorun değil ama kesin kayda geçiş sırasında yaparsak işler daha basitleşecek.

- G-Suite'te girişlerin SSO üzerinden yapılması (yani G-Suite'in bağımsız olmaması) senaryosu giderek ağırlık kazanıyor.  İşleri çok daha basit hale getiriyor ve açıkçası bu basitliğe şiddetle ihtiyacımız var.

- Personel tarafındaki kayıtlanmalar için de ekranların hazırlanması lazım.

Stand up'lara devam edelim, fakat https://github.com/omu/po/issues/9 iş kaydında istenenlere uygun olarak akış diyagramlarını ve use case'leri zenginleştirelim lütfen.  Şifahi işlemesin her şey.

**Comment by roktas** [comment]
Yol boyunca yapılması gereken kodlamalar (aklıma geldikçe yazacağım):

- Twilio ile telefon doğrulama
- Tekil kullanıcı adı ve rastgele ilk parola oluşturma
- Kesin kayıt durumu için YÖKSİS'ten sorgulama yapan zamanlanmış bir görev

**Comment by ekural** [comment]
Birkaç gündür @roktas, @isubas, @ecmelkytz, @abdagli ve @begum  ile yaptığımız toplantılar sonucunda prospective student sürecine ait [akış diagramı](https://github.com/omu/nokul/blob/doc-product/doc/product/prospective-process.md) ve [mockupları](http://po.omu.sh/nokul/mockups/user/?to=B835425E-A2D4-4BB3-B2FC-7F38B2F800B0) oluşturduk. Üzerinde çalışmaya devam ediyoruz ancak görüş ve önerilere açığız.

**Comment by ekural** [comment]
Bu başlık amacını tamamladı gibi o nedenle kapatıyorum.
