### ISSUE TITLE
TravisCI entegrasyonu yapılmalı

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#735]
**Bu özellik bir problemle mi ilgili? Lütfen detaylıca açıklayınız:**

[//]: # (Özelliği detaylıca açıklayınız. Eklenmesi/değiştirilmesi iyi olacak olan özelliğin netleştirilmesi, varsa yaşanan sorunların tanımı açıkça yapılmalıdır.)

Repoyu public durumuna çektiğimiz için artık TravisCI kullanabiliyoruz. CircleCI ile kıyaslandığında daha zengin bir özellik seti sunduğu için deploy'ların TravisCI'dan gelmesini tercih ediyorum. Ancak CircleCI entegrasyonu yaşamaya devam edecek çünkü zaman zaman CI/CD araçları false positive sonuçlar döndürebiliyor. Örneğin yakın zamanda selenium testlerinin paralel çalıştırdığımızda CircleCI'ın resource'larının yetmemesi gibi sorunlar olmuştu. Yani özetle:

- [x] TravisCI entegrasyonu yapılacak.
- [ ] Selenium testleri saucelabs'a tünellenecek.
- [x] Deploy'lar Travis'ten gelecek. [Dokku+Github için deploy key vs. eklenecek]
- [x] CircleCI'da bulunan deploy adımları kaldırılacak. [Şimdilik comment-out edelim]
- [ ] Entegrasyon sonrası Travis için "Don't build pushed branches" seçeneği aktive edilecek.
- [x] Travis için notifikasyonlar aktive edilecek.

Bunlar düzeltilirken aşağıdaki durumları da aradan çıkartalım:

- [ ] Plug-in'lerin .rubocop.yml dosyaları eski Ruby sürümünü işaret ediyor. `TargetRubyVersion: 2.5.1` satırları güncellenmeli.
- [x] Plug-in Gemfile'larına .ruby-version eklenmemiş, dolayısıyla .lock dosyalarında da RUBY_VERSION gelmiyor, eklentilerin Gemfile'ları güncellenmeli.

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [ ] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [ ] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [ ] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Ek içerik:**

[//]: # (Kaynaklar, dış bağlantılar, ekran görüntüleri, örnek çözümler ve benzeri diğer kaynakları ekleyiniz.)

**Comment by ecylmz** [comment]
Son durum hakkında bilgi vereyim.

Yapılan değişiklikleri şimdilik şuradan görebilirsiniz: https://github.com/omu/nokul/compare/develop...travis-ci

10.02.2019 tarihli son build: https://travis-ci.com/omu/nokul/builds/100369521

Görev 8 dakika sürdü, 4 buçuk dakikası testlerin çalışması. 2 dakika docker imajının hazırlığı. Geriye kalan 1 buçuk dakika ise travis kaynaklı.

Saucelabs ile docker-compose'u birlikte kullanamadım. Bunun nedeni saucelabs eklentisi travis'in VM'i içerisinde çalışıyor. bizim testler ise VM içerisindeki bir konteynerde çalışıyor. Testleri chromedriver paketini kurarak çalıştırdım. Saucelabs'i bizim docker imajı içerisinde çalıştırmak ayrı bir iş olur :/

Geriye kalan işler:

- [ ] travis-ci için ssh anahtarı üretip deploy etmesini sağlamak.
- [ ] Tek bir Dockerfile ile hem test hem production üretimini sağlamak. Şimdilik iki farklı Dockerfile var.
- [ ] bundle install, yarn install ve assets precompile işlemerini Dockerfile'dan çıkarıp, app.json predeploy aşamasında bu işlemleri yapmak.

**Comment by roktas** [comment]
Fikir vermesi için notification için geçmişte çalıştırdığım bir örnek vereyim (Slack notification):

```yaml
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    rooms:
      - secure: XXXXXXX
```

**Comment by msdundar** [comment]
Saucelabs şart değil, bildiğimiz chromedriver yolundan gidelim bence de.
