### ISSUE TITLE
Account isim uzayı anlamı dışında işler yapan controller'ları barındırıyor

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#749]
**Hatayı ve/veya bug'ı açıklayın:**

[//]: # (Kısa ve net bir şekilde hatanın ne olduğu açıklanmalıdır.)

Account isim uzayı; `employee`, `duty`, `position` gibi çağrıştırdığı anlam dışında işler yapan controller'lar barındırıyor.

**Olması gereken davranış:**

[//]: # (Kısa ve net bir şekilde hata yerine olması gereken uygulama davranışının ne olması gerektiğini açıklayınız. Örn: X kaydı silindiğinde Z sayfasına yönlendirme yapılmalı.)

Account klasörü yalnızca kullanıcının hesabıyla ilgili yaptığı işlerde kullanılan controller'ları barındırmalı. Örneğin: hesap oluşturma, hesabını güncelleme, profilini düzenleme, hesabına adres bilgisi ekleme vs.

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [X] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi:**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) emin misiniz?

**Ek içerik:**

[//]: # (Kaynaklar, dış bağlantılar, ekran görüntüleri, örnek çözümler ve benzeri diğer kaynakları ekleyiniz.)

**Comment by isubas** [comment]
Bu ve benzer bir kaç issue tek bir issue atında toplanıp çözülecek.
