### ISSUE TITLE
Address ve Identity için ortak controller kullanılmamalı

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#750]
**Hatayı ve/veya bug'ı açıklayın:**

[//]: # (Kısa ve net bir şekilde hatanın ne olduğu açıklanmalıdır.)

Adres ve kimlik bilgilerinin yönetimi için sadece tek bir controller tanımlı. Dolayısıyla bir kullanıcının kendisiyle ilişkili adres-kimlik işlemleri ve bir kullanıcının başka bir kullanıcıyla ilişkili adres-kimlik işlemleri aynı controller'dan yönetiliyor.

**Olması gereken davranış:**

[//]: # (Kısa ve net bir şekilde hata yerine olması gereken uygulama davranışının ne olması gerektiğini açıklayınız. Örn: X kaydı silindiğinde Z sayfasına yönlendirme yapılmalı.)

Bir user'ın kendisini yönetmesi ve bir user'ın başka user'ları yönetmesi epey farklı senaryolar. Dolayısıyla bu senaryoları karşılayacak ayrı address ve identity controller'ları gerekiyor. Bu sağlandığında kullanıcı profillerinde adres ve kimlik yönetimi yaparken URL'de çirkin görünen ID numaraları vs. gibi durumlar da düzelmiş olacak.

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [X] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi:**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) emin misiniz?

**Comment by isubas** [comment]
Bu ve benzer bir kaç issue tek bir issue atında toplanıp çözülecek.
