### ISSUE TITLE
Dokku'da bundler ve yarn için daha agresif cacheleme olanaklarına bakılmalı

### ISSUE THREAD

**Issue by roktas** [omu/nokul#758]
**Bu özellik bir problemle mi ilgili? Lütfen detaylıca açıklayınız:**

Dokku'da Dockerfile ile konuşlandırma yapıyoruz.  Travis entegrasyonunda mevcut Dockerfile'ın bundler ve yarn için CI'da düzgün cacheleme yapmadığını gördük ve düzelterek CI'a özgü bir Dockerfile oluşturduk.  Aynı yöntemin (deployment komutlarını bir parça karışıklaştırma pahasına) Dokku'da da uygulanabilir olduğunu görüyorum.  Bu doğruysa hem Dokku konuşlandırma süreleri daha da kısalacak hem de (beni asıl ilgilendiren gerekçe) tek bir Dockerfile kullanmış olacağız.

**Sizin çözümünüz:**

Dokku, CI için kullanacağımız Dockerfile ile çalışır hale getirilmeli.  Bu yapılamaz veya çok sorun çıkarırsa iş kaydı kapatılabilir.

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Comment by ecylmz** [comment]
https://github.com/omu/nokul/pull/786 ile tamamlandı.
