### ISSUE TITLE
Product takımının kolayca kullanabileceği bir sanallaştırma ortamı sunulmalı

### ISSUE THREAD

**Issue by roktas** [omu/nokul#759]
**Bu özellik bir problemle mi ilgili? Lütfen detaylıca açıklayınız:**

Product ekibi mevcut durumda tamamen beta servislerini kullanıyor.  Bu bir kaç açıdan sorunlu:

- Zaman zaman veritabanı değişikliğinden dolayı takımın gözden geçirmeleri aksayabiliyor.
- Birim bilgilerinin test edilmesi veya yeniden üretilmesi gibi beta servisleriyle gerçekleştirilemeyecek işlemler var.
- Entegrasyon testlerinde product takımı kendi özel yöntemlerini geliştirmek (ve sonrasında ana depoya katmak) isteyebilir.

Özetle @omu/product takımının geliştirme sürecine bir parça daha yakın girmesinde yarar var.

**Sizin çözümünüz:**

Aslında Vagrant (`dev` makinesi) hemen kullanılabilir.  Fakat Vagrant yöntemi geliştirme süreçleri için optimize edildi.  Product takımı için bir kaç tık daha basit bir şeye ihtiyaç var.  Travis CI entegrasyonunda denediğimiz Docker Compose güzel bir çözüm sunuyor.  O taraf tamamlanınca bu iş kaydını kapatan bir PR'da süreci dokümante edelim.

**Diğer alternatifler:**

Vagrant LXC değil de Virtualbox imajı bir seçenek.  Ama Docker Compose daha kolay görünüyor.

**Katkı sağlama:**

* [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Comment by ecylmz** [comment]
https://github.com/omu/nokul/pull/797 ile tamamlandı.
