### ISSUE TITLE
Tenant API'ye credentials eklenmeli

### ISSUE THREAD

**Issue by roktas** [omu/nokul#761]
**Bu özellik bir problemle mi ilgili? Lütfen detaylıca açıklayınız:**

Tenant eklentilerini AİS'de kullanırken farkettik.  Kiracı sırlarını da host uygulamada değil kiracı eklentilerinde (`config/credentials`) tutmak lazım.  Bunları aynı `RAILS_MASTER_KEY` ile veya (ekstra bir güvenlik katmanı olsun diye) her kiracı için ayrı anahtarlarla yönetebiliriz.

**Sizin çözümünüz:**

`Tenant.credentials` gibi bir API eklenmeli.  Host uygulamada `Rails.application.credentials` kullanılıyor.  Malum `Rails.application` da aslında bir `Engine` (miras alma yoluyla).  Fakat `Engine`'e bu özelliği koymamışlar.  Dolayısıyla `Tenant.engine.credentials` cevap vermiyor.  Sorunu Tenant nesnesine özellik olarak ekleyerek çözmeye çalışacağım.  Ama şuna emin olmamız lazım, gerçekleme gelecekte kırılmamalı.  Buna emin olamazsam `Sensitive` support modülü üzerinden gideceğim.

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

Şimdilik üzerime aldım.  Zaman bulamazsam devrederim.

* [X] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Comment by msdundar** [comment]
Bunu gerçeklerken Rails 6 ile birlikte gelecek olan ortama özel credential davranışını da göz önünde bulundurmak lazım. Bu yeni sürümde gelen özelliklerden biri olacak.

**Comment by roktas** [comment]
@msdundar Evet onu farkettim.  Şu civar: https://github.com/rails/rails/blob/master/railties/lib/rails/application/configuration.rb#L293
