### ISSUE TITLE
Entegrasyon testlerinin daha etkin şekilde yapılabilmesi için yöntemler araştırılmalı

### ISSUE THREAD

**Issue by roktas** [omu/nokul#771]
**Bu özellik bir problemle mi ilgili? Lütfen detaylıca açıklayınız:**

Entegrasyon testleri için yüklü bağımlılıklar gerekiyor.  Bu durum gerek geliştirme sırasında gerekse CI'da beklemelere yol açıyor.  Ayrıca CI'da bu araçları ayrıca kurup yapılandırmakla da uğraşıyoruz. Gerekli bağımlılıklar (chromedriver vs) uygulama konteynırında hazır olursa bu sorunlar büyük ölçüde ortadan kalkar.

Entegrasyon testleri çok önemli.  Neden?  Malum nedenler bir yana, gelecekte Nokul'daki multi-tenant yapı daha etkin kullanıldığında her tenant için deployment öncesinde entegrasyon testi yapacağız mutlaka.  Bir kaç tane kiracı olsa bile bu testlerin setuplanması çok uzun sürecektir.

**Sizin çözümünüz:**

`ondokuz/ruby-stretch` imajına Chrome headless ve Chrome driver başta olmak üzere gerekli araçları kur.

**Diğer alternatifler:**

Bu çözümün bazı sakıncaları da var:

- Atak yüzeyi büyüdüğünden güvenlik bir parça azalıyor.
- İmaj boyutu artıyor.  Yaptığım ön hesaba göre raw halde ekstra 500 MB geliyor, sıkıştırma dikkate alındığında imaj boyutunun bir kaç yüz MB artacağını tahmin ediyorum.  Nihai rakamı söylerim.

İmaj boyutunun artması büyük bir sorun değil.  Konuşlandırmalarda sadece imaj güncellendiğinde al baştan yapılıyor.  Kalan durumlarda docker cache yeterli.  CI'da ise biraz sorun.  Travis docker cachelemesi yapmıyor.  Bunu elle ekleyip duruma bakacağız.  Ama ilk denemelerde şunu gördük: Travis'in internal ağı Docker hub'dan çok yüksek hızda indirme yapıyor (muhtemelen proxy caching yapıyorlar), o kadar hızlı ki bizim cacheleme işlemi daha çok işleri yavaşlatabiliyor.   Henüz denemeye devam ediyoruz.

Alternatifler:

- Saucelab kullan.  Çok güzel bir servis ama çok pahalı ve bizi uzun vadede kurtaracak bir çözüm değil, özellikle çok kiracılı yapıda.
- Tamamen CI'da çözelim.  Olabilir ama konuşlandırma ve testlerdeki tekilleştirme hedefimi bir parça zedeliyor.  Uzun beklemeler de cabası.
- İki imaj kullan: biri production, diğeri test için.  Maintain etmesi zor.
- Entegrasyon testlerini bizim tarafta tamamen custom bir yapıya dönüştür.  Bence ciddi bir seçenek.  CI'ın yeterli gelmediği bir noktaya ulaştığımızda seçenek değil zorunlu.  Şimdilik maintain etmesi zor olduğundan tercih etmiyorum.

Bu iş kaydında çok iddialı değilim.  Şimdilik deneme kabilinden açtım.  Yukarıda saydığım sakıncaları kuvvetle tekrar eder ve/veya yeni sakıncalar sayarsanız hemen iptal edebilirim. :-)

**Katkı sağlama:**

* [X] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Comment by roktas** [comment]
Önerdiğim çözümde kararsızım, iş kaydını buna göre güncelledim.  Aklımda bir çözüm daha var, denemem lazım.

**Comment by msdundar** [comment]
CircleCI'ın kendi Docker imajlarını kullanan konfigürasyonu ben ayarlamıştım ve bugüne kadar (~9 aydır) sorunsuz çalıştı. Bundan sonrası için seçilecek yol veya yapılacak değişiklikler ancak bize aynı pragmatikliği sağlarsa anlamlı olur. Yok eğer bu yenilikler bize; CI imkanlarını kullanmaya göre daha yavaş ilerleyen, dokümantasyonu olmayan ve daha kişiye bağımlı bir süreç getirecekse üzerinde biraz daha düşünmemiz ve bu faktörleri sıfırlayarak ilerlememiz lazım.

**Comment by roktas** [comment]
Travis'te uyguladığımız çözüm (Travis'in kendisiyle birlikte) şimdilik tatminkar.  İş kaydını kapatıyorum.  Tenant'ların sayısı arttığında tekrar gündeme alırız.
