### ISSUE TITLE
Geliştirme süreçlerinde sanallaştırma araçlarının kullanımı dokümante edilmeli

### ISSUE THREAD

**Issue by roktas** [omu/nokul#777]
**Bu özellik bir problemle mi ilgili? Lütfen detaylıca açıklayınız:**

Vagrant ve yakında product ekibi için eklenecek Docker Compose araçlarının nasıl kullanılacağı herkes tarafından bilinmiyor.

**Sizin çözümünüz:**

Araçlar dokümante edilmeli.

**Katkı sağlama:**

* [X] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Comment by msdundar** [comment]
Aslında bu araçların nasıl kullanılacağı kişilerin kendi çözmesi gereken bir şey. Dokümantasyon daha çok bu araçlar büyük resimde nereye oturuyor, bizim için ne anlam ifade ediyor, varsa ipuçları/kısayollar, kullanımla ilgili standartlar/kurallarımız var mı vs. içerse de yeterli.

**Comment by roktas** [comment]
Benim de planım o yönde.  Ayrıntılı bir kılavuza ne ihtiyaç ne de yazmaya vaktim var. :-)  Vagrant'ın tüm numarası "workflow".  Bunun bir şekilde çözüleceğini varsayıyorum.
