### ISSUE TITLE
Konuşlandırma sorunu PaaS makinesini güncelleyerek çözülmeli

### ISSUE THREAD

**Issue by roktas** [omu/nokul#796]
**Hatayı ve/veya bug'ı açıklayın:**

Dokku sürümü eski kalmış durumda.  Arka plan: Travis'le deploy yaparken PaaS makinesinde diskin taglenmemiş Docker konteynerleri nedeniyle dolu olduğunu farkettik.   Disk doluluğu deploy'u da engelledi.  Eski imajları silerek bunu bir şekilde halledebiliriz ama Dokku sürümünün de eskiliğini dikkate alarak daha kalıcı bir çözüm bulmamız lazım.

Şu an (bu iş kaydı öncesinde) disk taşımada uyguladığımız hatalı bir yöntemden dolayı nokul.omu.sh servisleri çalışmıyor.  Bu bir süre daha devam edecek. 

**Çözüm**

Güncelleme iki şekilde yapılabilir: (1) in-place upgrade, (2) yeni makine kurup servisleri ona taşı.  Bu iş kaydı özelinde ikinci yoldan gidelim.  Amacımız biraz da "çalışan servisleri yeni bir PaaS'a nasıl taşırız?" tatbikatını yapmak ve süreci dokümante etmek.  Bu iş kaydı tamamlandığında:

- Süreç dokümante edilmiş olmalı
- Disk doluluğunu önceden bildirmek üzere `inspeqtor` etkinleştirilmeli (monitörleme sistemi gelinceye kadar)
- Taglenmemiş konteynerlerin düzenli silinmesi için bir çözüm geliştirilmiş olmalı

**Katkı sağlama:**

* [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi:**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığına emin misiniz?

**Comment by ecylmz** [comment]
Planım şu şekilde:

### Servislerin Ayağı Kalkması

- [ ] Eski sanalın ip'sini kullanılmayan bir ip ile değiştir.
- [ ] Paas imajından yeni bir VM ayağı kaldır.
- [ ] Bu imaja yeni eski sanalın ip'sini ata.
- [ ] dokku uygulamalarını oluştur(redis ve postgres dahil)
- [ ] Uygulamaların runtime ve build aşamalarındaki ortam değişkenlerini ata
- [ ] Volume olarak uygulamaya eklenecek dizinleri ayarla
- [ ] Veritabanı yedeklerini geri yükle
- [ ] Letsencyrpt yapılandırması ve cron
- [ ] http-auth ile anasayfa yetkilendirmesi

### Yedekleme ve Monitor

- [ ] cron ile yedekleme ayarla
- [ ] inspeqtor kur

**Comment by roktas** [comment]
https://stackoverflow.com/questions/32723111/how-to-remove-old-and-unused-docker-images

**Comment by roktas** [comment]
@ecylmz bu konuda okumaya devam ediyorum.  Şu seçenekler öne çıktı:

- Docker'a nispeten yeni eklenmiş `prune` komutu:

  ```sh
  docker system prune --all
  ```

- Spotify'ın Docker'ın prune desteğinden çok önce yazdığı [docker-gc](https://github.com/spotify/docker-gc) komutu

Bu iki yöntem arasındaki farka [şu iş kaydında](https://github.com/spotify/docker-gc/issues/199) değinilmiş.  Benim anladığım docker-gc biraz daha güvenli temizlik yapıyor.  Ama ben yine de oyumu Docker prune'dan yana kullanırım.

Cron'a gelince kararımız `docker system prune -a` ise bunu yapan betiği `/etc/cron.daily` dizine koyalım.  Debian cron.daily her gece 03:00'de çalışıyor.

Yine de iki yöntemi dikkatlice deneyelim.  Build cache'leri kaybetmek istemeyiz örneğin.

**Comment by roktas** [comment]
`docker system prune -a -f`'i benim makinede denedim.  Neredeyse her şeyi temizledi (toplamda 13 GB sildi) :-)   `-f` eklemek zorunda kaldım, aksi halde confirm istiyor (muhtemelen cron içinde istemez ama yine de eklemek lazım.).  Kesin olan bu komut build cache'leri de siliyor.  Sınırlama koymamız lazım.  Araştırıyorum...

**Comment by roktas** [comment]
https://docs.docker.com/config/pruning/

**Comment by ecylmz** [comment]
Bu görevden geriye yalnızca cron ile docker temizliği yapmak kaldı. Servisler yeni sunusunda çalışıyor. omu/doc/dokku.md dokümanına eklemeler yaptım ve omu/doc/paas.md dokümanında ise geçiş adımlarını sıraladım.

**Comment by roktas** [comment]
@ecylmz build cache'i kaybetmeyen çözümü seçeceğiz.  bir dizi deneme yapmak gerekecek :-/

**Comment by ecylmz** [comment]
`docker image prune -f` komutu untagged imajları silmeye yarıyor, cache'i silmiyor.
`docker image prune -a -f` ise kullanılmayan imajları ve untagged imajların hepsini siliyor. Bu nedenle öncelikle `docker image prune -f` ile ilerleyelim. inspeqtor sunucuda kurulu, uyarı durumunda seçtiğimiz yöntemi tekrar değerlendiririz.

**Comment by roktas** [comment]
cron.daily yaptık değil mi?

**Comment by ecylmz** [comment]
evet, cron.daily'de ve inspeqtor %75'te
