### ISSUE TITLE
Kurul/komisyon ve ilişkili modelleri için beta_seed eklenmeli

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#804]
**Hatayı ve/veya bug'ı açıklayın:**

[//]: # (Kısa ve net bir şekilde hatanın ne olduğu açıklanmalıdır.)

Kurul/komisyon menüsü altında bulunan işlemleri örneklemek için beta_seed eklenmeli.

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi:**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığına emin misiniz?

**Comment by dilara** [comment]
Örnek veri mevcut ancak calendar verileri oluşturulurken ilişkili olduğu için [db/beta_seed/calendar.rb](https://github.com/omu/nokul/blob/develop/db/beta_seed/calendar.rb)'ye eklemişim, bu yüzden gözden kaçmış olabilir. Düzenleme yapmalı mıyım? @msdundar
