### ISSUE TITLE
Kayıtlı kullanıcıların email bilgisi eksikleri tamamla

### ISSUE THREAD

**Issue by sinansh** [omu/nokul#808]
**Hatayı ve/veya bug'ı açıklayın:**

[//]: # (Kısa ve net bir şekilde hatanın ne olduğu açıklanmalıdır.)

Sistemde kayıtlı bazı kullanıcıların gerçek email bilgisi eksik olup, `<TC_Kimlik_No>@omu.edu.tr` şeklinde çözüm üretilmiş. Bu kullanıcıların tespitinin yapılıp, email bilgileri toplanmalıdır. 

**Hatayı tekrarlama için takip edilmesi gereken adımlar:**

[//]: # (1. X adresinde bulunan Y sayfasına git.)
[//]: # (2. Z butonuna tıkla.)
[//]: # (3. Sayfayı en alta kaydır.)
[//]: # (4. Görünmesi gereken metin K iken L görünüyor.)

https://dev.nokul.omu.sh/users

**Olması gereken davranış:**

[//]: # (Kısa ve net bir şekilde hata yerine olması gereken uygulama davranışının ne olması gerektiğini açıklayınız. Örn: X kaydı silindiğinde Z sayfasına yönlendirme yapılmalı.)

**Ekran görüntüleri:**

[//]: # (Varsa, hatayı görmeyi kolaylaştırılacak ekran görüntüleri.)

**Hatanın alındığı ortam:**

[//]: # (Belirtmediğiniz taktirde Ubuntu 18.04/Debian 9 üzerinde güncel Google Chrome kullandığınız varsayılacaktır.)

[//]: # (- OS: [e.g. iOS, Windows 10])
[//]: # (- Browser [e.g. chrome, safari])
[//]: # (- Version [e.g. 22])

**Hata mobil ortamda alınıyorsa:**

[//]: # (- Device: [e.g. iPhone6])
[//]: # (- OS: [e.g. iOS8.1])
[//]: # (- Browser [e.g. stock browser, safari])
[//]: # (- Version [e.g. 22])

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [x] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi:**

* [x] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [x] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [x] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığına emin misiniz?

**Ek içerik:**

[//]: # (Kaynaklar, dış bağlantılar, ekran görüntüleri, örnek çözümler ve benzeri diğer kaynakları ekleyiniz.)

**Comment by msdundar** [comment]
@sinansh Bize doğru düzgün bir personel listesi de temin edebilir misin bu vesileyle? Şuan kullanıcıları YÖKSİS'ten alıyoruz ancak kurumdan ayrıldığı halde YÖKSİS'te bulunan pek çok kişi var. Bunları da tespit edebilirsek düzeltilmesini sağlarız.

**Comment by roktas** [comment]
@sinansh Bu kampsamda Zimbra'dan da tüm accountları CSV export yapalım: https://help.bittitan.com/hc/en-us/articles/115008106887-How-do-I-export-a-user-list-from-Zimbra-into-a-CSV-file-

**Comment by roktas** [comment]
@sinansh Mustafa Çayıroğlu'yla görüştüm.  Personel listesi için otoriter kaynak olarak UBS'yi gösterdi.  Maaş bordroları için de bu servisteki verilerin kullanıldığından bahsetti.  Bu durumda @ekural sen de bakar mısın buna, UBS'den verileri çekelim.  Sorun varsa Mustafa Çayıroğlu'yla görüşebilirsiniz.

**Comment by ekural** [comment]
@roktas  aktif pasif tüm personel mi yoksa sadece aktifler mi?

**Comment by ekural** [comment]
Doğru personel listesinin ubs'de olduğunu pdb'de belirtmişti. Ubs üzerinden listeyi alabilirim ancak ubs üzerindeki görevlendirme bilgileri vs doğru değil. Bu bilgileri de daha sonra farklı yollarla düzeltmeyi deneyebiliriz.

**Comment by msdundar** [comment]
References #671
