### ISSUE TITLE
Bologno icin kullanilan EBS'nin FTP bilgilerini paylas

### ISSUE THREAD

**Issue by abdagli** [omu/nokul#815]
EBS'nin barindigi sunucunun FTP bilgileri @ecmelkytz ile paylasilmali. #795 

**Kontrol listesi**

* [x] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [x] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [x] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Comment by abdagli** [comment]
#795

**Comment by ekural** [comment]
Bilgiler @ecmelkytz ile paylaşıldı
