### ISSUE TITLE
Git History

### ISSUE THREAD

**Issue by gdemir** [omu/nokul#825]
Merhaba,

Belki işinize yarayabilir diye yazıyorum. Tarayıcı üzerinden Github dosyaların değişimlerinin kolay görünmesi için : https://githistory.xyz/

Örneğin,

Dosya : https://github.com/omu/nokul/blob/develop/app/views/admin/cities/show.html.erb

Git Geçmiş: https://github.githistory.xyz/omu/nokul/blob/develop/app/views/admin/cities/show.html.erb

Bu arada **[şu]** satırda sorun var gibi geldi: `<%==` 

[şu]: https://github.com/omu/nokul/blob/develop/app/views/admin/cities/show.html.erb#L63
Kolay gelsin, iyi çalışmalar.

**Comment by msdundar** [comment]
Teşekkürler @gdemir.

> Bu arada **[şu](https://github.com/omu/nokul/blob/develop/app/views/admin/cities/show.html.erb#L63)** satırda sorun var gibi geldi: `<%==`

Bu satırda [sorun yok](https://github.com/ddnexus/pagy#easy-to-use). Zaten tüm ERB ve HTML dosyaları da linter'dan geçiyor.
