### ISSUE TITLE
OMÜ öğrenci listesi temin edilmeli

### ISSUE THREAD

**Issue by ekural** [omu/nokul#840]
**Açıklama:**
OMÜ'de kaydı bulunan öğrencilere ait bilgiler (ad, soyad, doğum tarihi, durum vs.) temin edilmeli.

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [x] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [x] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [ ] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [x] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Comment by ekural** [comment]
Öğrenci listesini drive da paylaştım. Nokul ekip drive'ında "product paylaşılanlar" dizininden erişebilirsiniz.

**Comment by roktas** [comment]
Bu csv dosyayı standart kitaplıkla gelen csv ile parse etmeye çalışırsanız:

```ruby
students = CSV.read(File.expand_path('student_list.csv', ENV['HOME']), headers: :first_row)
```

`CSV::MalformedCSVError: Illegal quoting in line 1.` hatası alabilirsiniz.  ]Şöyle](https://stackoverflow.com/a/29422027) yapacaksınız:

```ruby
students = CSV.read(File.expand_path('student_list.csv', ENV['HOME']), headers: :first_row, encoding: "bom|utf-8")
```

Bu noktada `unknown encoding name - bom|utf-8 (ArgumentError)` hatası alırsanız csv gem'ini güncellemelisiniz.

FYI: @isubas, @msdundar

Vakit kaybetmeyin diye not ediyorum.

**Comment by roktas** [comment]
Bir diğer not.  Bu çok büyük bir dosya, sadece CSV parse bende 12 sn'de tamamlandı.  Marshal dump/load yoluyla bu süre 1/3 oranında (bende 4 sn) düşebiliyor.  Gist: https://gist.github.com/0fdc789061ec7b2f41f74d4b1adf74c5

**Comment by roktas** [comment]
Herhangi bir optimizasyon girişiminde bulunmadan elde ettiğim ilk sonuçlar:

```
./test.rb > ~/numbers  37,86s user 0,40s system 99% cpu 38,266 total
Processed:    295653 Skipped:    111786 Average attempt:   1 Max attempt:  19
```

- ~400_000 öğrencinin isim üretimi 37 sn sürdü
- ~300_000 öğrenci için tekil isim üretildi
- ~100_000 kayıtta hata var (tc kimlik veya isim yok)
- Burası güzel isim üretiminde ortalama çakışma sayısı 1
- En büyük çakışma sayısı 19 (ama 300_000 üretimde "noise")

**Comment by roktas** [comment]
19 gibi çakışma sayıları tekrarlı kullanıcılardan kaynaklanıyor (tc kimlik aynı), bunları çıkardığımda en büyük çakışma sayısı 3 oldu.  Toplam çakışma sayısı da 250_000'de 635, yani 1000'de ~2.
