### ISSUE TITLE
Dosya ile sisteme veri aktarmak için file upload mekanizması geliştirilmeli

### ISSUE THREAD

**Issue by isubas** [omu/nokul#848]
**Bu özellik bir problemle mi ilgili? Lütfen detaylıca açıklayınız:**

`ProspectiveStudent`, `ProspectiveEmployee` ve `Profile`(Öğrenci resimleri) gibi modellere veri aktarımı için birkaç yöntem var bu yöntemlerden biri de `.csv` veya belirlenen bir dosya formatında bir
dosya yüklenmesi ve bu dosyadaki verilerin ilgili model tablosuna aktarılması şeklindedir. Ek olarak bu modellerin gelecekte çoğalabileceği unutulmamalıdır. Bu bağlamda bizim bir uploader mekanizmasına ve buna bağlı olarak dosya işleme mekanizmasına ihtiyaçımız var.

**İhtiyaçlar**

- Her bir model için farklı dosya formatları belirlenebilir ve dosya upload edilirken bu formatlara göre validasyon edilmesi gerekir. **Örneğin**, `ProspectiveStudent` için `.csv` formatında dosya yüklenmesi gerekirken, Profile için `.zip, .tar.gz` formatlarından herhangi birinin yüklenmesi istenebilir.
- Her bir dosya hangi model için yüklendi ve bu dosya ile hangi işlem yapılacak gibi, dosyayı işleme esnasında kullanılacak bilgiler bir tabloda tutulmalıdır.
- Dosya yükleme formu tek bir yerden yönetilmemeli, kullanılabilirlik açısından hangi model için yükleme yapılacaksa o alana dosya yükleme formu eklenmelidir. (DRY'a uygun şekilde) **Örneğin;** `ProspectiveStudent` modeli ile ilgili bir dosya sisteme yüklenecek ve işlenecekse, bu form ve linkler `ProspectiveStudent` ile alakalı bir sayfada veya menüde görüntülenmelidir.
- Dosya yüklendikten sonra işlenmesi gerekiyor, bunun için her bir file türüne uygun şekilde `worker`'lar oluşturulmalı ve tek bir `interface` üzerinden bu workerlar çalıştırılabilmelidir.
- Dosya başarılı bir şekilde aktarıldıysa bu dosyanın durumu `işlendi` olarak değiştirilmelidir. Tabi dosyanın bir kaç durumu olmalıdır. Örneğin; `yeni yüklendi`, `işleniyor`, `işlendi`, `başarısız`, vb..
- Dosya işleme sırasında bir `progress bar` ile işleme durumunu takip etmek gerekiyor. `sidekiq-status` gibi bir araçla worker üzernden status bilgisi alınabiliyor. Bununla ilgili bir çalışma yapılmalıdır.
- Dosyalar yüklenirken imkan varsa modellere göre klasör yapısı kurulmalıdır. (Minio tarafında klasörlü şekilde durmalıdır.)

**Sizin çözümünüz:(Draft)**

- `ImportFile` adında bir model oluştur. Bu model ile dosya yüklemelerini yapacağız. (ActiveStorage kullanılacak) **Not:** Model ismi değişebilir ben sadece ilk başta aklıma geleni yazdım.
   
   - **ImportFile**
     - name: string
     - related: Model Adı(enum olabilir)
     - status: enum
     - processed_at: datetime

- Her bir model için bir import-concern oluştur ve validasyon vb özel durumları buradan yönet.
- `ImportFile.last.process` denildiği anda eğer dosya işlenmediyse worker'a gönderilsin ve gerekli işlemler yapılsın.
- Dosya import için tek bir form oluştur ve ilgili alanlarda bu formu dinamik olarak oluştur.
- Dosya yükleme durumunu görüntülemek için bir progress-bar oluştur. (Js kullanılarak dinamik olarak gösterilecek)

**Diğer alternatifler:**

- Yorumlarda diğer arkadaşlardan bekleniyor.

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [x] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [x] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [x] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Comment by msdundar** [comment]
Bunu konuşuruz ancak isim konusunda bir not düşeyim, çeşitli yerlerde bu kargaşa gözüme çarpıyor ve bu isimlendirme konusu tam anlaşılmamış gibi görüyorum. Bu vesileyle yazmış olayım.

- Ruby'de class'lara isim verirken **noun** kullanırız.
- Method isim verirken **verb** kullanırız.
- Modüllere isim verirken ise **adjective** kullanırız.

Dolayısıyla `ImportFile` model için kötü bir isim. Yukarıdaki sistematik ile bunu örneklersek:

- Model => `ImportedFile`
- Method => `import_file`
- Modül => `Importable`

Bir şeye isim verirken bu kuralları takip ederseniz göze kulağa daha hoş gelen kodlarımız olur.

**Comment by isubas** [comment]
Günü geldiğinde tekrardan açılmak üzere kapatıyorum.
