### ISSUE TITLE
Pilot kullanım için 5 bölüm/program seçilmeli

### ISSUE THREAD

**Issue by ekural** [omu/nokul#849]
[//]: # (Yapılması beklenen görevi net olarak yazmalısınız. Örneğin; Öğrenci işleri daire başkanlığından tüm öğrencilerin bulunduğu öğrenci listesini dijital olarak al, json formatında google drive'da nokul ekip drive'ında paylaş ve linkini bu issue'nun altında yorum olarak belirt.)
Nokul'da iş takiplerinin yapılacağı 5 bölüm/program seçilmeli. Seçim aşamasında ilgili bölüm/programların içerikleri (organizasyon, öğrenci, ders, müfredat...) kontrol edilmeli.
**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [x] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [x] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [x] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [x] Konuyla ilgili açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Comment by ekural** [comment]
Şuan için belirlediğim bölüm/programlar:

1. Ziraat Fakültesi - [Tarım Ekonomisi](http://ebs.omu.edu.tr/ebs/program.php?dil=tr&mod=1&Program=2717)
2. Bafra Turizm M.Y.O. - [Turizm ve Seyahat Hizmetleri](http://ebs.omu.edu.tr/ebs/program.php?dil=tr&mod=0&Program=5018)
3. İktisadi ve İdari Bilimler Fakültesi - [Siyaset Bilimi ve Kamu Yönetimi](http://ebs.omu.edu.tr/ebs/program.php?dil=tr&mod=1&Program=2748)
4. İktisadi ve İdari Bilimler Fakültesi - [Uluslararası Ticaret ve Lojistik](http://ebs.omu.edu.tr/ebs/program.php?dil=tr&mod=1&Program=4786)
5. Sağlık Hizmetleri M.Y.O. - [Odyometri](http://ebs.omu.edu.tr/ebs/program.php?dil=tr&mod=0&Program=4784)

**Comment by msdundar** [comment]
BÖTE'de ekleyebiliriz, son iki yılda epey az öğrencisi var.

**Comment by ekural** [comment]
Eğitim Fakültesine bu yıl genel bir müfredat değişikliği geldi. O nedenle şimdilik uzak durma taraftarıyım
