### ISSUE TITLE
Repo'ya hassas verilerin gönderilmesi engellenmeli

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#853]
[//]: # (Yapılması beklenen görevi net olarak yazmalısınız. Örneğin; Öğrenci işleri daire başkanlığından tüm öğrencilerin bulunduğu öğrenci listesini dijital olarak al, json formatında google drive'da nokul ekip drive'ında paylaş ve linkini bu issue'nun altında yorum olarak belirt.)

Nokul reposuna hassas verilerin (ortam değişkeni, şifre, URL vb.) gönderilmesi geliştirme aşamasındayken engellenmeli.

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [X] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Konuyla ilgili açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Comment by msdundar** [comment]
Okuma ve denemeler sonucunda şu noktaya vardım:

- [git-secrets](https://github.com/awslabs/git-secrets) ile hassas veriler commitlenmeden önce tespit etmeliyiz.
- [gitrob](https://github.com/michenriksen/gitrob) veya [trufflehog](https://github.com/dxa4481/truffleHog) ile repoyu düzenli olarak tarayarak sızıntı var mı incelemeliyiz.

`git-secrets` için regex yazmak gerekiyor. Aşağıdaki eşleşmeleri case insensitive olarak yakalasın istiyoruz:

```
master_key
rails_master_key
access_token
access_key
secret_key
bearer_token
```

Regex setini bunlarla da sınırlı tutmayarak, gelecekte yanlışla push edilebilecek başka pattern'leri de şimdiden ekleyebiliriz: https://github.com/dxa4481/truffleHogRegexes/blob/master/truffleHogRegexes/regexes.json

## Links

- https://snyk.io/blog/ten-git-hub-security-best-practices/

**Comment by roktas** [comment]
Bu iş kaydını omu/debian üzerinden karşılamaya çalıştım: https://github.com/omu/debian/commit/eff0c5de8744be407dacf33ffe762c4cfd6edd75

Yapılması gereken basitçe şu olmalı (bende çalıştı):

- `scripts` betiğini PATH'te bir yere alın (kurulu değilse)

  ```sh
  sudo curl -fsSL -o /usr/local/bin/scripts https://raw.githubusercontent.com/omu/debian/master/bin/scripts
  sudo chmod +x /usr/local/bin/scripts
  ```

- Sistem geneli Git desteğini kurun

  ```sh
  sudo scripts operator/git
  ```

Neden böyle yaptım?

Git-secrets Git hook mekanizmasıyla çalışıyor. Bu mekanizmanın önemli bir zaafı var: çoklu hook desteklemiyor.  Hali hazırda Nokul'da git-lfs hook kullanıyoruz.  Bir de git-secrets kurarsak git-lfs'te sıkıntı olur.   Bir diğer konu da bu iş kaydının aslında Nokul'a özel olmaması.  Her ne yapacaksak tüm projelerde bunu kullanabilmeliyiz.  Tüm bu nedenlerle Nokul'da örneğin bir rake task'ı uygun bir çözüm görünmüyor.

Bu problemi herhangi bir Git-hook framework'ü kullanmadan en basit şekilde çözmeye çalıştım:

- (omu/debian'daki sistem geneli yapılandırma politikamız bir yana) Geliştiricinin kişisel yapılandırmalarıyla karışmaması için Git'i sistem geneli yapılandırdım.  Bu yapılandırmada Git hooklarını tüm takımın kullanabileceği bir yere aldım: https://github.com/omu/debian/blob/master/etc/git/gitconfig#L20  Özetle kişisel Git ayarlarınız bu düzenlemeden sonra aynen çalışmaya devam etmeli (aksi halde bug kaydı açın).

- Bu hookları git-lfs ve git-secrets desteklerken varsa "per repository" hookları da çalıştıracak şekilde oluşturdum: https://github.com/omu/debian/tree/master/etc/git/git/hooks  İzlediğim yol gayet basit ve sessizce iş gören türden.

- Git-secrets'i de bu yapılandırmaya bağladım.  [Düzenli ifadeler](https://github.com/omu/debian/blob/master/etc/git/git/secrets) ve örneğin [bir hook](https://github.com/omu/debian/blob/master/etc/git/git/hooks/pre-commit#L2) (@msdundar linkini verdiğin truffle regexleri de düzelterek ekledim)

- Hazır el atmışken "sensible" bir Git ayarı da ekledim: https://github.com/omu/debian/blob/master/etc/git/gitconfig

- Hooklara yaptığımız müdahale sayesinde tüm ekibin ortak olarak kullanabileceği bir mekanizmaya da sahip olmuş oluyoruz.  Gelecekte farklı düzenlemelerle bunu zenginleştirebiliriz.

Herhangi bir vakitte bu düzenlemede bir güncelleme olursa `sudo scripts operator/git` ile kurulumu tekrarlamanız yeterli.

@msdundar Test edelim, hata ve ilave bir istek yoksa iş kaydını kapatacağım.

**Comment by roktas** [comment]
Düzenli ifadeleri oluştururken şu makalenin ekinden de yararlandım: https://blog.acolyer.org/2019/04/08/how-bad-can-it-git-characterizing-secret-leakage-in-public-github-repositories/

**Comment by roktas** [comment]
`git secret --scan` nokul'da epey false positive üretti.  Düzelteceğim.

**Comment by roktas** [comment]
Paternleri elden geçirdim ve false pozitifleri düzelttim.  Yukarıda yazdığım bilgiler ışığında bir de siz test ederseniz makbule geçer.  İlgili PR içeri alındığında bu iş kaydı da kapatılacak ve tüm geliştirme makinelerinde git-secrets'in kullanımını zorunlu hale getireceğim.
