### ISSUE TITLE
Eksik lint denetimlerini ekle

### ISSUE THREAD

**Issue by roktas** [omu/nokul#868]
**Bu özellik bir problemle mi ilgili? Lütfen detaylıca açıklayınız:**

Aşağıdaki dosya tipleri için de lintleme yapılmalı:

- Shell betikleri
- Markdown dokümanları

**Sizin çözümünüz:**

omu/omu'dakine benzer bir düzenleme yapalım.  Bunu yaparken shell betikleri için şunu kullanabiliriz:

```sh
find -type f -and -not -regex '\./\(\.git\|app\|test\)/.*' | xargs file --mime-type | grep text/x-shellscript$ | cut -f1 -d:
```

(varsayım: bin dizinindeki binstub'lar çoğunlukla shell değil ruby betiği; ama gelecekte sorun olursa patterni düzenleriz)

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Comment by roktas** [comment]
@huseyin https://github.com/omu/omu/blob/master/.markdownlintrc bunu depo köküne ekleyerek başlayacağız

**Comment by msdundar** [comment]
@huseyin Dokümanları da linter'a göre düzeltelim, hatalı doküman kalmasın (nokul, xokul vs. dahil)

**Comment by roktas** [comment]
@huseyin satır uzunluğunu 120 yapalım (bu durumda code için istisna koymaya da gerek yok)

**Comment by roktas** [comment]
@huseyin bugün (pazartesi) kapatalım iş kaydını
