### ISSUE TITLE
Hesap aktifleştirilirken kullanım hakları ve koşulları onayı alınmalı

### ISSUE THREAD

**Issue by ecmelkytz** [omu/nokul#889]
**Bu özellik bir problemle mi ilgili? Lütfen detaylıca açıklayınız:**

Hesap aktifleştirilmeden önce kullanım hakkı ve koşullarını içeren bir sözleşme yazısı kullanıcıların karşısına çıkacak. Bu onaylanmadan hesap aktifleştirilmemeli.

[//]: # (Özelliği detaylıca açıklayınız. Eklenmesi/değiştirilmesi iyi olacak olan özelliğin netleştirilmesi, varsa yaşanan sorunların tanımı açıkça yapılmalıdır.)

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [x] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [x] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [x] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [x] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Comment by ecmelkytz** [comment]
@omu/product  ekibi ile konuşmalarımız neticesinde, T.C ve telefon numarası doğrulandıktan **sonra** kullanıcının karşısına gizlilik politikasını, kullanıcı sözleşmesini vs. içeren bir yazı gelecek ve kişi bunu onayladıktan sonra hesabı aktifleştirilecekti.

Bu gizlilik politikası, kullanım hak ve koşulları vs. sadece hesap aktifleştirme işlemi sırasında kişinin karşısına gelen veriler olmamalı. Bu bilgilere herkes herhangi bir sign işlemi yapmadan [örnekteki](https://www.linkedin.com/legal/user-agreement) gibi erişebilmeli.

Netice itibariyle bu onaylama işlemini başka sayfaya yönlendirme yapmadan aynı sayfa içerisinde (TC ve telefonun doğrulandığı yerde) sadece bu politikalara ulaşım linki vererek check yaptırmayı düşünüyorum. İlk etapta bu verileri bootstrap modal içerisinde de gösterebilirim. 

Aşağıya incelediğim bazı şirketlerin bu konudaki çözümlerinin görselini ekledim.

Siz ne dersiniz? @omu/backend, @omu/product 

|   |  | 
|---|---|
| Linkedin | ![linkedin_signup](https://user-images.githubusercontent.com/937358/54993444-d6623e80-4fd2-11e9-98fd-9ef7adf618e8.png) 
| Facebook  | ![facebook_signup](https://user-images.githubusercontent.com/937358/54993512-04e01980-4fd3-11e9-9a06-6b5a2412d213.png)
| Mailchimp  | ![mailchimp_signup](https://user-images.githubusercontent.com/937358/54993561-26410580-4fd3-11e9-85cf-476d504d746e.png)
| Microsoft | ![microsoft_signup](https://user-images.githubusercontent.com/937358/54993779-b0896980-4fd3-11e9-865e-da399fb96855.png)

**Comment by abdagli** [comment]
Kullanicinin en son neyi onayladigini da bilmemiz gerekebilir. Konuyla ilgili bir `analiz` issue'su actik. Neticelendirdigimizde daha iyi cevap verebiliriz.

UI acisindan bir onerim yok. Ilgili component'leri en guzel sekilde degerlendireceksindir. Ancak gerekli her yerde ilgili sozlesmelerin kullanicinin erisimine sunmak dogru bir adim. Ayrica KVKK da konuyla ilgili bazi kurallar getirmis olabilir. Bu konuyu da analiz issue'su olarak acip konusacagiz.

**Comment by msdundar** [comment]
@ecmel Ayni fikirdeyim. Kayit olarak bu kurallari kabul etmis sayilirsiniz diyip basit bir sayfaya baglanti verebiliriz. Kimsenin okumadigi o kullanim kosullarina gider. Dolayisiyla cokta takilmamak lazim.

KVKK alti doldurulmamis ve tutarsiz bir kanun. Devlet kurumu oldugumuz icin bizi pekte baglamiyor zaten.

GPDR'da bir balondu söndü. Yalnizca AB vatandasi ogrenciler soz konusu oldugunda bizle alakasi var. Ticari bir amacla veri isleme yapmadigimiz icin yine bizi cok baglamiyor. Unutulma hakki vs. gibi seylerin bir devlet kurumu icin karsiligi zaten yok.

Dolayisiyla bu ise takilmadan basit bir linkle gecelim diyorum. Yalnizca kisi hangi kosullari hangi tarihte kabul etmis bilgisini tutsak yeter.

**Comment by roktas** [comment]
Slack'te not düştüm.
