### ISSUE TITLE
Sisteme kayıtlanma özelliği kaldırılmalı

### ISSUE THREAD

**Issue by ecmelkytz** [omu/nokul#897]
**Bu özellik bir problemle mi ilgili? Lütfen detaylıca açıklayınız:**

Devise'ın `registrable` modülü, bununla ilgili sayfalar ve testler kaldırılmalı.

[//]: # (Özelliği detaylıca açıklayınız. Eklenmesi/değiştirilmesi iyi olacak olan özelliğin netleştirilmesi, varsa yaşanan sorunların tanımı açıkça yapılmalıdır.)

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [x] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [x] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [x] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [x] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Comment by msdundar** [comment]
bunu birlikte konusmustuk, ancak simdi baktigimda `registrable` modulunu kaldirmanin mumkun olmadigini goruyorum, cunku bu modul sadece yeni kayitlanmayi degil, mevcut kaydin duzenlenmesi islevini de yerine getiriyor.
