### ISSUE TITLE
Panelden kullanıcı oluşturulamıyor

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#91]
http://localhost:3000/users/new bu sayfadan kullanıcı oluşturamıyoruz çünkü devise default olarak kullanıcı oluşturduktan sonra login'e yönlendirdiği için 'zaten login olduğumuzu' söylüyor ve kullanıcıyı oluşturmuyor. Stackoverflow ve devise sayfalarında çözüm anlatılmış.

**Comment by dilara** [comment]
https://github.com/plataformatec/devise/wiki/How-To:-Manage-users-through-a-CRUD-interface
