### ISSUE TITLE
Birimlere effective_unit_id alanı eklenmeli

### ISSUE THREAD

**Issue by begum** [omu/nokul#911]
[//]: # (Yapılması beklenen görevi net olarak yazmalısınız. Örneğin; Öğrenci işleri daire başkanlığından tüm öğrencilerin bulunduğu öğrenci listesini dijital olarak al, json formatında google drive'da nokul ekip drive'ında paylaş ve linkini bu issue'nun altında yorum olarak belirt.)

İlişkili birimlerin eşleştirilmesi için yok.yml dosyasında ilgili birimlere `effective_unit_id` alanı eklenmeli. (bk. #885)

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [x] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [x] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [x] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [x] Konuyla ilgili açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Ek içerik:**

[//]: # (Kaynaklar, dış bağlantılar, ekran görüntüleri, örnek çözümler ve benzeri diğer kaynakları ekleyiniz.)

**Comment by begum** [comment]
`effective_unit_id` üzerinde çalışırken farkettiğim şöyle bir durum var. Canik'ten bize gelen bazı programları ilişkilendirebileceğim ana program bulunmuyor. Örnekle açıklayayım:
```
 İç Mimarlık Programı (%25 Burslu)
 İç Mimarlık Programı (%50 Burslu)
 İç Mimarlık Programı (Tam Burslu)
 İç Mimarlık Programı (Ücretli)
```
yukarıdaki 4 programa `effective_unit_id` ile verebileceğim "İç Mimarlık Programı" adlı (burs durumu belirtmeyen) bir programımız yok. Bu durumda nasıl ilerlemeliyim karar veremedim.

**Comment by msdundar** [comment]
Sanirim 'ucretli' olani parent kabul edip ilerleyebiliriz. Neticede ozel universitelerde programlar default olarak 'ucretli'dir?

**Comment by begum** [comment]
Bahsettiğim durum sadece 3 ana programın eksik olmasından kaynaklanıyor. 
```
 İç Mimarlık Programı (%25 Burslu)
 İç Mimarlık Programı (%50 Burslu)
 İç Mimarlık Programı (Tam Burslu)
 İç Mimarlık Programı (Ücretli)

 Siyaset Bilimi ve Uluslararası İlişkiler Programı (%25 Burslu)
 Siyaset Bilimi ve Uluslararası İlişkiler Programı (%50 Burslu)
 Siyaset Bilimi ve Uluslararası İlişkiler Programı (Tam Burslu)
 Siyaset Bilimi ve Uluslararası İlişkiler Programı (Ücretli)

 Uluslararası Ticaret ve İşletmecilik Programı (%25 Burslu)
 Uluslararası Ticaret ve İşletmecilik Programı (%50 Burslu)
 Uluslararası Ticaret ve İşletmecilik Programı (Tam Burslu)
 Uluslararası Ticaret ve İşletmecilik Programı (Ücretli)
```
@msdundar dediğin gibi "ücretli" program seçip effective unit olarak verilebilir, hepsinde mevcut. Bu durumda önce; varsa ana programı yoksa ücretli programı effective unit belirleyerek standartlaştırabiliriz.

**Comment by msdundar** [comment]
> @msdundar dediğin gibi "ücretli" program seçip effective unit olarak verilebilir, hepsinde mevcut. Bu durumda önce; varsa ana programı yoksa ücretli programı effective unit belirleyerek standartlaştırabiliriz.

Bana mantikli geliyor.
