### ISSUE TITLE
LDAP nitelikleri üretilmeli

### ISSUE THREAD

**Issue by roktas** [omu/nokul#912]
**Bu özellik bir problemle mi ilgili? Lütfen detaylıca açıklayınız:**

#655 numaralı iş kaydının ön hazırlığı kapsamında LDAP people ağacında Nokul kullanıcılarına ait niteliklerin üretilmesi ve yönetilmesi gerekiyor.

**Sizin çözümünüz:**

Üretilmesi gereken LDAP nitelikleri Hokul alt projesinde çıkartıldı: https://github.com/omu/hokul/blob/develop/docs/guide.md  Bu doküman ve ilgili niteliklerin semantiği dikkate alınarak:

- User, Student ve Employee modellerinden bu nitelikleri üretecek gerçekleme yapılmalı.
- Üretilen niteliklerin kullanıcının yaşam süresi boyunca güncel tutulması için gerekli mekanizma (Sidekiq görevleri vb) oluşturulmalı
- Bu vesileyle modellerdeki eksiklik ve çarpıklıklar da varsa düzeltilmeli.

**Çalışma yöntemi**

Bu bir epik görev.  Görevi @roktas, @isubas ve @ecylmz birlikte yürütecek.

- İlk araştırmaları izleyen en erken zamanda adı basitçe `ldap` olan bir geliştirme dalı açalım.  Lütfen artık uzun süre kimsenin haberdar olmadığı kişisel çalışmalardan kaçınalım.  Hemen iyi bir şey çıkması gerekmiyor,  önemli olan şeffaflık ve paylaşım.

- Tüm tartışmaları Slack hokul kanalında yürütelim.  DM'den kaçınalım (bu not özellikle bana).

- Vagrant'ı sonuna kadar kullanalım.

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Ek içerik:**

- https://github.com/omu/hokul

**Comment by msdundar** [comment]
Ilk iterasyon cok dummy bir kod dahi olabilir, en azindan bu is bana en hizli oyle cozulur gibi geliyor. Ikinci-ucuncu iterasyonlarda, gundemde daha acil bir is yoksa refactor edilebilir.

**Comment by isubas** [comment]
`LdapData` ve `LdapSynchronousError` adında iki model oluşturmayı düşünüyorum,

```ruby
class CreateLdapDatas < ActiveRecord::Migration[6.0]
  def change
    create_table :ldap_datas do |t|
      t.references :user, null: false, foreign_key: true
      t.jsonb :values
      t.datetime :synchronized_at
      t.timestamps
    end
  end
end
```

```ruby
class CreateLdapSynchronousError < ActiveRecord::Migration[6.0]
  def change
    create_table :ldap_synchronous_error do |t|
      t.references :ldap_data, null: false, foreign_key: true
      t.text :description
      t.boolean :resolved, dafault: false
      t.timestamps
    end
  end
end
```

Kullanıcının, herhangi bir şekilde verisi değiştiğinde (parolası, adı, soyadı , öğrencilik durumu vb.) `callback`'ler çalışacak ve `LdapData` modeline bir kayıt ekleyecek. Bu modele kayıt eklendiği anda farklı bir `callback` ile sidekiq görevi çalışacak ve bu veriyi ldap'a senkron etmeye işlevini başlatacak.

Senkron işlevi sorunsuz bir şekilde tanımlanınca `synchronized_at` set edilecek. Eğer bir sorun oluşursa LdapSynchronousError modeline hatanın açıklaması ile birlikte bir kayıt düşülecek. Böylelikle senkron edilen veri ve oluşan hatalar arayüz üzerinden görüntülenecek ve saklanacak.

**Comment by roktas** [comment]
Uygundur.  İsimlendirme için öneri: `LdapSynchronizationError` veya `LdapSyncError`

**Comment by msdundar** [comment]
Burada sidekiq monitoring yapma ihtiyaci bir kez daha ortaya cikiyor. @omu/ops WDYT? Sidekiq icin ozellikle latency'yi monitorlemeliyiz.
