### ISSUE TITLE
Telefon doğrulama kodu aktivasyon sayfasına eklenmeli

### ISSUE THREAD

**Issue by ecmelkytz** [omu/nokul#914]
**Bu özellik bir problemle mi ilgili? Lütfen detaylıca açıklayınız:**

Hesap aktifleştirilirken kullanıcılardan telefon doğrulama kodu alınması sağlanmalı.

[//]: # (Özelliği detaylıca açıklayınız. Eklenmesi/değiştirilmesi iyi olacak olan özelliğin netleştirilmesi, varsa yaşanan sorunların tanımı açıkça yapılmalıdır.)

**Sizin çözümünüz:**

Aktivasyon sayfasında ilgili bilgiler doğru doldurulduktan sonra aynı sayfa üzerinde modal ile açılan telefon doğrulama ekranı gelmeli. 

[//]: # (Kısa ve net bir şekilde konuyla ilişkili olarak sizin önerileriniz neler, sizin öneriniz kabul edilirse neler olacak, uygulama da neler iyileşecek açıklayınız.)

**Diğer alternatifler:**

[//]: # (Konuyla veya sunduğunuz çözümle ilgili düşündüğünüz diğer alternatifler neler? Konuya dahil olarak kişiler neleri göz önünde bulundurmalı?)

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [x] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi**

* [x] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [x] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [x] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Comment by ecmelkytz** [comment]
Telefon doğrulaması yapıldıktan sonra bunu kişinin adres bilgilerindeki telefon numarası alanına kaydediyorum. Adres bilgisi olmayanlar için bir adres oluşturmam lazım ancak ilçe ve açık adres alanlarını doldurmadan bir kayıt oluşturamıyorum. Dolayısıyla doğrulanan telefon kodunu kaydedememiş oluyorum.

Aklıma gelen bazı çözümler:

1. `User` modelindeki `profile_preferences` parametrelerine `mobile_phone` alanı ekle ve doğrulanan telefonu bu alanda tut. Ancak bu alanı kişi güncelleyemesin.
2. `Address` modelindeki db'ye kaydetmeyi engelleyen `constraint`'ları düzenle `validate: false` kullanarak adres oluşturulmasını sağla. Kişi, adresimi mernis'den güncelle dediği zaman diğer boş alanlar güncellensin.
3. Adresi olmayanları şimdilik hesaba katma.

Bunlar veya bunların dışında ne önerirsiniz? @omu/backend

**Comment by roktas** [comment]
Telefon numarası Nokul'da çok önemli bir kimlik (!) unsuru, neredeyse tüm kritik haberleşme bunun üzerinden yürüyor.  Acaba adres içinde tutmadan büsbütün ayrı kendi başına bir entite mi yapsak bunu?  @msdundar ?

**Comment by isubas** [comment]
User modelindeki profile_preferences `phone_number` niteliği var fakat telefon bilgisini burada tutmak yerine `User` modelinde telefon numarası için bir kolon olarak ekleyebiliriz. Adres modelinden de kaldırabiliriz.

**Comment by sinansh** [comment]
> User modelindeki profile_preferences parametrelerine mobile_phone alanı ekle ve doğrulanan telefonu bu alanda tut. Ancak bu alanı kişi güncelleyemesin.

Yukarıdaki yöntem mantıklı diye düşünüyorum. Cep telefonu bilgisi ile adres bilgisi birbirinden ayrılmalı düşüncesindeyim, çünkü bunların arasında bir ilişki yok. 

Alan güncelleme kısmı ayrı bir tartışma konusu. Alanı kullanıcı self service güncelleyebilmeli, belki yönetici onay veya ikinci doğrulama faktörü eklenebilir.

**Comment by msdundar** [comment]
`profile_preferences` bence dogru yer degil. Orada olacak tek sey kisinin is telefonu, dahili numarasi vs. olmali. O amacla koymustum onu. Zaten profil public olacagi icin orada cep telefonu numarasi olmamali.

Iki olasilik aklima yatiyor. 1) telefon numaralarini basli basina bir model yapariz. Bir kullanicinin birden fazla dogrulanmis telefon numarasi da olabilir. 2) User modeline bir phone_number alani ekleriz.

**Comment by msdundar** [comment]
`profile_preferences` altindaki telefon numarasini public olacak sabit + dahili numara gibi dusunebiliriz. Ismi konusunda cok emin degilim eger kafa karistirmasin derseniz `phone_number` yerine `fixed_phone` kullanabiliriz.

@isubas'in dedigi gibi Address modelinden telefon alanini kaldiralim ve User modeline ekleyelim.
