### ISSUE TITLE
BAUM personeli seed edilmeli

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#917]
**Hatayı ve/veya bug'ı açıklayın:**

[//]: # (Kısa ve net bir şekilde hatanın ne olduğu açıklanmalıdır.)

Kayitlanmayi kaldirdigimiz ve hesap aktivasyon sistemine gectigimiz icin sisteme disardan erisim artik mumkun degil. Dolayisiyla hesabimi olusturmak icin sunucuya girip konsola erismem, kullanici olusturmam, rolleri eklemem, kendime rolu vermem vs. gerekiyor.

**Olması gereken davranış:**

[//]: # (Kısa ve net bir şekilde hata yerine olması gereken uygulama davranışının ne olması gerektiğini açıklayınız. Örn: X kaydı silindiğinde Z sayfasına yönlendirme yapılmalı.)

BAUM personeli icin seed verisi hazirlayalim, ayni zamanda bu kisilerin admin olarak seed edilmesini saglayalim. Herkes ayni sifreyi kullanabilir. Hatta bildigimiz (op kullanici sifresi gibi) bir sifre olursa daha iyi olur.

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi:**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığına emin misiniz?

**Comment by isubas** [comment]
Proje public olduğundan dolayı BAUM personel bilgilerinin `seed.rb` veya buna benzer bir dosya içerisinde geçmesinin çok uygun olmadığını düşünmekteyim. Bu yüzden sistem genelinde tam yetkiliye sahip dummy bir kullanıcı oluşturdum. Bu kullanıcı üzerinden dilediğiniz kullanıcıya yetki verebilir veya sistemi bu kullanıcı üzerinden yönetebiliriz.
