### ISSUE TITLE
Form parametrelerinin güvenliği sağlanmalı

### ISSUE THREAD

**Issue by ecmelkytz** [omu/nokul#920]
**Bu özellik bir problemle mi ilgili? Lütfen detaylıca açıklayınız:**

[integrate-phone-verification-code](https://github.com/omu/nokul/tree/integrate-phone-verification-code) branch'ında yaptığım çalışmada form ile gönderdiğim [parametreler](https://github.com/omu/nokul/compare/integrate-phone-verification-code?expand=1#diff-eab21e073536459291176b4e7ea0b9c1R10) değiştirilebiliyor. Bu sebeple bir güvenlik açığı ortaya çıkıyor.
@isubas ile bu parametrelerin güvenliğini [ActiveSupport::MessageEncryptor](https://api.rubyonrails.org/v5.2.3/classes/ActiveSupport/MessageEncryptor.html) kullanarak sağlayabileceğimiz üzerinde konuştuk. 

Bu problemle ilgili düşünce ve önerileriniz için konuyu tartışmaya açıyorum.

**Kontrol listesi**

* [x] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [x] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [x] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığından emin misiniz?

**Comment by msdundar** [comment]
Burayi tam anlamadim. Bahsettigimiz sey asagidaki satirdan telefon numarasinin duzenlenebilmesi mi?

```
<input value="+4915256282451" type="hidden" name="phone_verification[mobile_phone]" id="phone_verification_mobile_phone">
```

**Comment by msdundar** [comment]
Anlamadigim bazi konular var:

1- ProspectiveEmployee olustururken neden telefon format dogrulamasi yapmiyoruz? Muhtemelen bunu olusturacak personel usendigi icin uydurma numaralar girecek buraya.

2- Eger bir ProspectiveEmployee'yi telefon numarasi ile birlikte olusturuyorsak, bir daha kisilerin neden telefon numarasi girmesini istiyoruz? Kisinin girdigi kimlik numarasiyla iliskili ProspectiveEmployee'nin telefonuna neden dogrulama kodunu yollamiyoruz? Ilk basta acaba telefon numarasini bilmedigimiz ProspectiveEmployee'ler olabilir mi acaba diye dusundum ancak bu alan ProspectiveEmployee olustururken bos gecilemiyor. Buradaki is akisini netlestirmemiz lazim, varsayim nedir, telefon numarasini bilmedigimiz ProspectiveEmployee olabilir mi olamaz mi?

3- Eger telefon numarasini bilmedigimiz ProspectiveEmployee olmayacaksa dogrulama formundan telefon numarasi girme kismini kaldirip, form submit edildiginde ilgili kullaniciyi ProspectiveEmployee icinde bulabilirsek dogrulama kodunu yollariz ve yine ayni sekilde 'dogrulama kodu' kutusunu acariz ve kisinin ayni sekilde dogrulama kodunu girmesini isteyebiliriz.

4- Eger telefon numarasini bilmedigimiz ProspectiveEmployee olacaksa, herhangi bir kisinin ad, soyad, dogum tarihi ve kimlik seri numarasini bilen herkes onun adina dogrulama zaten yapabilir.

**Comment by roktas** [comment]
Telefon numararası bir sabit.  Telefon numarasını bilmediğimiz Prospective olamaz, nokta.  Herşeyi bu kabule göre yapalım.  Ayrıca dediğin gibi doğrulama sırasında (numarasını bildiğimiz halde) Prospective'e numara sorulması ekstra bir güvenlik önlemi hatırlarsanız.

**Comment by roktas** [comment]
@ecmelkytz benim kafam karıştı biraz (Ramazan'a ver) :-)  Bu PR'daki doğrulama akışını (tercihen ekran görüntüleriyle birlikte) en baştan bir yazar mısın.

**Comment by ecmelkytz** [comment]
> Burayi tam anlamadim. Bahsettigimiz sey asagidaki hidden field satirindan telefon numarasinin duzenlenebilmesi mi?
> 
> ```
> <input value="+4915256289999" type="hidden" name="phone_verification[mobile_phone]" id="phone_verification_mobile_phone">
> ```
Branch üzerinde değişiklik yaptığım için parametreleri gösterdiğim satır değişmiş ondan anlaşılamamış sanırım. Eski haliyle [şu satırdaki](https://github.com/omu/nokul/commit/c5c2327938c4976c2d02f2c931f47b97b0f2c432#diff-eab21e073536459291176b4e7ea0b9c1R10) parametrelerin güvenliğinden bahsediyorum. Hidden field ile gönderdiğim alanda sıkıntı yok. Bu alanı kişi değişse bile formda yazdığı telefona doğrulama kodu gönderileceği için değiştirilen telefon ile doğrulama kodu hiçbir zaman eşleşmeyecek.

**Comment by ecmelkytz** [comment]
@msdundar 
1. `ProspectiveEmployee` bir görevli personel tarafından oluşturulan ve bizim sistemde kişinin hesabını aktifleştirme mekanizmasını yürütebilmemiz için tuttuğumuz bir veri. Yani adaylıkla ilgili hiç bir süreci şu an işletmiyoruz. Dolayısıyla telefon alanı zorunlu bir alan değil. Burada `ProspectiveEmployee` telefon alanı kesin zorunlu olmalı diyebiliriz ancak bütün `Prospective`'lerin telefon numarası olmak zorunda diyemeyiz buna bulk olarak kaydettiğimiz `ProspectiveStudent`'lar uymayabilir.

2. `ProspectiveStudent` hesaba katılmamış sanırım. Çünkü aynı form üzerinden hem personelin hem de öğrencinin hesabını aktifleştiriyoruz. Dolayısıyla telefon doğrulama alanının kaldırılması söz konusu olamaz. (Farklı formlarda olsun diye radikal bir karar alınmadığı sürece...)
Kişinin telefon numarası görevli bir personel tarafından **doğru** girilmiş olsa bile tekrar kişinin kendisinin doğrulama kodu ile telefonunu doğrulamasında ne gibi bir sakınca var anlayamadım. Sonuçta görevli tarafından girilen bir telefon ile kişinin telefonunu kendisinin doğrulaması aynı güvenlikte ve doğrulukta olmayacaktır.

3. Hem seri no hem de telefon numarası ile doğrulama yapıyoruz.

**Comment by ecmelkytz** [comment]
Aktivasyon sayfası:
![aktivasyon_sayfası](https://user-images.githubusercontent.com/937358/58807753-5cc57d00-8621-11e9-85fa-1b8534f570b6.png)

@roktas hocam doğrulama mekanizması şu şekilde:

1. Form parametreleri validasyonlarına(TC 11 karakterli olmalı vs.) bakılır sorun varsa işlem durur.
2. Forma girilen `id_number`'a ait aktif bir user olup olmadığına bakılır,  **var** ise işlem durur. Hesap aktifleştirmeye gerek yok, zaten aktif durumda.
3. Arşivlenmemiş bir adaylığın olup olmadığına bakılır,  **yok** ise işlem durur. Aktifleştirilmeyi bekleyen bir aday yok anlamına gelir.
4. Girilen verilere göre kimlik kontrolü yapılır. Veriler yanlış ise işlem durur.
5. Telefon doğrulama kodu gönderilir. (Bu aşamaya kadar bütün validasyonlardan geçilmiş olur.)

`İşlem durur`'dan kastım ilgili durumla ilgili bir hata mesajı verilir ve geri kalan validasyonlar çalıştırılmaz. Tüm validasyonlardan başarıyla geçilirse kişiye telefon doğrulama kodu gönderilir. 

Telefon doğrulama formu aşağıdaki gibi modal ile açılır ve doğru kod girilirse hesap aktifleştirilmiş olur. Tam da bu form ile gönderilen parametrelerin güvenliğinde sıkıntı oluyordu. Doğrulama kodu doğru girilse ve parametre ile gönderilen `user` ve `prospective` bilgileri değiştirilirse yanlış kişinin hesabı aktifleştiriliyordu.

![phone_modal](https://user-images.githubusercontent.com/937358/58808125-0dcc1780-8622-11e9-95a8-779e9466e6ad.png)
