### ISSUE TITLE
Rubocop ve Markdownlint için kurumsal yapılandırmalar baz alınmalı

### ISSUE THREAD

**Issue by roktas** [omu/nokul#924]
**Hatayı ve/veya bug'ı açıklayın:**

Kurumsal olarak tüm projelerde kullanılmasını istediğimiz Rubocop ve Markdownlint yapılandırmalarını bir süre önce merkez depoya almıştık: https://github.com/omu/omu/tree/master/etc/rubocop ve https://github.com/omu/omu/tree/master/etc/markdownlint

Bu yapılandırmaları güncellemeleri kolayca alacağımız şekilde Nokul'da (ve diğer tüm projelerde) etkinleştirmeliyiz.  Aksi halde işler kurumsal olmaktan çıkıyor.

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [X] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi:**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) olmadığına emin misiniz?

**Comment by huseyin** [comment]
Bu iş kaydıyla alakalı PR merge edilmiş. Bu yüzden iş kaydını kapatıyorum.
