### ISSUE TITLE
db:seed aşamasında "phone_number" kolonu bulunamıyor

### ISSUE THREAD

**Issue by huseyin** [omu/nokul#933]
#### Hatanın açıklaması

Veritabanı `seed` edilirken aşağıdaki hata üretiliyor:

```
SQL error during exec: ERROR:  column "phone_number" of relation "addresses" does not exist
LINE 2361: INSERT INTO public.addresses (id, type, phone_number, full_a...
```

#### Hatayı tekrarlamak için takip edilmesi gereken adımlar

- `bin/rails db:seed SAMPLE_DATA=true` komutu çalıştırılmalı

#### Olması gereken davranış

- Seed verilerini başarılı şekilde veritabanına yüklemeli

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [X] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [X] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [X] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

- Hatanın ekran görüntüsü
  ![image](https://user-images.githubusercontent.com/10838794/59725028-c73b0780-9234-11e9-9efa-3a5373123f05.png)

**Comment by huseyin** [comment]
hata son rake task refaktörleri sonrasıda ortaya çıkmış olabilir. emin değilim :thinking:

**Comment by msdundar** [comment]
Address modelinden bu sutunu kaldirmistik hata ondan. Bu statik dump olayi hic icime sinmedi :/

**Comment by huseyin** [comment]
@msdundar bunu sürekli up to date tutmak gerekiyor gibi. Var mı başka problemli yanları?

**Comment by msdundar** [comment]
evet, tek sorun bu. surekli guncel tutmak dert.

**Comment by huseyin** [comment]
@msdundar peki bunun başka yolu var mı veya static dump çok gerekli mi? bunun kararına göre bu bug'ı fix'leyelim istersen. bence sorarsan bir süre daha idare edelim
