### ISSUE TITLE
Mekan yönetim sistemi kararlaştırılmalı ve alt işlere bölünmeli

### ISSUE THREAD

**Issue by huseyin** [omu/nokul#935]
#### Kullanım senaryosu

Meksis genel olarak şöyle:

1. Binalar, sınıflar ve bunlara ait ders programlarının read-only işlemleri
2. Ders programlarının ve akademik birimlerin writable işlemleri
3. Bunların dışında kalan fonksiyon (AnaFonksiyon ve AltFonksiyon gibi) işlemleri

Bunlar alt işlere ayrılmalı ve nasıl birşey olması gerektiğine karar verilmeli.

#### Katkı sağlama

- @ekural hocam hangisinden başlayacağımıza ve nasıl birşey istediğimize karar verelim. Bence ilk aşama daha elzem.
- @ekural hocam ayrıca veri gönderdiğimiz işlemlerde test verilerine ihtiyacımız var. Bunu öğrenebilir miyiz?

#### Kontrol listesi

- [X] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [X] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [X] Özellik ürün takımı tarafından incelendi ve onaylandı
- [X] İş kaydını "Product" projesiyle ilişkilendirdim
- [X] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

Ek içerik yok.

**Comment by ekural** [comment]
Bu konu yapılsada açıklamaları geç kaldı biraz. @huseyin le yol haritamızı belirledik ve konuyla ilgili Vedat hocayla görüştük. Yol haritamız şu şekilde:
1- Birimler ile mekan bilgileri eşleştirilmeli
2- Mekanlar kullanım işlevlerine (meksisteki yapıya göre fonksiyon) göre filtrelenebilmeli.
3- Birimler harita üzerinde konumlarıyla eşleştirilmeli.
4- Birim bazında veya bina bazında istatistikler üretilebilmeli
5- Farklı düzeylerde rapor üretilip çıktı verilebilmeli.
6- İdarenin giriş yapıp birimlerine ait verileri görüntüleyebileceği ekranlar üretilmeli.

Mekanlar ile ilgili ilk versiyon hedeflerimiz bu kadarla sınırlı. Bu noktadan sonraki hedeflerimiz birimler ile ders programlarının eşleştirilmesi ve ders programlarının görüntülenmesi.
Bu aşamada verilerin insert, update edilmesi ile ilgili bir hedef belirlemedik. Bu konular Nokul belirli bir olgunluğa ulaştıktan sonra ele alınacak.

**Comment by roktas** [comment]
@ekural işi uzun bir paragrafla özetlemekle yetinmeyin. Bu iş kaydı zaten işin parçalanmasını talep eden bir meta kayıt. Bu noktadan sonra yeni iş kayıtları açarak ilerleyin.  Aranızda şifahi olarak neyi nasıl yapacağınızı tartışabilirsiniz, bunları yazmak (ben aksini tercih etsem bile) mutlaka gerekmiyor. Ama tartışmaların sonucunda gerçeklenecek her feature için atomik boyutta iş kayıtları açmanız mutlaka gerekiyor.
