### ISSUE TITLE
Personel sayfalarında görüntülenecek bilgiler belirlenmeli

### ISSUE THREAD

**Issue by ecmelkytz** [omu/nokul#937]
#### İş kaydı
Personel profil sayfasında hangi bilgilerin nasıl görüntüleneceği belirlenmeli.
 
[//]: # (Kısa ve net şekilde iş kaydının hedeflediği problemi tanımla)
[//]: # (Kısa ve net bir şekilde çözüm önerini yaz)

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- @ekural, @abdagli birlikte personel profil sayfalarında hangi bilgilerin görüntüleneceğine karar vermemiz lazım. Bu süreçte tasarımsal olarak hangi bilgilerin nerede görüntüleneceğini de netleştirirsek geliştirme aşaması daha hızlı olacaktır.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] İş kaydı hata bildirimi veya ürün özelliği dışında bir niteliğe sahip
- [x] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

**Comment by ekural** [comment]
3 farklı otomasyondan bu sayfalarda hangi bilgilerin olduğunu inceledim. Başlıklar ve bilgiler şu şekilde:
1. Otomasyon:
- Hizmet bilgileri -> Sigorta dökümü vb.
- İletişim bilgileri
- İzin bilgileri
- Kişisel bilgiler
- Personel detay (Eğitim bilgileri - İdari görev bilgileri)
2. Otomasyon:
- Eğitim bilgileri
- Akademik ünvanlar
- Uzmanlık alanları
- İdari görevler
- Ödüller
- Özgeçmiş
- Görev yaptığı birimler
- İlgi alanları
- Bildiği diller
- Akademik cv

Bu başlıklara göre bizim için şu başlıkları özetledim.
- Hesap Bilgileri (Şuan mevcut)
Kullanıcı hesabına ait oluşturma, güncelleme, son hatalı giriş vb. bilgiler.
- Kimlik Bilgileri (Şuan mevcut)
- İletişim Bilgileri
Telefon, E-Posta, Adres vb. bilgilerin bulunduğu alan. Buradan telefon için doğrulama, güncelleme ekranlarına yönlendirilmeli.
- Eğitim Bilgileri
Kişilere ait eğitim bilgileri. Kişi beyanına dayalı veya Yöksis tabanlı olabilir. Ancak yöksisten alsak dahi eski kayıtlar gelmeyecektir.
- Personel Detay
Akademik, idari geçmiş ve izin geçmişleri burada toplanabilir. Akademik ünvan geçmişi, İdari görev geçmişi burada listelenir. İzin geçmişi gibi bilgilerin UBS'den çekilmesi gerek. Bilgilere şuan erişebiliyoruz ancak bir adaptörle XOKUL üzerinden veya başka bir şekilde bilgilerin sağlanması gerek. (Kısmi olarak zaten mevcut). 

Ödüller vb. başlıklar şuan için bize gerekli değil ana başlıklar çıktıktan sonra bu tarz ek başlıklar için tekrar iş kaydı açabiliriz.

**Comment by roktas** [comment]
> Bu süreçte tasarımsal olarak hangi bilgilerin nerede görüntüleneceğini de netleştirirsek geliştirme aşaması daha hızlı olacaktır.

Bu ayrı bir iş kaydı ve öyle de yaptım (#944).  İşleri her birisi kendi içinde anlamlı küçük parçalara bölerek ilerleyelim.

@omu/product Bir an önce bunu toparlayalım.  Bakın iş kaydı 7 gün önce açılmış ses yok.  Dün @ekural bir toparlama yapmış yeterli reaksiyon yok.

**Comment by abdagli** [comment]
@roktas hocam konu gundemimizde. Daha da odaklanıyoruz bugünkü konuşmadan sonra zaten. 7 gün önce issue açıldıktan sonra @omu/product olarak toplantı yaptık zaten ve çeşitli ürünleri inceledik öncelikle. Dün de @ekural bunları yorum olarak yukarı yazdı. #944 te de hem benzer uygulamaların özellik matrisin hem de diğer uygulamaların özellik matrisini üzerinde titizlikle çalışarak cikartacagiz.
