### ISSUE TITLE
Mekanlar konum bilgileri ile eşleştirilmeli

### ISSUE THREAD

**Issue by ekural** [omu/nokul#949]
#### Kullanım senaryosu
Mekanların harita üzerinde gösterilebilmesi için konum bilgileri gerekiyor. Ancak meksiste bu veriler olmasına karşın servis bu bilgileri sağlamıyor. Mekanların harita üzerinde gösterilebilmesi için konum bilgilerinin girişinin yapılabileceği ekranların oluşturulması gerekiyor.

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Özellik ürün takımı tarafından incelendi ve onaylandı
- [ ] İş kaydını "Product" projesiyle ilişkilendirdim
- [x] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

**Comment by msdundar** [comment]
MEKSIS'e yazsak API'a bunu eklemezler mi?

**Comment by baran** [comment]
> MEKSIS'e yazsak API'a bunu eklemezler mi?

MEKSİS'e yazdım, cevap bekliyorum.

**Comment by baran** [comment]
> > MEKSIS'e yazsak API'a bunu eklemezler mi?
> 
> MEKSİS'e yazdım, cevap bekliyorum.

Eposta'ya dönüş olmadığı için gün içinde telefonla bilgi almaya çalışacağım.

**Comment by baran** [comment]
> > > MEKSIS'e yazsak API'a bunu eklemezler mi?
> > 
> > 
> > MEKSİS'e yazdım, cevap bekliyorum.
> 
> Eposta'ya dönüş olmadığı için gün içinde telefonla bilgi almaya çalışacağım.

@ekural konu ile sen ilgilenir misin?

**Comment by baran** [comment]
> > > > MEKSIS'e yazsak API'a bunu eklemezler mi?
> > > 
> > > 
> > > MEKSİS'e yazdım, cevap bekliyorum.
> > 
> > 
> > Eposta'ya dönüş olmadığı için gün içinde telefonla bilgi almaya çalışacağım.
> 
> @ekural konu ile sen ilgilenir misin?

Bu hafta işi sonlandırıp issue'yu kapatalım.

**Comment by ekural** [comment]
SDU'dan Nazmiye Kilim irtibat kişisi. Kişisel cep telefonundan dahi 4 5 defa aradım ancak herhangi bir geri dönüş yok. Hafta sonuna kadar aramaya devam edeceğim.

**Comment by baran** [comment]
> SDU'dan Nazmiye Kilim irtibat kişisi. Kişisel cep telefonundan dahi 4 5 defa aradım ancak herhangi bir geri dönüş yok. Hafta sonuna kadar aramaya devam edeceğim.

SMS/Whatsapp imkanlarından da taciz etmeyi ihmal etmeyelim. 👍

**Comment by ekural** [comment]
Geçtiğimiz Perşembe Nazmiye Hanım'a ulaştım oda beni servisi geliştiren Cevriye Hanım'a yönlendirdi. Aramalar ve SMS dahil herhangi bir iletişim kuramadım. Beklemedeyim.

**Comment by ekural** [comment]
Konuyla ilgili halen dönüş yok. Verilerin servis ile alınmasını debt olarak bırakabiliriz. Mevcut durumda veriler manuel olarak girilebilir. Toplam bina sayısı 169. Bina ile ilgili konum bilgilerini (varsa) yapı işlerinden almaya çalışacağım. Yoksa manuel olarak girişini sağlarız.

**Comment by baran** [comment]
@abdagli **15.11.2019** tarihine kadar manuel olarak konum bilgilerinin girişi sağlansın.

**Comment by abdagli** [comment]
NOKUL'daki `Building`'lerin [geocode'larını](https://gist.github.com/abdagli/e919c41a8524c8aa60a88150c2e476e8) oluşturdum. Bulunamayan `Building`'ler ve hatalı geocode'lar için manuel kontrol yapacağım.

**Comment by abdagli** [comment]
Geocode'lardaki `key` değerlerinin hangi `Building`'lere karşılık geldiğini gösteren [gist](https://gist.github.com/abdagli/b350021192fd70bfc1ade148b97b0b86).

**Comment by abdagli** [comment]
169 kaydın 163 adedine lat/lon değerleri girildi. 11 adet kayıt harita üzerinde arama yapılarak manuel girildi. Bunun dışındaki 152 kayıt Google Geocode API kullanılarak belirlendi.

Tesbit edilemeyen 6 kayıt;

- https://dev.nokul.omu.sh/meksis/buildings/41
- https://dev.nokul.omu.sh/meksis/buildings/42
- https://dev.nokul.omu.sh/meksis/buildings/43
- https://dev.nokul.omu.sh/meksis/buildings/51
- https://dev.nokul.omu.sh/meksis/buildings/67
- https://dev.nokul.omu.sh/meksis/buildings/72

Bu kayıtları lokasyonları bilen birinin girmesi gerekiyor. Ya da bana bu lokasyonları tarif ederlerse haritadan bulup ben girebilirim.

**Comment by abdagli** [comment]
- Yukaridaki 6 lokasyonu bulamadim. Bazilari insaat halinde bazilari ise muallak.
- Veriler manuel islemlerle sisteme girildigi icin bir sekilde otomatik seed edilebilir olmali.

**Comment by sinansh** [comment]
İnternet Salonu Satış Üniteleri Öğrenci İşleri Bürosu: 41°22'05.3"N 36°12'24.2"E
İnternet Salonu Satış Üniteleri Kafeterya: 41°22'04.3"N 36°12'23.7"E
İnternet Salonu Satış Üniteleri Sağlık Ünitesi İş ve İnsan Kaynakları: 41°22'04.7"N 36°12'25.3"E

Okul Öncesi Araştırma Uygulama Merkezi: 41°22'09.3"N 36°12'23.1"E
Okul Öncesi AUM için yer **tahminidir**. Gistlerde Çocuk Üniversitesi(Bildiğimiz Anaokulu) listede yok, olsa olsa bu binadır varsayımı ile eklenmiş bilgidir. 

Ladik MYO'yu gözümle gördüm ama Ladik'te tam yerini bilmediğim için haritadan koordinat çıkaramadım. 

Güzel sanatlar kampüsü hakkında çok bi bilgim olmadığı için Mimarlık Ek bina hangisi tam bilmiyorum.

**Comment by ekural** [comment]
Bu issue tamamlandı. Uzun süre açık kaldı kapatıyorum.
