### ISSUE TITLE
Git LFS iş akışını aksatıyor

### ISSUE THREAD

**Issue by roktas** [omu/nokul#960]
#### Hatanın açıklaması

Git pull sonrasında dosya modified görülüyor ve kurtulmak istediğimde aşağıdaki hatayı alıyorum:

![image](https://user-images.githubusercontent.com/47842/60754169-e16f3680-9fe5-11e9-8bf6-84ed226f8635.png)

- [X] Ekran görüntüsü ekte

Hatırlamadığım başka sorunlar da var.  Git LFS CI ve deployment tarafında da çok sorun çıkardı.  Bunu Git LFS dışında bir yere alalım.  Önerim: https://s3.omu.sh

P.S. Hatayı bir şekilde çözerim (`git lfs pull` vs).  Ama benim derdim Git LFS'in genel olarak böyle bir proje için iş akışını zaman zaman engelleyecek sıkıntılar çıkarması.  Bunların hepsi çözülebilir ve dokümante edilebilir.  Ama ne gerek var. :-)

#### Katkı sağlama

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [X] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [X] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by roktas** [comment]
@huseyin Buna bakalım.

**Comment by roktas** [comment]
FYI @huseyin meksis merge edildikten sonra bakacak

**Comment by huseyin** [comment]
bununla ilgileniyorum

**Comment by roktas** [comment]
@huseyin ping

**Comment by roktas** [comment]
- Seed dosyasını LFS yerine s3.omu.sh'a alalım
- İlgili Rake tasklerini düzeltelim

**Comment by roktas** [comment]
@huseyin son durum?

**Comment by huseyin** [comment]
bugün PR çıkmayı hedefliyorum hocam
