### ISSUE TITLE
Mekan sisteminde üretilen raporlara baum badge eklenmeli

### ISSUE THREAD

**Issue by ekural** [omu/nokul#961]
Sistemden üretilen mekan raporlarının alt bölümüne BAUM rozeti eklenmeli. 

[//]: # (Kullanım senaryosunu yaz veya dış bir dokümana bağlantı oluştur)

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Özellik ürün takımı tarafından incelendi ve onaylandı
- [ ] İş kaydını "Product" projesiyle ilişkilendirdim
- [x] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

**Comment by huseyin** [comment]
ref. https://github.com/omu/nokul/commit/986bcf58a23ac6ab783aefc41783c6e5edb0939c
