### ISSUE TITLE
Akademik takvimlerde pdf butonu hata veriyor

### ISSUE THREAD

**Issue by begum** [omu/nokul#968]
#### Hatanın açıklaması

Akademik takvim çıktısı alınamıyor. [500] İçsel hata mesajı görüntüleniyor.

#### Hatayı tekrarlamak için takip edilmesi gereken adımlar

[//]: # (1. X adresinde bulunan Y sayfasına git.)

1. Takvim Yönetimi / Akademik Takvimler sayfasına git
2. Mevcut takvimlerden biri için pdf butonuna tıkla
(https://dev.nokul.omu.sh/calendars/1.pdf)

#### Olması gereken davranış

[//]: # (Kısa ve net bir şekilde uygulama davranışının ne olması gerektiğini açıkla.)
[//]: # (Örnek: X kaydı silindiğinde Z sayfasına yönlendirme yapılmalı.)

#### Hatanın alındığı ortam

- [X] Masaüstü

[//]: # (Belirtmediğiniz taktirde Ubuntu 18.04/Debian 9 üzerinde güncel Google Chrome kullandığınız varsayılacaktır.)
[//]: # (- OS: [ör. iOS, Windows 10])
[//]: # (- Browser [ör. Chrome, Safari])
[//]: # (- Version [ör. 22])

- [ ] Mobil

[//]: # (- Device: [ör iPhone6])
[//]: # (- OS: [ör. iOS8.1])
[//]: # (- Browser [ör. stock browser, Safari])
[//]: # (- Version [ör. 22])

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [X] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [X] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by roktas** [comment]
Bu hatayı tekrar açıyorum (bk #1200)
