### ISSUE TITLE
Rollere göre navigasyon menülerinin içeriklerini belirle

### ISSUE THREAD

**Issue by abdagli** [omu/nokul#969]
#### İş kaydı

Rollere göre navigasyon menülerinde yer alacak linkler belirlenmeli. Bunun icin oncelikle roller belirlenmeli. Sonrasinda hangi ekranlari kimler gorecek belirlenmeli. Sonuc olarak hangi link hangi lokasyonda kimlere gorunecek tasarlanmali.

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [ ] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [ ] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [ ] İş kaydı hata bildirimi veya ürün özelliği dışında bir niteliğe sahip
- [ ] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [ ] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [ ] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by abdagli** [comment]
Konuyla ilgili geçtiğimiz hafta @omu/product ekibi olarak mini bir toplantı yaptık. Bu hafta üzerinde çalışıyor olacağız. @ekural ve kendime issue'yu assign ediyorum. Gerekli durumda @begum de dahil olacaktır.

**Comment by roktas** [comment]
Gerçek kullanımda ağırlıklı olarak şu senaryo geçerli, kişi sadece öğrenci veya personel olacak.  UX'i buna göre optimize etmemiz lazım.  Kişinin hem öğrenci hem personel olduğu durum olağan değil ve bu durumu özel olarak yöneteceğiz.

**Comment by ekural** [comment]
Öncelikle menülerde **temelde** nelerin olmasını istediğimize dair genel bir liste çıkarıp sonra üzerinde düzenlemeler yapma yoluna gitme taraftarıyım. Bunun için liste elemanları genellikle düzensiz olarak yazacak. Gruplama, birleştirme, listeyi genişletme gibi işlemleri sonradan yazacağım.

İlk olarak durumu sadece " kişi sadece öğrenci veya personel olacak" şeklinde incelediğimizde 3 durum ortaya çıkıyor. Bunlar:
- Öğrenci -> En geniş kullanıcı kitlesi
- Personel (Akademik) -> Öğretim elemanları
- Personel (idari) -> Öğretim faaliyetlerinde daha az etkin. Genellikle kendi işlemlerini takip edecek grup.

Bu üç durumu ele alırsak görüntülenmesini düşündüğüm menü elemanları:
## Personel (Akademik)
- İzin işlemleri
- Görevlendirme işlemleri
- Derslerim
- Not Girişi
- Danışmanlık işlemleri
   - Öğrenci takip (Danışmanı olduğum öğrenciler, başarı durumları, dereceler...)
   - Ders kayıt onay

## Personel (İdari)
- İzin işlemleri
- Görevlendirme işlemleri

## Öğrenci
- Akademik takvim
- Müfredat
- Öğrenci belgesi
- Transkript
- Harç işlemleri
    - Ödemelerim
    - Yeni ödeme
- Ders kayıt
- Not görüntüleme
- Akademik durum analizi (Ortalamam ne? Mezun olabilmek için hangi dersleri vermem gerek? vb.)

Bu çerçeveyi belirlemek adına bir liste. Bu temel rollerde görüntülenmesini istenen menülerle ilgili görüşlerinizi belirtirseniz çalışma devam ederken onları da eklerim.

**Comment by begum** [comment]
Mevcut ekranlardan yola çıkarsak; Öğrenci İşleri Daire Başkanlığı Yetkilisi, Personel Daire Başkanlığı Yetkilisi ve Kurul/Komisyon gündem ve toplantılarını girecek kişilerin yukarıdakilere ek olarak gerçekleştirebileceği işlemler var. Yetkilendirme aşamasında bunlara göre menüleri olmalı.

**Personel: Öğrenci İşleri Yetkilisi**
- İstenen belgeleri tanımlama
- Akademik takvimde etkinlik tarihlerini tanımlama
- Aday öğrenci işlemleri
- Ders, müfredat tanımlama

**Personel: Personel Yetkilisi**
- Aday personel işlemleri

**Personel: Kurul/Komisyon Sorumlusu**
- Bulunduğu komisyona gündem/toplantı ekleme

**Comment by ekural** [comment]
Temel roller için menüler belirlendi diğer roller için ya ayrıca issue açarız yada bu issue yu tekrar açarız. Kapatıyorum
