### ISSUE TITLE
Kullanıcı profil sayfası oluşturulmalı

### ISSUE THREAD

**Issue by ecmelkytz** [omu/nokul#985]
#### İş kaydı
Personeller için #944 iş kaydında belirlenen profil sayfası oluşturulmalı. Bu sayfa public olmayan kısmı içerir.

![](https://user-images.githubusercontent.com/618030/61793092-f2fa7000-ae26-11e9-9306-a2af7f90df68.png)

[//]: # (Kısa ve net şekilde iş kaydının hedeflediği problemi tanımla)
[//]: # (Kısa ve net bir şekilde çözüm önerini yaz)

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [x] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] İş kaydı hata bildirimi veya ürün özelliği dışında bir niteliğe sahip
- [x] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by ecmelkytz** [comment]
Akademik mesleki deneyimler için `AcademicCredential` model ismini kullanmayı düşünüyorum. Siz ne dersiniz, uygun mudur?

**Comment by baran** [comment]
@roktas _öncelikle gözümden kaçmış olabileceğini belirterek_ bu soru cümlesi hakkındaki görüşümü paylaşayım. Bu tür işlemler için "oylamadan" ziyade bu ve buna benzer durumları yönetecek bir yönergenin çalışmasını yapalım diyorum hocam. Böylece geliştiricinin ***ikilemde*** kalmasının önüne geçtiğimiz gibi zaman kaybının da önüne geçmiş oluruz.
