### ISSUE TITLE
Personel ayarlar sayfası oluşturulmalı

### ISSUE THREAD

**Issue by ecmelkytz** [omu/nokul#986]
#### İş kaydı

Personeller için #944 iş kaydında belirlenen ayarlar sayfası oluşturulmalı.

Ayarlar sayfası görüntüsü:

![ayarlar](https://user-images.githubusercontent.com/937358/64317271-df166200-cfbf-11e9-8e8b-8e7fbb455073.png)

[//]: # (Kısa ve net şekilde iş kaydının hedeflediği problemi tanımla)
[//]: # (Kısa ve net bir şekilde çözüm önerini yaz)

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [x] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] İş kaydı hata bildirimi veya ürün özelliği dışında bir niteliğe sahip
- [x] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by ecmelkytz** [comment]
Netleşmesini istediğim bir kaç husus var: @omu/product 
1) `User` için 2 email(bir tanesi default omu hesabı) ve 2 telefon girişine izin verilecek mi? 
2) Yönet/Değiştir butonlarına basınca işlem için başka bir sayfaya mı yönlendirme yapılacak?

**Comment by huseyin** [comment]
Email ve telefon için görüşüm şöyle:
- Email, `omu` alan adı içerisinde bir tane olmalı fakat bir veya daha fazla alias eklenebilmeli (belki bir üst limitle ve/veya operasyonel tarafının bizde olmasıyla sınırlandırılabilir)
- Doğrulanmış telefon numarası bir tane olmalı. Gerekirse süper kullanıcı yetkisiyle değiştirilebilir (parolasını sorma vesaire gibi).

**Comment by ekural** [comment]
@ecmelkytz 
1. Soru için: Bu konuyu izin verilebilir şeklinde konuşmuştuk ama @roktas şimdilik buna öncelik vermemizi söylemişti. 
2. Soru için: Evet ilgili sayfaya yönlendirilerek orada değişiklik yapacak diye düşünmüştük.

**Comment by ecmelkytz** [comment]
Tamamdır o halde email ve telefonla ilgili bir değişiklik yapmadan sayfayı oluşturuyorum.
