### ISSUE TITLE
Kullanıcı dashboard sayfası oluşturulmalı

### ISSUE THREAD

**Issue by ecmelkytz** [omu/nokul#987]
#### İş kaydı
Personel için #944 iş kaydında belirlenen dashboard oluşturulmalı.

![](https://user-images.githubusercontent.com/618030/61530485-d4facd00-aa2c-11e9-84da-c3b606184fb9.png)

[//]: # (Kısa ve net şekilde iş kaydının hedeflediği problemi tanımla)
[//]: # (Kısa ve net bir şekilde çözüm önerini yaz)

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [x] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] İş kaydı hata bildirimi veya ürün özelliği dışında bir niteliğe sahip
- [x] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by baran** [comment]
Bu issue'da son durum nedir?

**Comment by ecmelkytz** [comment]
İş kaydı içeriği bazı hususlara göre netleşip gerekirse güncellenmeli.

1. Sidebar mockup çalışması yapılmıştı bu dahil olacak mı?
2. Şu an kişiyle alakalı bütün bilgiler aynı sayfada gözüküyor. Bilgilerin gösterimi kişinin tercihine bırakılacaktı ancak bizim de default bir değer atamamız gerekiyor. Öğrenciliği ve personelliği olan birisi için tercih neye göre yapılacak?

**Comment by baran** [comment]
> 1. Sidebar mockup çalışması yapılmıştı bu dahil olacak mı?

Konuyla alakalı olarak @isubas görüşüldü. Detayları ondan alabilirsin.

> 2. Şu an kişiyle alakalı bütün bilgiler aynı sayfada gözüküyor. Bilgilerin gösterimi kişinin tercihine bırakılacaktı ancak bizim de default bir değer atamamız gerekiyor. Öğrenciliği ve personelliği olan birisi için tercih neye göre yapılacak?

Bu konuda 1. maddedeki durum geçerli.

>    Edit: Bu değişim ayarlar altında tercihler kısmından mı yapılmalı yoksa UX anlamında daha kolay bir yerden mi değiştirilmeli?

Bu konuda da 1. maddedeki durum geçerli. Kullanıcı deneyimlerine dayalı olarak sonrasında değişiklik yapılabilecek unsurlarda vakit kaybetmeye gerek kalmadan kodu tamamlayalım. Gerek duyulduğunda A/B testleri eklenerek en uygun seçeneğe sonrasında karar verilebilir.

**Comment by baran** [comment]
Sidebar ayrı bir görev olarak tanımlanacak. Sidebar bitiminden sonra bu issue devam edecek.

**Comment by baran** [comment]
Bloklayan isseu: #1179

**Comment by isubas** [comment]
Tekrardan tasarlanmak ve iş kaydı açmak için kapatıyorum.
