### ISSUE TITLE
Ülkelere YÖKSİS kodlarını ekle

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#99]
Mevcut seed dosyası ISO kodları (alpha2, alpha3 ve numeric) ekliyor. Bunun yanı sıra MERNİS kodlarını da ekliyor.

Ancak YÖKSİS kafasına göre ülkelere numara vermiş. Bizim ülkeler modeline `yoksis_code` isimli integer bir alan ekleyelim. Statik bir CSV'den bu kodları ülkeleri eklesin.

Tabii bu işlem seed olmayacak çünkü artık DB sıfırlamıyoruz. Dolayısıyla bir rake task yazılmalı.

Sorun şu - YÖKSİS'in ülkelere verdiği isimler bizde tutulan ile eşleşmeyebiliyor - orada manuel düzeltmeler lazım. Yani özetle:

0) Ülkeler modeline yoksis_code alanı ekle.
1) Ülke adı - yoksis kodu içeren bir CSV hazırla.
2) Bu listeyi okuyarak ülkelerin yoksis_code alanını güncelleyen rake task'i yaz.

YOKSIS'te tüm ülkeler olmayabilir - dert değil.

YOKSIS kodları şurada: https://gist.github.com/msdundar/4e4d5e90d044462db70e9eb18fb9d2ef

@sinansahin bu işe bakabilir misin? seni repoya da ekledim, daveti kabul edene kadar işi assign edemedim, sen kendini edersin :)

**Comment by msdundar** [comment]
Ek olarak şöyle çalışıyoruz:

`develop`'un son halini çekiyorsun. `develop`'tan yeni branch çıkıyorsun.

sen çalışırken branch'te birileri değişiklik yaparsa yeni değişiklikleri kendine alıyorsun. eğer conflict çıkarsa bunları kod üzerinde çözüp commitliyorsun ve çalışmaya devam ediyorsun.

her şey bitince çalıştığın branch'i push edip, çalıştığın branch'ten develop'a PR açıyorsun.

**Comment by sinansahin** [comment]
MERNİS datasında `Kıbrıs` adında 1 ülke var. YÖKSİS datasında ise `Güney Kibris Rum Kesimi` ve `Kktc` olarak 2 farklı ülke var. Manuel düzeltmede hangi ülkenin kodunu baz alacağız?

**Comment by isubas** [comment]
@sinansahin  sen şimdilik `KKTC` ile eşleştir.

**Comment by sinansahin** [comment]
YÖKSİS'te `958 BİLİNMEYEN ÜLKELER(DİĞER) ` şeklinde bir değer var.

YÖKSİS'te eksik olan diğer ülkelere yoksis_code olarak 958 değeri işlenmeli mi ? 

YÖKSİS'te olup MERNİS'te karşılığını bulamadığım ülkeler:
```
Ceuta
Melilla
Holanda Antilleri
Güney Kıbrıs Rum Kesimi
```

**Comment by msdundar** [comment]
Bu 4 ülkeye 958 diyebiliriz öyleyse

**Comment by sinansahin** [comment]
Hocam commenti güncelledim, ufak yazım hatası yapmışım anlam değişmiş. Bu ülkeler veritabanımızda hiç yok. 

Aşağıdaki ülkeler veritabanımızda var fakat YÖKSİS'te yok. Bu ülkelere 958 kodu eklenecek şekilde task'ı güncelliyorum o zaman. 

```
Aland Adaları
Batı Sahra
Bonaire, Sint Eustatius Ve Saba
Curaçao
Fransız Guyanası
Guadeloupe
Guernsey
Güney Sudan
Jersey
Man Adası
Martinik
Monako
Porto Riko
Reunion
Saint Barthelemy
Saint Martin
Sint Maarten
Svalbard Ve Jan Mayen
```
